<cfif NOT structKeyExists(VARIABLES,'cpCoupon') OR NOT cpCoupon.recordcount><cfheader statuscode="403"/><cfabort/></cfif>
<cfoutput>
<section class="cp-links"><h3>Eventos vinculados</h3><p class="cp-help">A vigência abaixo se aplica a cada evento. A expiração geral do cupom também deve ser respeitada.</p>
<cfloop query="cpLinks">
<article class="cp-link"><strong>#encodeForHTML(cpLinks.nome_evento)#</strong><p>#cpDate(cpLinks.data_validade_inicio)# até #cpDate(cpLinks.data_validade_fim)#</p><small>Quantidade acordada: #len(cpLinks.qtd_limite_cupom & '') ? encodeForHTML(cpLinks.qtd_limite_cupom) : 'Não informada'#</small>
<cfif cpCanEdit><div class="cp-actions mt-2"><button class="btn btn-sm btn-outline-secondary" type="button" data-cp-edit-link data-event="#cpLinks.id_evento#" data-label="#encodeForHTMLAttribute(cpLinks.nome_evento)#" data-start="#isDate(cpLinks.data_validade_inicio) ? dateFormat(cpLinks.data_validade_inicio,'yyyy-mm-dd') : ''#" data-end="#isDate(cpLinks.data_validade_fim) ? dateFormat(cpLinks.data_validade_fim,'yyyy-mm-dd') : ''#" data-quantity="#encodeForHTMLAttribute(cpLinks.qtd_limite_cupom)#">Editar vínculo</button>
<cfif cpAccess.admin OR cpLinks.recordcount GT 1><form method="post" action="./?cupom_id=#cpSelected###cp-editor" data-cp-confirm="Desvincular este evento do cupom? Você poderá vinculá-lo novamente."><input type="hidden" name="csrf" value="#encodeForHTMLAttribute(SESSION.couponManagerCsrf)#"/><input type="hidden" name="coupon_action" value="desvincular"/><input type="hidden" name="id_cupom" value="#cpSelected#"/><input type="hidden" name="revision" value="#encodeForHTMLAttribute(cpCoupon.revision)#"/><input type="hidden" name="id_evento_cupom" value="#cpLinks.id_evento_cupom#"/><button type="submit" class="btn btn-sm btn-link text-warning">Desvincular</button></form></cfif></div></cfif>
</article>
</cfloop>
<cfif NOT cpLinks.recordcount><p class="cp-help">Nenhum evento diretamente vinculado nesta conta.</p></cfif>
<cfif cpOthers.recordcount><h3 class="mt-3">Outros vínculos existentes</h3><cfloop query="cpOthers"><p>#encodeForHTML(cpOthers.tipo)# · #encodeForHTML(cpOthers.nome)#</p></cfloop><p class="cp-help">Os vínculos de páginas e circuitos são preservados. Alterar os dados gerais do cupom também afeta esses vínculos.</p></cfif>
<cfif cpCanEdit>
<details class="cp-link-editor" <cfif len(cpError) AND (FORM.coupon_action ?: '') EQ 'vincular'>open</cfif>><summary>Vincular evento ou ajustar validade</summary><form method="post" action="./?cupom_id=#cpSelected###cp-editor" data-cp-form data-cp-link-form><input type="hidden" name="csrf" value="#encodeForHTMLAttribute(SESSION.couponManagerCsrf)#"/><input type="hidden" name="coupon_action" value="vincular"/><input type="hidden" name="id_cupom" value="#cpSelected#"/><input type="hidden" name="revision" value="#encodeForHTMLAttribute(cpCoupon.revision)#"/><cfset cpPickerPrefix='link'/><cfinclude template="event-fields.cfm"/><button class="btn btn-warning mt-3" type="submit" <cfif cpConflict>disabled</cfif>>Salvar vínculo</button><p class="cp-help" data-cp-feedback role="status"></p></form></details>
<form class="cp-status-action" method="post" action="./?cupom_id=#cpSelected###cp-editor" data-cp-confirm="#cpCoupon.ativo ? 'Desativar o cupom para todos os seus vínculos?' : 'Reativar o cupom? Confira a validade de todos os seus vínculos.'#"><input type="hidden" name="csrf" value="#encodeForHTMLAttribute(SESSION.couponManagerCsrf)#"/><input type="hidden" name="coupon_action" value="status"/><input type="hidden" name="id_cupom" value="#cpSelected#"/><input type="hidden" name="revision" value="#encodeForHTMLAttribute(cpCoupon.revision)#"/><input type="hidden" name="ativo" value="#cpCoupon.ativo ? 'false' : 'true'#"/><button class="btn btn-outline-warning" type="submit">#cpCoupon.ativo ? 'Desativar cupom' : 'Reativar cupom'#</button></form>
</cfif>
</section>
</cfoutput>
