-- Pacote de apresentação 2025. Somente resultados congelados; não consulta tabelas de atletas/resultados.
-- Troque os IDs explicitamente depois de revisar e congelar novas coletas. Nada muda na web ao executar/congelar.
WITH b AS (SELECT payload FROM estudo.web_bases WHERE ano=2025),
r AS (SELECT * FROM estudo.notebook_runs WHERE frozen AND status='ok' AND NOT truncated AND id IN (6,7,8,15,16,17,25)),
m AS (
SELECT 'sexo_2024' AS serie,'F' AS categoria,jsonb_build_object('valor',v->'porcentagem','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip 2024'),'fonte','Notebook · execução #6','nota','Participações tratadas; todas as categorias de sexo no denominador. Em 2025, exige tempo positivo.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=6 AND v->>'versao'='DataGrip 2024' AND v->>'genero'='F'
UNION ALL
SELECT 'sexo_2024' AS serie,'M' AS categoria,jsonb_build_object('valor',v->'porcentagem','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip 2024'),'fonte','Notebook · execução #6','nota','Participações tratadas; todas as categorias de sexo no denominador. Em 2025, exige tempo positivo.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=6 AND v->>'versao'='DataGrip 2024' AND v->>'genero'='M'
UNION ALL
SELECT 'sexo_2025' AS serie,'F' AS categoria,jsonb_build_object('valor',v->'porcentagem','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip 2025 (tempo positivo)'),'fonte','Notebook · execução #6','nota','Participações tratadas; todas as categorias de sexo no denominador. Em 2025, exige tempo positivo.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=6 AND v->>'versao'='DataGrip 2025 (tempo positivo)' AND v->>'genero'='F'
UNION ALL
SELECT 'sexo_2025' AS serie,'M' AS categoria,jsonb_build_object('valor',v->'porcentagem','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip 2025 (tempo positivo)'),'fonte','Notebook · execução #6','nota','Participações tratadas; todas as categorias de sexo no denominador. Em 2025, exige tempo positivo.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=6 AND v->>'versao'='DataGrip 2025 (tempo positivo)' AND v->>'genero'='M'
UNION ALL
SELECT 'distancias_faixas' AS serie,'Até 5 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x),'fonte','Notebook · execução #15','nota','Faixas legadas de distância, preservadas no notebook.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=15 AND v->>'percurso'='< 6'
UNION ALL
SELECT 'distancia_dentro_sexo_F' AS serie,'Até 5 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='F'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='< 6' AND v->>'sexo'='F'
UNION ALL
SELECT 'distancia_dentro_sexo_M' AS serie,'Até 5 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='M'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='< 6' AND v->>'sexo'='M'
UNION ALL
SELECT 'distancias_faixas' AS serie,'6 a 10 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x),'fonte','Notebook · execução #15','nota','Faixas legadas de distância, preservadas no notebook.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=15 AND v->>'percurso'='6-11'
UNION ALL
SELECT 'distancia_dentro_sexo_F' AS serie,'6 a 10 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='F'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='6-11' AND v->>'sexo'='F'
UNION ALL
SELECT 'distancia_dentro_sexo_M' AS serie,'6 a 10 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='M'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='6-11' AND v->>'sexo'='M'
UNION ALL
SELECT 'distancias_faixas' AS serie,'11 a 29 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x),'fonte','Notebook · execução #15','nota','Faixas legadas de distância, preservadas no notebook.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=15 AND v->>'percurso'='11-30'
UNION ALL
SELECT 'distancia_dentro_sexo_F' AS serie,'11 a 29 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='F'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='11-30' AND v->>'sexo'='F'
UNION ALL
SELECT 'distancia_dentro_sexo_M' AS serie,'11 a 29 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='M'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='11-30' AND v->>'sexo'='M'
UNION ALL
SELECT 'distancias_faixas' AS serie,'+30 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x),'fonte','Notebook · execução #15','nota','Faixas legadas de distância, preservadas no notebook.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=15 AND v->>'percurso'='30+'
UNION ALL
SELECT 'distancia_dentro_sexo_F' AS serie,'+30 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='F'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='30+' AND v->>'sexo'='F'
UNION ALL
SELECT 'distancia_dentro_sexo_M' AS serie,'+30 km' AS categoria,jsonb_build_object('valor',v->'perc','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'sexo'='M'),'fonte','Notebook · execução #16','nota','Distribuição dentro de cada sexo; denominador corrigido explicitamente na consulta candidata.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=16 AND v->>'percurso'='30+' AND v->>'sexo'='M'
UNION ALL
SELECT 'eventos_com_5km' AS serie,'5 km' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'eventos_com_5km','denominador',(v->>'eventos_com_resultados_rua')::bigint,'fonte','Notebook · execução #17','nota','Eventos de rua com resultados tratados; não usa todos os eventos cadastrados.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=17 AND true
UNION ALL
SELECT 'meses' AS serie,'Jan' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=1
UNION ALL
SELECT 'meses' AS serie,'Fev' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=2
UNION ALL
SELECT 'meses' AS serie,'Mar' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=3
UNION ALL
SELECT 'meses' AS serie,'Abr' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=4
UNION ALL
SELECT 'meses' AS serie,'Mai' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=5
UNION ALL
SELECT 'meses' AS serie,'Jun' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=6
UNION ALL
SELECT 'meses' AS serie,'Jul' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=7
UNION ALL
SELECT 'meses' AS serie,'Ago' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=8
UNION ALL
SELECT 'meses' AS serie,'Set' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=9
UNION ALL
SELECT 'meses' AS serie,'Out' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=10
UNION ALL
SELECT 'meses' AS serie,'Nov' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=11
UNION ALL
SELECT 'meses' AS serie,'Dez' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Mês'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Mês' AND (v->>'ordem')::int=12
UNION ALL
SELECT 'trimestres' AS serie,'1' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Trimestre'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Trimestre' AND (v->>'ordem')::int=1
UNION ALL
SELECT 'trimestres' AS serie,'2' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Trimestre'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Trimestre' AND (v->>'ordem')::int=2
UNION ALL
SELECT 'trimestres' AS serie,'3' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Trimestre'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Trimestre' AND (v->>'ordem')::int=3
UNION ALL
SELECT 'trimestres' AS serie,'4' AS categoria,jsonb_build_object('valor',v->'percentual','contagem',v->'total','denominador',(SELECT sum((x->>'total')::bigint) FROM jsonb_array_elements(r.result->'rows') x WHERE x->>'versao'='DataGrip' AND x->>'periodo'='Trimestre'),'fonte','Notebook · execução #25','nota','Resultados tratados de 2025; denominador anual. Data usada: data_final do evento.') AS atual FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') v WHERE r.id=25 AND v->>'versao'='DataGrip' AND v->>'periodo'='Trimestre' AND (v->>'ordem')::int=4
), comps AS (
 SELECT jsonb_build_object('serie',z.value->>'serie','categoria',z.value->>'categoria',
 'atual',CASE WHEN m.atual IS NOT NULL THEN m.atual WHEN jsonb_typeof(z.value->'atual')='object' THEN (z.value->'atual') || jsonb_build_object('fonte','Snapshot inicial · coleta 26/09/2026; fonte ainda em conciliação') ELSE 'null'::jsonb END,
 'status',CASE WHEN m.atual IS NOT NULL THEN 'notebook_em_conciliacao' ELSE z.value->>'status' END) AS item,z.ordinality AS n
 FROM b CROSS JOIN LATERAL jsonb_array_elements(b.payload->'comparacoes') WITH ORDINALITY z
 LEFT JOIN m ON m.serie=z.value->>'serie' AND m.categoria=z.value->>'categoria'
)
SELECT b.payload || jsonb_build_object(
 'meta',(b.payload->'meta') || jsonb_build_object('origem','Notebook Business + fontes iniciais identificadas','totais_fontes',jsonb_build_object('resultados','vw_resultados · notebook, execução #7','eventos','Eventos no Brasil · notebook, execução #8'),'notebook_fontes',(SELECT jsonb_agg(jsonb_build_object('execucao',id,'celula',cell_id,'revisao',cell_version,'coletado_em',started_at) ORDER BY id) FROM r)),
 'comparacoes',(SELECT jsonb_agg(item ORDER BY n) FROM comps),
 'conciliacao',(SELECT jsonb_object_agg(status,n) FROM (SELECT item->>'status' AS status,count(*) AS n FROM comps GROUP BY item->>'status') q),
 'totais_atuais',jsonb_build_object('resultados',(SELECT x->'total' FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') x WHERE r.id=7 AND x->>'versao'='DataGrip'),
 'eventos',(SELECT x->'eventos_cadastrados' FROM r CROSS JOIN LATERAL jsonb_array_elements(r.result->'rows') x WHERE r.id=8 AND x->>'ano'='2025'))
) AS payload FROM b WHERE (SELECT count(*) FROM r)=7