-- Apply as runner_dba in one transaction after private backup and preflight.
-- Moves the existing notebook tables. Does not modify estudo.snapshots.
SET LOCAL lock_timeout='3s';
SET LOCAL statement_timeout='30s';
SELECT pg_advisory_xact_lock(9282026,1);
DO $preflight$
BEGIN
 IF to_regnamespace('estudo') IS NULL THEN RAISE EXCEPTION 'Schema estudo ausente'; END IF;
 IF to_regclass('public.notebooks') IS NULL OR to_regclass('public.notebook_cells') IS NULL THEN
   RAISE EXCEPTION 'Acervo de origem ausente ou migracao ja aplicada; conferir recibo antes de repetir';
 END IF;
 IF to_regclass('estudo.notebooks') IS NOT NULL OR to_regclass('estudo.notebook_cells') IS NOT NULL THEN
   RAISE EXCEPTION 'Destino ja existe; migracao interrompida';
 END IF;
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='estudo_reader') THEN
   RAISE EXCEPTION 'Papel estudo_reader ja existe; revisar antes da migracao';
 END IF;
END;
$preflight$;
LOCK TABLE public.notebooks,public.notebook_cells IN ACCESS EXCLUSIVE MODE;
DO $validate$
BEGIN
 IF EXISTS(SELECT notebook_id FROM public.notebooks GROUP BY notebook_id HAVING count(*)>1)
 OR EXISTS(SELECT 1 FROM public.notebooks WHERE notebook_title IS NULL)
 OR EXISTS(SELECT 1 FROM public.notebook_cells c LEFT JOIN public.notebooks n USING(notebook_id) WHERE n.notebook_id IS NULL)
 THEN RAISE EXCEPTION 'Acervo legado inconsistente; corrigir antes de migrar'; END IF;
END;
$validate$;
CREATE TABLE estudo.notebook_migrations (
 migration_key text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 before_counts jsonb NOT NULL, before_hashes jsonb NOT NULL
);
INSERT INTO estudo.notebook_migrations(migration_key,before_counts,before_hashes)
SELECT '2026-09-28-notebooks-v1',
 jsonb_build_object('notebooks',(SELECT count(*) FROM public.notebooks),'cells',(SELECT count(*) FROM public.notebook_cells)),
 jsonb_build_object(
 'notebooks',(SELECT encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(n) ORDER BY notebook_id)::text,'[]'),'UTF8')),'hex') FROM public.notebooks n),
 'cells',(SELECT encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(c) ORDER BY id)::text,'[]'),'UTF8')),'hex') FROM public.notebook_cells c));

ALTER TABLE public.notebooks SET SCHEMA estudo;
ALTER TABLE public.notebook_cells SET SCHEMA estudo;

CREATE TABLE estudo.cadernos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 titulo text NOT NULL CHECK(length(btrim(titulo)) BETWEEN 1 AND 200),
 ano smallint CHECK(ano BETWEEN 1900 AND 9999), descricao text NOT NULL DEFAULT '',
 source_key text UNIQUE, version integer NOT NULL DEFAULT 1,
 criado_em timestamptz NOT NULL DEFAULT clock_timestamp(), criado_por bigint,
 atualizado_em timestamptz NOT NULL DEFAULT clock_timestamp(), atualizado_por bigint
);
INSERT INTO estudo.cadernos(id,titulo,ano,descricao,source_key)
 VALUES(1,'Brasil que Corre Provas — 2025',2025,'Acervo original do editor RunnerHub. Queries e resultados HTML historicos preservados.','legacy-runnerhub-2025');
SELECT setval(pg_get_serial_sequence('estudo.cadernos','id'),1,true);
ALTER TABLE estudo.notebooks ADD PRIMARY KEY(notebook_id);
ALTER TABLE estudo.notebooks ADD COLUMN caderno_id bigint NOT NULL DEFAULT 1 REFERENCES estudo.cadernos(id);
ALTER TABLE estudo.notebooks ADD COLUMN version integer NOT NULL DEFAULT 1;
ALTER TABLE estudo.notebooks ADD COLUMN archived boolean NOT NULL DEFAULT false;
ALTER TABLE estudo.notebooks ADD COLUMN updated_at timestamptz NOT NULL DEFAULT clock_timestamp();
ALTER TABLE estudo.notebooks ADD COLUMN updated_by bigint;
ALTER TABLE estudo.notebooks ADD COLUMN source_key text UNIQUE;

ALTER TABLE estudo.notebook_cells ADD CONSTRAINT notebook_cells_notebook_fk FOREIGN KEY(notebook_id) REFERENCES estudo.notebooks(notebook_id);
ALTER TABLE estudo.notebook_cells ADD COLUMN version integer NOT NULL DEFAULT 1;
ALTER TABLE estudo.notebook_cells ADD COLUMN archived boolean NOT NULL DEFAULT false;
ALTER TABLE estudo.notebook_cells ADD COLUMN updated_by bigint;
ALTER TABLE estudo.notebook_cells ADD COLUMN origem jsonb NOT NULL DEFAULT '{"tipo":"editor_legado"}';
ALTER TABLE estudo.notebook_cells ADD COLUMN source_key text UNIQUE;
ALTER TABLE estudo.notebook_cells ADD CONSTRAINT notebook_cells_origin_object CHECK(jsonb_typeof(origem)='object');
SELECT setval(pg_get_serial_sequence('estudo.notebooks','notebook_id'),greatest(coalesce((SELECT max(notebook_id) FROM estudo.notebooks),1),(SELECT last_value FROM estudo.notebooks_notebook_id_seq)),true);
SELECT setval(pg_get_serial_sequence('estudo.notebook_cells','id'),greatest(coalesce((SELECT max(id) FROM estudo.notebook_cells),1),(SELECT last_value FROM estudo.notebook_cells_id_seq)),true);

CREATE TABLE estudo.notebook_revisions (
 cell_id bigint NOT NULL REFERENCES estudo.notebook_cells(id),
 version integer NOT NULL CHECK(version>0),
 notebook_id bigint NOT NULL, cell_type text NOT NULL,lang text,content text NOT NULL,
 archived boolean NOT NULL, origem jsonb NOT NULL,
 saved_at timestamptz NOT NULL, saved_by bigint,content_sha256 text NOT NULL,
 PRIMARY KEY(cell_id,version)
);
INSERT INTO estudo.notebook_revisions
 SELECT id,version,notebook_id,cell_type,lang,content,archived,origem,updated_at,updated_by,
 encode(sha256(convert_to(content,'UTF8')),'hex') FROM estudo.notebook_cells;

CREATE FUNCTION estudo.notebook_cell_version() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$
BEGIN
 IF TG_OP='INSERT' THEN NEW.version:=1;
 ELSE NEW.version:=OLD.version+1; END IF;
 NEW.updated_at:=clock_timestamp();
 RETURN NEW;
END;
$fn$;
CREATE FUNCTION estudo.notebook_cell_revision() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$
BEGIN
 INSERT INTO estudo.notebook_revisions
 VALUES(NEW.id,NEW.version,NEW.notebook_id,NEW.cell_type,NEW.lang,NEW.content,NEW.archived,NEW.origem,NEW.updated_at,NEW.updated_by,encode(sha256(convert_to(NEW.content,'UTF8')),'hex'));
 RETURN NEW;
END;
$fn$;
CREATE FUNCTION estudo.notebook_immutable() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$
BEGIN RAISE EXCEPTION 'Registro imutavel: crie outra versao'; END;
$fn$;
CREATE FUNCTION estudo.notebook_archive_only() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$
BEGIN RAISE EXCEPTION 'Use arquivamento; exclusao do historico nao permitida'; END;
$fn$;
CREATE TRIGGER notebook_cell_version BEFORE INSERT OR UPDATE ON estudo.notebook_cells FOR EACH ROW EXECUTE FUNCTION estudo.notebook_cell_version();
CREATE TRIGGER notebook_cell_revision AFTER INSERT OR UPDATE ON estudo.notebook_cells FOR EACH ROW EXECUTE FUNCTION estudo.notebook_cell_revision();
CREATE TRIGGER notebook_cell_no_delete BEFORE DELETE ON estudo.notebook_cells FOR EACH ROW EXECUTE FUNCTION estudo.notebook_archive_only();
CREATE TRIGGER notebook_cell_no_truncate BEFORE TRUNCATE ON estudo.notebook_cells FOR EACH STATEMENT EXECUTE FUNCTION estudo.notebook_archive_only();
CREATE TRIGGER notebook_revision_immutable BEFORE UPDATE OR DELETE ON estudo.notebook_revisions FOR EACH ROW EXECUTE FUNCTION estudo.notebook_immutable();
CREATE TRIGGER notebook_revision_no_truncate BEFORE TRUNCATE ON estudo.notebook_revisions FOR EACH STATEMENT EXECUTE FUNCTION estudo.notebook_immutable();

CREATE TABLE estudo.notebook_runs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cell_id bigint NOT NULL,cell_version integer NOT NULL,
 sql_text text NOT NULL,sql_sha256 text NOT NULL CHECK(sql_sha256 ~ '^[a-f0-9]{64}$'),
 executed_by bigint NOT NULL,started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 finished_at timestamptz,duration_ms integer CHECK(duration_ms>=0),
 status text NOT NULL CHECK(status IN ('running','ok','error')),
 result jsonb,row_count integer NOT NULL DEFAULT 0 CHECK(row_count>=0),
 truncated boolean NOT NULL DEFAULT false,error_message text NOT NULL DEFAULT '',
 frozen boolean NOT NULL DEFAULT false,frozen_at timestamptz,frozen_by bigint,
 title text NOT NULL DEFAULT '',note text NOT NULL DEFAULT '',
 FOREIGN KEY(cell_id,cell_version) REFERENCES estudo.notebook_revisions(cell_id,version),
 CHECK(result IS NULL OR (jsonb_typeof(result)='object' AND jsonb_typeof(result->'columns')='array' AND jsonb_typeof(result->'rows')='array')),
 CHECK(status<>'ok' OR (result IS NOT NULL AND row_count=jsonb_array_length(result->'rows'))),
 CHECK(NOT frozen OR (status='ok' AND NOT truncated AND length(btrim(title)) BETWEEN 1 AND 200))
);
CREATE INDEX notebook_runs_cell_time ON estudo.notebook_runs(cell_id,id DESC);
CREATE FUNCTION estudo.notebook_run_protect() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$
BEGIN
 IF TG_OP IN ('DELETE','TRUNCATE') THEN RAISE EXCEPTION 'Execucao imutavel'; END IF;
 IF TG_OP='INSERT' THEN
   IF NEW.frozen THEN RAISE EXCEPTION 'Congele somente uma execucao salva completa'; END IF;
   RETURN NEW;
 END IF;
 IF OLD.frozen THEN RAISE EXCEPTION 'Resultado congelado imutavel'; END IF;
 IF OLD.status='running' AND NEW.status IN ('ok','error') AND NOT NEW.frozen THEN
   IF NEW.cell_id<>OLD.cell_id OR NEW.cell_version<>OLD.cell_version OR NEW.sql_text<>OLD.sql_text OR NEW.sql_sha256<>OLD.sql_sha256 OR NEW.executed_by<>OLD.executed_by OR NEW.started_at<>OLD.started_at THEN
     RAISE EXCEPTION 'Identidade da execucao imutavel';
   END IF;
   RETURN NEW;
 END IF;
 IF OLD.status='ok' AND NEW.frozen AND NOT OLD.truncated
   AND (to_jsonb(NEW)-ARRAY['frozen','frozen_at','frozen_by','title','note'])=(to_jsonb(OLD)-ARRAY['frozen','frozen_at','frozen_by','title','note'])
 THEN
   IF length(btrim(NEW.title)) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'Titulo do congelamento obrigatorio'; END IF;
   NEW.frozen_at:=clock_timestamp();
   RETURN NEW;
 END IF;
 RAISE EXCEPTION 'Execucao imutavel; congelamento exige resultado completo';
END;
$fn$;
CREATE TRIGGER notebook_run_protect BEFORE INSERT OR UPDATE OR DELETE ON estudo.notebook_runs FOR EACH ROW EXECUTE FUNCTION estudo.notebook_run_protect();
CREATE TRIGGER notebook_run_no_truncate BEFORE TRUNCATE ON estudo.notebook_runs FOR EACH STATEMENT EXECUTE FUNCTION estudo.notebook_run_protect();

CREATE ROLE estudo_reader NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
GRANT USAGE ON SCHEMA public,estudo TO estudo_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO estudo_reader;
GRANT SELECT ON estudo.snapshots,estudo.notebooks,estudo.notebook_cells,estudo.notebook_revisions,estudo.notebook_runs,estudo.cadernos TO estudo_reader;
REVOKE ALL ON estudo.notebooks,estudo.notebook_cells,estudo.notebook_revisions,estudo.notebook_runs,estudo.cadernos,estudo.notebook_migrations FROM PUBLIC;
REVOKE ALL ON FUNCTION estudo.notebook_cell_version(),estudo.notebook_cell_revision(),estudo.notebook_immutable(),estudo.notebook_archive_only(),estudo.notebook_run_protect() FROM PUBLIC;
COMMENT ON TABLE estudo.notebook_runs IS 'Execucoes administrativas de leitura; congelamentos completos preservam SQL, revisao e resultado para futura publicacao. Sem acesso publico direto.';
COMMENT ON TABLE estudo.notebook_revisions IS 'Historico de celulas a partir da migracao do editor; registros imutaveis.';
