BEGIN;

CREATE TABLE IF NOT EXISTS public.tb_evento_saude_config
(
    id_evento                integer PRIMARY KEY
        REFERENCES public.tb_evento_corridas (id_evento)
        ON UPDATE CASCADE ON DELETE CASCADE,
    ativo                    boolean                  NOT NULL DEFAULT false,
    nome_operacao            varchar(120)             NOT NULL DEFAULT 'Central de Saúde',
    percurso_padrao          numeric,
    intervalo_atualizacao    integer                  NOT NULL DEFAULT 15,
    inicio_operacao          timestamp with time zone,
    fim_operacao             timestamp with time zone,
    local_atendimento        varchar(180),
    id_diretor_medico        integer
        REFERENCES public.tb_usuarios (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    diretor_medico           varchar(160),
    whatsapp_equipe          varchar(20),
    instrucoes               text,
    id_usuario_atualizacao   bigint,
    data_criacao             timestamp with time zone NOT NULL DEFAULT now(),
    data_atualizacao         timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tb_evento_saude_config_intervalo_ck
        CHECK (intervalo_atualizacao BETWEEN 10 AND 300),
    CONSTRAINT tb_evento_saude_config_periodo_ck
        CHECK (fim_operacao IS NULL OR inicio_operacao IS NULL OR fim_operacao >= inicio_operacao),
    CONSTRAINT tb_evento_saude_config_percurso_fk
        FOREIGN KEY (id_evento, percurso_padrao)
        REFERENCES public.tb_evento_corridas_percursos (id_evento, percurso_evento)
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS tb_evento_saude_config_ativo_idx
    ON public.tb_evento_saude_config (ativo, inicio_operacao, fim_operacao);

ALTER TABLE public.tb_evento_saude_config
    ALTER COLUMN nome_operacao SET DEFAULT 'Central de Saúde';

ALTER TABLE public.tb_evento_saude_config
    ALTER COLUMN intervalo_atualizacao SET DEFAULT 15;

ALTER TABLE public.tb_evento_saude_config
    ADD COLUMN IF NOT EXISTS id_diretor_medico integer,
    ADD COLUMN IF NOT EXISTS diretor_medico varchar(160),
    ADD COLUMN IF NOT EXISTS whatsapp_equipe varchar(20);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tb_evento_saude_config_diretor_fk'
          AND conrelid = 'public.tb_evento_saude_config'::regclass
    ) THEN
        ALTER TABLE public.tb_evento_saude_config
            ADD CONSTRAINT tb_evento_saude_config_diretor_fk
            FOREIGN KEY (id_diretor_medico)
            REFERENCES public.tb_usuarios (id)
            ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS tb_evento_saude_config_diretor_idx
    ON public.tb_evento_saude_config (id_diretor_medico);

WITH diretor_candidatos AS (
    SELECT cfg.id_evento,
           min(usr.id) AS id_usuario,
           count(DISTINCT usr.id) AS total
    FROM public.tb_evento_saude_config cfg
    INNER JOIN public.tb_conta_eventos ce
        ON ce.id_evento = cfg.id_evento
       AND ce.status = 'ATIVO'::public.status_conta_evento
    INNER JOIN public.tb_conta_usuarios cu
        ON cu.id_conta = ce.id_conta
       AND cu.papel = 'MEDICO'::public.papel_usuario_conta
       AND cu.status = 'ATIVO'::public.status_usuario_conta
    INNER JOIN public.tb_usuarios usr
        ON usr.id = cu.id_usuario
       AND lower(trim(usr.name)) = lower(trim(cfg.diretor_medico))
    WHERE cfg.id_diretor_medico IS NULL
      AND nullif(trim(cfg.diretor_medico), '') IS NOT NULL
    GROUP BY cfg.id_evento
)
UPDATE public.tb_evento_saude_config cfg
SET id_diretor_medico = diretor_candidatos.id_usuario
FROM diretor_candidatos
WHERE cfg.id_evento = diretor_candidatos.id_evento
  AND diretor_candidatos.total = 1;

UPDATE public.tb_evento_saude_config
SET nome_operacao = 'Central de Saúde',
    data_atualizacao = now()
WHERE nome_operacao = 'Central de Saude';

UPDATE public.tb_evento_saude_config
SET intervalo_atualizacao = 15,
    data_atualizacao = now()
WHERE intervalo_atualizacao = 30;

CREATE TABLE IF NOT EXISTS public.tb_evento_saude_historico
(
    id_historico             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento                integer                  NOT NULL
        REFERENCES public.tb_evento_corridas (id_evento)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    num_pedido               integer,
    num_peito                integer,
    id_usuario_atleta        integer,
    status_anterior          varchar(30),
    status_novo              varchar(30),
    tipo_acao                varchar(40)              NOT NULL DEFAULT 'status',
    descricao                text,
    origem                   varchar(30),
    id_usuario_operador      bigint,
    autor_nome               varchar(160),
    identificador_sessao     varchar(64),
    endereco_ip              inet,
    data_alteracao           timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.tb_evento_saude_historico
    ADD COLUMN IF NOT EXISTS tipo_acao varchar(40) NOT NULL DEFAULT 'status',
    ADD COLUMN IF NOT EXISTS descricao text,
    ADD COLUMN IF NOT EXISTS origem varchar(30),
    ADD COLUMN IF NOT EXISTS autor_nome varchar(160),
    ADD COLUMN IF NOT EXISTS identificador_sessao varchar(64);

ALTER TABLE public.tb_evento_saude_historico
    ALTER COLUMN num_peito DROP NOT NULL;

ALTER TABLE public.tb_evento_saude_historico
    DROP CONSTRAINT IF EXISTS tb_evento_saude_historico_id_evento_fkey;

ALTER TABLE public.tb_evento_saude_historico
    ADD CONSTRAINT tb_evento_saude_historico_id_evento_fkey
    FOREIGN KEY (id_evento)
    REFERENCES public.tb_evento_corridas (id_evento)
    ON UPDATE CASCADE ON DELETE RESTRICT;

UPDATE public.tb_evento_saude_historico
SET tipo_acao = CASE
        WHEN status_novo = 'scan' THEN 'acesso_ficha'
        WHEN status_novo = 'acionado' THEN 'acionar_equipe'
        WHEN status_novo = 'bib_desvinculado' THEN 'bib_desvinculado'
        ELSE 'status'
    END,
    origem = coalesce(origem, CASE WHEN id_usuario_operador IS NULL THEN 'perfil_publico' ELSE 'business_central' END),
    autor_nome = coalesce(autor_nome, CASE WHEN id_usuario_operador IS NULL THEN 'Acesso público' END)
WHERE tipo_acao = 'status'
  AND descricao IS NULL;

CREATE INDEX IF NOT EXISTS tb_evento_saude_historico_evento_data_idx
    ON public.tb_evento_saude_historico (id_evento, data_alteracao DESC);

CREATE INDEX IF NOT EXISTS tb_evento_saude_historico_atleta_idx
    ON public.tb_evento_saude_historico (id_evento, num_peito, data_alteracao DESC);

CREATE INDEX IF NOT EXISTS tb_evento_saude_historico_usuario_data_idx
    ON public.tb_evento_saude_historico (id_usuario_atleta, data_alteracao DESC);

CREATE INDEX IF NOT EXISTS tb_evento_saude_historico_inscricao_data_idx
    ON public.tb_evento_saude_historico (num_pedido, data_alteracao DESC)
    WHERE num_pedido IS NOT NULL;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tb_evento_saude_config TO runner;
GRANT SELECT, INSERT ON public.tb_evento_saude_historico TO runner;
GRANT USAGE, SELECT ON SEQUENCE public.tb_evento_saude_historico_id_historico_seq TO runner;

INSERT INTO public.tb_evento_saude_config
(
    id_evento,
    ativo,
    nome_operacao,
    percurso_padrao,
    intervalo_atualizacao
)
SELECT evt.id_evento,
       true,
       'Central de Saúde',
       COALESCE(
           (
               SELECT p.percurso_evento
               FROM public.tb_evento_corridas_percursos p
               WHERE p.id_evento = evt.id_evento
                 AND p.percurso_evento = 10
               LIMIT 1
           ),
           (
               SELECT min(p.percurso_evento)
               FROM public.tb_evento_corridas_percursos p
               WHERE p.id_evento = evt.id_evento
           )
       ),
       15
FROM public.tb_evento_corridas evt
WHERE evt.id_evento = 41703
ON CONFLICT (id_evento) DO NOTHING;

COMMIT;
