<section class="mb-3"><div class="ads-v1-eyebrow">Uso interno</div><h2 class="h5 mb-1">Administração financeira</h2><p class="text-muted mb-0">Crédito manual, movimentações e correções da conta.</p></section>

<div class="row g-4 mb-4">
  <div class="col-xl-4"><section class="card shadow-0 h-100"><div class="card-body p-3 p-lg-4"><h2 class="h5">Crédito manual</h2><p class="text-muted">Use apenas para ajustes administrativos.</p><form method="post" action="./?view=admin"><input type="hidden" name="ads_v1_action" value="credit_account"/><input type="hidden" name="ads_v1_csrf" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1Csrf)#</cfoutput>"/><input type="hidden" name="idempotency_key" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1CreditIdempotencyKey)#</cfoutput>"/><div class="mb-3"><label class="form-label" for="ads-v1-credit">Valor</label><input class="form-control" id="ads-v1-credit" type="number" name="amount" min="0.01" step="0.01" required/></div><div class="mb-3"><label class="form-label" for="ads-v1-credit-reason">Justificativa</label><textarea class="form-control" id="ads-v1-credit-reason" name="reason" minlength="5" maxlength="500" required></textarea></div><button class="btn btn-info w-100" type="submit">Registrar crédito</button></form></div></section></div>
  <div class="col-xl-8"><section class="card shadow-0 h-100"><div class="card-body p-3 p-lg-4"><h2 class="h5">Movimentações recentes</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Data</th><th>Tipo</th><th>Campanha</th><th class="text-end">Valor</th><th class="text-end">Saldo</th></tr></thead><tbody><cfif qAdsV1Ledger.recordcount><cfoutput query="qAdsV1Ledger"><tr><td><cfif isDate(occurred_at)>#lsDateFormat(occurred_at, "dd/mm/yyyy")# #lsTimeFormat(occurred_at, "HH:nn")#<cfelse>-</cfif></td><td>#htmlEditFormat(adsV1LedgerLabel(entry_type, source_type))#</td><td>#htmlEditFormat(campaign_name)#</td><td class="text-end">#lsCurrencyFormat(amount)#</td><td class="text-end">#lsCurrencyFormat(balance_after)#</td></tr></cfoutput><cfelse><tr><td colspan="5" class="text-muted text-center py-4">Nenhuma movimentação.</td></tr></cfif></tbody></table></div></div></section></div>
</div>

<cfif qAdsV1ReversibleDebits.recordcount>
  <section class="card shadow-0 mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5">Débitos elegíveis para estorno</h2><p class="text-muted">O estorno cria uma movimentação compensatória; nenhum registro é apagado.</p><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Data</th><th>Campanha</th><th>Débito</th><th>Motivo e ação</th></tr></thead><tbody><cfoutput query="qAdsV1ReversibleDebits"><tr><td><cfif isDate(occurred_at)>#lsDateFormat(occurred_at, "dd/mm/yyyy")# #lsTimeFormat(occurred_at, "HH:nn")#<cfelse>-</cfif></td><td>#htmlEditFormat(campaign_name)#</td><td>#lsCurrencyFormat(amount)#</td><td><form method="post" action="./?view=admin" class="d-flex flex-column flex-lg-row gap-2"><input type="hidden" name="ads_v1_action" value="reverse_click_debit"/><input type="hidden" name="ads_v1_csrf" value="#htmlEditFormat(VARIABLES.adsV1Csrf)#"/><input type="hidden" name="ledger_entry_id" value="#htmlEditFormat(ledger_entry_id)#"/><input type="hidden" name="idempotency_key" value="business:click-reversal:#htmlEditFormat(ledger_entry_id)#:#adsV1NewIdempotencyToken()#"/><input class="form-control form-control-sm" name="reason" minlength="5" maxlength="500" required placeholder="Motivo do estorno"/><button class="btn btn-sm btn-outline-info" type="submit">Estornar</button></form></td></tr></cfoutput></tbody></table></div></div></section>
</cfif>
