<section class="card shadow-0 mb-4" id="campaign-form">
  <div class="card-body p-3 p-lg-4">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><div class="ads-v1-eyebrow">Campanha</div><h2 class="h5 mb-1"><cfif len(VARIABLES.adsV1FormCampaignId)>Editar campanha<cfelse>Nova campanha</cfif></h2><p class="text-muted mb-0">Defina o evento, o investimento e onde a campanha aparecerá.</p></div><a class="btn btn-sm btn-outline-light" href="./?view=campaigns">Fechar formulário</a></div>

    <cfif NOT VARIABLES.adsV1CampaignEditable><div class="alert alert-warning mb-0">Somente rascunhos ou campanhas pausadas podem ser editados.</div>
    <cfelseif NOT qAdsV1Events.recordcount><div class="alert alert-warning mb-0">Esta conta nao possui eventos ativos vinculados.</div>
    <cfelseif NOT qAdsV1Placements.recordcount><div class="alert alert-warning mb-0">Nenhum local de exibição está disponível.</div>
    <cfelse>
      <form method="post" action="./?view=campaigns#campaign-form" class="row g-3">
        <input type="hidden" name="ads_v1_action" value="save_campaign"/><input type="hidden" name="ads_v1_csrf" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1Csrf)#</cfoutput>"/><input type="hidden" name="campaign_id" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormCampaignId)#</cfoutput>"/>
        <div class="col-lg-6"><label class="form-label" for="ads-v1-event">Evento</label><select class="form-select" id="ads-v1-event" name="core_event_id" required><option value="">Selecione</option><cfoutput query="qAdsV1Events"><option value="#id_evento#" <cfif val(id_evento) EQ VARIABLES.adsV1FormEventId>selected</cfif>>#htmlEditFormat(nome_evento)# - #htmlEditFormat(cidade)#/#htmlEditFormat(estado)#</option></cfoutput></select></div>
        <div class="col-lg-6"><label class="form-label" for="ads-v1-name">Nome da campanha</label><input class="form-control" id="ads-v1-name" name="name" minlength="3" maxlength="160" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormName)#</cfoutput>"/></div>
        <div class="col-sm-4"><label class="form-label" for="ads-v1-cpc">Custo por clique (CPC)</label><input class="form-control" id="ads-v1-cpc" type="number" name="cpc_bid" min="0.01" step="0.01" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormCpcRaw)#</cfoutput>"/></div>
        <div class="col-sm-4"><label class="form-label" for="ads-v1-total">Orçamento total</label><input class="form-control" id="ads-v1-total" type="number" name="budget_total" min="0.01" step="0.01" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormBudgetTotalRaw)#</cfoutput>"/></div>
        <div class="col-sm-4"><label class="form-label" for="ads-v1-daily">Limite diário</label><input class="form-control" id="ads-v1-daily" type="number" name="budget_daily" min="0.01" step="0.01" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormBudgetDailyRaw)#</cfoutput>" placeholder="Opcional"/></div>
        <div class="col-md-6"><label class="form-label" for="ads-v1-start">Início</label><input class="form-control" id="ads-v1-start" type="datetime-local" name="starts_at" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormStartsDisplay)#</cfoutput>"/></div>
        <div class="col-md-6"><label class="form-label" for="ads-v1-end">Fim</label><input class="form-control" id="ads-v1-end" type="datetime-local" name="ends_at" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormEndsDisplay)#</cfoutput>"/></div>
        <div class="col-md-4"><label class="form-label" for="ads-v1-device">Dispositivo</label><select class="form-select" id="ads-v1-device" name="target_device_class"><option value="ALL" <cfif VARIABLES.adsV1FormDevice EQ "ALL">selected</cfif>>Todos</option><option value="DESKTOP" <cfif VARIABLES.adsV1FormDevice EQ "DESKTOP">selected</cfif>>Desktop</option><option value="MOBILE" <cfif VARIABLES.adsV1FormDevice EQ "MOBILE">selected</cfif>>Mobile</option></select></div>
        <div class="col-md-4"><label class="form-label" for="ads-v1-country">País</label><input class="form-control" id="ads-v1-country" name="target_country_code" maxlength="2" required value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormCountry)#</cfoutput>"/></div>
        <div class="col-md-4"><label class="form-label" for="ads-v1-region">Região</label><input class="form-control" id="ads-v1-region" name="target_region_code" maxlength="40" value="<cfoutput>#htmlEditFormat(VARIABLES.adsV1FormRegion)#</cfoutput>" placeholder="Opcional, ex.: SC"/></div>
        <div class="col-12"><fieldset><legend class="form-label mb-2">Locais de exibição</legend><p class="small text-muted mb-2">Escolha onde o anúncio poderá aparecer no RoadRunners.</p><div class="row g-2"><cfoutput query="qAdsV1Placements"><div class="col-md-6 col-xl-4"><div class="form-check border rounded p-3 h-100"><input class="form-check-input ms-0 me-2" id="ads-v1-placement-#currentRow#" type="checkbox" name="placement_keys" value="#htmlEditFormat(placement_key)#" <cfif arrayFindNoCase(VARIABLES.adsV1FormPlacementKeys, placement_key)>checked</cfif>/><label class="form-check-label" for="ads-v1-placement-#currentRow#"><strong>#htmlEditFormat(adsV1PlacementLabel(placement_key))#</strong><span class="d-block small text-muted">#htmlEditFormat(adsV1PlacementDescription(placement_key))#</span></label></div></div></cfoutput></div></fieldset></div>
        <div class="col-12 d-flex justify-content-end"><button class="btn btn-info" type="submit">Salvar campanha</button></div>
      </form>
    </cfif>
  </div>
</section>
