const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('cupons-rr/assets/manager.js','utf8');
function fixture(){
  const windowEvents={},forms=[],confirmations=[];let confirmation=true,response={items:[{id:123,label:'Corrida <script>alert(1)</script>'}]},fails=false;
  const node=(props={})=>Object.assign({listeners:{},value:'',textContent:'',addEventListener(key,fn){this.listeners[key]=fn;},setAttribute(){},removeAttribute(){},focus(){},scrollIntoView(){}},props);
  const main=node(),link=node(),confirmForm=node({dataset:{cpConfirm:'Desativar?'}}),feedback=node(),search=node({value:'Corrida & edição'}),button=node(),status=node();
  const select=node({options:[{value:'55',textContent:'Evento anterior'}],value:'55',get selectedOptions(){return this.options.filter(o=>o.value===this.value);},replaceChildren(...options){this.options=options;this.value='';},add(option){this.options.push(option);}});
  const details={open:false},fields={'[name=id_evento]':select,'[name=inicio]':node(),'[name=fim]':node(),'[name=quantidade]':node()};
  main.querySelector=()=>feedback;link.querySelector=key=>fields[key]||feedback;link.closest=()=>details;forms.push(main,link);
  const picker={querySelector:key=>({'[data-cp-search]':search,'[data-cp-find]':button,'[data-cp-results]':select,'[data-cp-search-status]':status})[key]};
  const edit=node({dataset:{event:'123',label:'Corrida',start:'2026-09-16',end:'2026-12-31',quantity:'20'}});
  vm.runInNewContext(source,{document:{querySelectorAll:key=>({'[data-cp-form]':forms,'[data-cp-confirm]':[confirmForm],'[data-cp-picker]':[picker],'[data-cp-edit-link]':[edit],'[aria-busy]':[]})[key]||[],querySelector:()=>link},window:{addEventListener:(k,fn)=>windowEvents[k]=fn,confirm:text=>{confirmations.push(text);return confirmation;}},Option:function(label,value){this.textContent=label;this.value=value;},fetch:async url=>{fixture.lastUrl=url;if(fails)throw Error('offline');return {ok:true,json:async()=>response};}});
  return {main,link,confirmForm,feedback,search,button,status,select,fields,details,edit,confirmations,confirmation:value=>confirmation=value,response:value=>response=value,fail:()=>fails=true,emit(target,key){const event={key:'Enter',preventDefault(){this.prevented=true;}};(target.listeners||windowEvents)[key]?.(event);return event;},windowEvents};
}
test('protege rascunho ao navegar e ao salvar outro formulário',()=>{const f=fixture();f.emit(f.main,'input');assert.equal(f.emit({},'beforeunload').prevented,true);f.confirmation(false);assert.equal(f.emit(f.link,'submit').prevented,true);assert.match(f.confirmations[0],/outro formulário/);});
test('ações de desativação/desvinculação exigem confirmação',()=>{const f=fixture();f.confirmation(false);assert.equal(f.emit(f.confirmForm,'submit').prevented,true);});
test('duplo envio bloqueado e retorno do navegador reabilita',()=>{const f=fixture();assert.notEqual(f.emit(f.main,'submit').prevented,true);assert.equal(f.emit(f.main,'submit').prevented,true);f.windowEvents.pageshow();assert.notEqual(f.emit(f.main,'submit').prevented,true);});
test('busca codifica a consulta, trata nomes como texto e preserva seleção',async()=>{const f=fixture();await f.button.listeners.click();assert.match(fixture.lastUrl,/Corrida%20%26%20edi%C3%A7%C3%A3o/);assert.equal(f.select.value,'55');assert.equal(f.select.options[1].textContent,'Corrida <script>alert(1)</script>');assert.equal(f.button.disabled,false);});
test('falha de busca mantém evento e informa problema',async()=>{const f=fixture();f.fail();await f.button.listeners.click();assert.equal(f.select.value,'55');assert.match(f.status.textContent,/Não foi possível/);assert.equal(f.button.disabled,false);});
test('JSON inválido não apaga seleção anterior',async()=>{const f=fixture();f.response({});await f.button.listeners.click();assert.equal(f.select.value,'55');assert.match(f.status.textContent,/Não foi possível/);});
test('editar vínculo carrega evento, datas e limite',()=>{const f=fixture();f.edit.listeners.click();assert.equal(f.details.open,true);assert.equal(f.select.value,'123');assert.equal(f.fields['[name=inicio]'].value,'2026-09-16');assert.equal(f.fields['[name=quantidade]'].value,'20');});
test('recusar substituição preserva edição do vínculo',()=>{const f=fixture();f.emit(f.link,'input');f.confirmation(false);f.edit.listeners.click();assert.equal(f.select.value,'55');assert.equal(f.details.open,false);});
test('backend usa POST/CSRF, escopo de conta e não grava anúncios',()=>{const backend=fs.readFileSync('cupons-rr/includes/backend.cfm','utf8'),service=fs.readFileSync('cupons-rr/includes/CouponService.cfc','utf8');assert.match(backend,/CGI.request_method NEQ 'POST'/);assert.match(backend,/compare\(FORM.csrf/);assert.match(service,/FOR UPDATE OF c/);assert.match(service,/pg_advisory_xact_lock/);assert.doesNotMatch(backend+service,/ads\.tb_ad_eventos|incluir_campanha|status_campanha/);});
