<cfprocessingdirective pageencoding="utf-8"/>
<cfinclude template="../includes/event_interest_backend.cfm"/>
<style>
.event-interest{--ei-border:rgba(255,255,255,.14);max-width:1600px;margin:0 auto;padding:24px 0 48px;color:#e8ebef}
.event-interest .ei-muted{color:#b7bec8}.event-interest .ei-panel{padding:20px;background:#25282d;border:1px solid var(--ei-border);border-radius:16px;margin-bottom:18px}
.event-interest .ei-heading{display:flex;gap:18px;align-items:start;justify-content:space-between;flex-wrap:wrap}.event-interest h1{font-size:1.85rem;font-weight:750;margin:4px 0 8px}
.event-interest .ei-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.event-interest .ei-kpi{padding:20px;border:1px solid var(--ei-border);border-radius:15px;background:#25282d}.event-interest .ei-kpi:first-child{border-color:#947133}.event-interest .ei-value{display:block;font-size:2.15rem;font-weight:750;line-height:1.4;color:#fff}.event-interest .ei-kpi:first-child .ei-value{color:#ffc454}
.event-interest .ei-filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.event-interest label{display:block;font-size:.8rem;margin-bottom:5px;color:#c6ccd4}.event-interest input,.event-interest select{max-width:100%;background:#1f2227;color:#f0f2f6;border:1px solid #697382;border-radius:7px;padding:8px 10px;min-height:40px}.event-interest .ei-search{flex:1;min-width:190px}.event-interest .ei-search input{width:100%}
.event-interest .ei-tabs{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0 20px;padding-bottom:10px;border-bottom:1px solid var(--ei-border)}.event-interest .ei-tabs a{padding:10px 14px;color:#cbd1d9;border-radius:8px}.event-interest .ei-tabs a[aria-current=page]{color:#1c2025;background:#ffc454;font-weight:700}
.event-interest .ei-table{color:#e8ebef;font-size:.88rem;margin:0;width:100%;border-collapse:collapse}.event-interest .ei-table th{font-size:.75rem;color:#b7bec8;font-weight:600;text-transform:uppercase;letter-spacing:.04em}.event-interest .ei-table th,.event-interest .ei-table td{padding:13px 10px;border-bottom:1px solid var(--ei-border);vertical-align:top}.event-interest .ei-table th:first-child,.event-interest .ei-table td:first-child{padding-left:0}.event-interest .ei-table .ei-title{min-width:230px;max-width:440px;white-space:normal;overflow-wrap:anywhere}.event-interest .ei-table .ei-num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.event-interest .ei-scroll{overflow-x:auto}.event-interest .ei-table a{color:#aad0ff}.event-interest .ei-table strong{color:#f0f2f5}.event-interest .ei-pill{display:inline-block;padding:3px 7px;border-radius:5px;background:#353d49;color:#d6e2f1;font-size:.72rem;margin:3px 4px 0 0}.event-interest .ei-up{color:#82dfb3}.event-interest .ei-warn{color:#ffd17c}.event-interest .ei-note{font-size:.82rem;line-height:1.6}.event-interest .ei-columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.event-interest .ei-bar{display:inline-block;height:7px;border-radius:5px;background:#e8ae45;vertical-align:middle;max-width:100%}.event-interest .ei-pagination{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:16px;flex-wrap:wrap}.event-interest details summary{cursor:pointer;color:#d2dae5}.event-interest a:focus-visible,.event-interest button:focus-visible{outline:3px solid #ffc454;outline-offset:3px}
@media(max-width:767px){.event-interest{padding-top:12px}.event-interest .ei-kpis{grid-template-columns:1fr 1fr;gap:10px}.event-interest .ei-kpi{padding:14px}.event-interest .ei-value{font-size:1.7rem}.event-interest .ei-panel{padding:15px}.event-interest .ei-columns{grid-template-columns:1fr}.event-interest .ei-tabs a{font-size:.85rem;padding:8px 10px}.event-interest h1{font-size:1.5rem}.event-interest .ei-table .ei-title{min-width:210px}}
</style>
<cfoutput>
<section class="event-interest" aria-labelledby="ei-title">
  <div class="ei-heading"><div><div class="small ei-muted">INTELIGÊNCIA DO PORTAL · ROAD RUNNERS</div><h1 id="ei-title">Quais provas estão despertando interesse?</h1><p class="ei-muted mb-2">Acessos medidos, interesse em agenda e prioridades para melhorar os cadastros.</p></div><a class="btn btn-sm btn-outline-light" href="/portal/audiencia/">Audiência do site</a></div>
  <form method="get" class="ei-panel ei-filters mt-3">
    <div><label for="ei-days">Acessos no período</label><select name="dias" id="ei-days"><cfloop list="#listFind('alta,agenda',VARIABLES.eiFilters.aba) ? '7,30' : '1,7,30,90'#" index="eiOption"><option value="#eiOption#" <cfif VARIABLES.eiFilters.dias EQ eiOption>selected</cfif>><cfif eiOption EQ "1">Hoje<cfelse>#eiOption# dias</cfif></option></cfloop></select></div>
    <div><label for="ei-uf">UF da prova</label><select id="ei-uf" name="uf"><option value="">Todas</option><cfloop list="#VARIABLES.eiUfs#" index="eiOption"><option <cfif VARIABLES.eiFilters.uf EQ eiOption>selected</cfif>>#eiOption#</option></cfloop></select></div>
    <cfif VARIABLES.eiFilters.aba NEQ 'agenda'><div><label for="ei-stage">Data da prova</label><select name="fase" id="ei-stage"><option value="all" <cfif VARIABLES.eiFilters.fase EQ 'all'>selected</cfif>>Todas</option><option value="future" <cfif VARIABLES.eiFilters.fase EQ 'future'>selected</cfif>>Hoje e futuras</option><option value="past" <cfif VARIABLES.eiFilters.fase EQ 'past'>selected</cfif>>Já realizadas</option></select></div><cfelse><input type="hidden" name="fase" value="future"></cfif>
    <div class="ei-search"><label for="ei-search">Prova, cidade ou ID</label><input id="ei-search" name="termo" maxlength="120" value="#encodeForHTMLAttribute(VARIABLES.eiFilters.termo)#" placeholder="Buscar uma prova"></div>
    <div><label for="ei-internal">Tráfego</label><select name="internos" id="ei-internal"><option value="0" <cfif VARIABLES.eiFilters.internos EQ '0'>selected</cfif>>Público</option><option value="1" <cfif VARIABLES.eiFilters.internos EQ '1'>selected</cfif>>Público + interno</option></select></div>
    <input type="hidden" name="aba" value="#VARIABLES.eiFilters.aba#"><cfif len(VARIABLES.eiFilters.evento_id)><input type="hidden" name="evento_id" value="#encodeForHTMLAttribute(VARIABLES.eiFilters.evento_id)#"></cfif>
    <button class="btn btn-warning" type="submit">Aplicar</button>
  </form>
  <nav class="ei-tabs" aria-label="Visões de interesse"><cfloop array="#[{key='ranking',label='Mais acessadas'},{key='alta',label='Em alta'},{key='agenda',label='Agenda'},{key='cadastro',label='Melhorar cadastros'},{key='origem',label='Origem'},{key='publico',label='Público e navegação'},{key='metodo',label='Como interpretar'}]#" index="eiTab"><a href="#encodeForHTMLAttribute(eventInterestUrl({aba=eiTab.key,p=1}))#" <cfif VARIABLES.eiFilters.aba EQ eiTab.key>aria-current="page"</cfif>>#eiTab.label#</a></cfloop></nav>
  <cfif NOT VARIABLES.eiReady>
    <cfif VARIABLES.eiFilters.aba EQ 'agenda'><div class="ei-panel" role="status"><h2 class="h5">Agenda indisponível</h2><p class="ei-muted mb-0">Não foi possível consultar as provas salvas agora. Isso não significa que a agenda está vazia. Tente atualizar a página ou consulte outra aba.</p></div><cfelse>
    <div class="ei-panel" role="status"><h2 class="h5">Leitura de audiência indisponível</h2><p class="ei-muted mb-0">Não foi possível consultar a nova medição agora. Isso não significa zero acessos. Tente atualizar a página.</p></div>
    </cfif>
  <cfelse>
    <cfset ei=VARIABLES.eiReport>
    <cfif VARIABLES.eiFilters.aba EQ 'agenda'>
      <cfinclude template="agenda.cfm">
    <cfelse>
    <div class="ei-note ei-muted">#encodeForHTML(ei.meta.since)# até #encodeForHTML(ei.meta.until)# · Brasília · Hoje é parcial · Último recebimento: #encodeForHTML(ei.meta.last_received)# · Atualização em até 1 minuto.</div>
    <cfif len(VARIABLES.eiFilters.evento_id)><div class="ei-panel mt-3 mb-2">Detalhe da prova ###encodeForHTML(VARIABLES.eiFilters.evento_id)# <a class="ms-3" href="#encodeForHTMLAttribute(eventInterestUrl({evento_id='',p=1}))#">Voltar a todas as provas</a></div></cfif>
    <div class="ei-kpis">
      <div class="ei-kpi"><span class="ei-muted">Aberturas de provas</span><strong class="ei-value" data-metric="pageviews">#eventInterestNumber(ei.summary.pageviews)#</strong><small class="ei-muted">Aberturas medidas, sem amostra</small></div>
      <div class="ei-kpi"><span class="ei-muted">Visitantes estimados</span><strong class="ei-value">#eventInterestNumber(ei.summary.visitors)#</strong><small class="ei-muted">#eventInterestNumber(ei.summary.sessions)# sessões · navegadores, não pessoas</small></div>
      <div class="ei-kpi"><span class="ei-muted">Provas acessadas</span><strong class="ei-value">#eventInterestNumber(ei.summary.events)#</strong><small class="ei-muted">#eventInterestNumber(ei.summary.gaps)# com campos para revisar</small></div>
      <div class="ei-kpi"><span class="ei-muted">Futuras em destaque</span><strong class="ei-value" data-metric="highlights">#eventInterestNumber(ei.summary.hot)#</strong><small class="ei-muted">Últimos #ei.meta.trend_days# dias · 3+ visitantes</small></div>
    </div>
    <cfif listFind('ranking,alta,cadastro',VARIABLES.eiFilters.aba)>
      <cfset eiRows=ei.ranking>
      <cfif VARIABLES.eiFilters.aba EQ 'alta'><cfset eiRows=ei.hot><cfelseif VARIABLES.eiFilters.aba EQ 'cadastro'><cfset eiRows=ei.gaps></cfif>
      <div class="ei-panel">
        <cfif VARIABLES.eiFilters.aba EQ 'alta'>
          <h2 class="h5">Provas em destaque nos últimos #ei.meta.trend_days# dias</h2><p class="ei-note ei-muted">Provas ativas, de hoje ou futuras, com pelo menos 3 visitantes distintos. Ordem: mais visitantes, depois aberturas. Até 20 provas; não é necessário estar crescendo para aparecer. Agenda ao lado mostra o saldo atual.</p>
          <p class="ei-note ei-muted">Período: #encodeForHTML(ei.meta.recent)# · Brasília. Escolha 7 ou 30 dias no filtro acima.</p>
          <cfif NOT ei.meta.comparison_ready><p class="ei-warn">Histórico ainda parcial: mostramos os destaques observados, sem percentual de crescimento. Os dias sem coleta não representam zero procura.</p><cfelse><p class="ei-note ei-muted">Comparação: #encodeForHTML(ei.meta.previous)#. Hoje e o último dia da base anterior são considerados até o mesmo horário. Variações sobre bases pequenas são apenas sinais exploratórios.</p></cfif>
        <cfelseif VARIABLES.eiFilters.aba EQ 'cadastro'>
          <h2 class="h5">Demanda observada, informação faltando</h2><p class="ei-note ei-muted">Até 20 prioridades: futuras primeiro, depois mais aberturas. Os campos são verificados no cadastro atual; a ausência indica revisão, não erro confirmado. Links e imagens herdados podem já aparecer no portal.</p>
        <cfelse><h2 class="h5">Mais acessadas no período</h2><p class="ei-note ei-muted">Compare volume de acessos com atletas que mantêm a prova na agenda. Agenda é o saldo atual compartilhado entre os portais, não inclusões deste período nem conversão desses visitantes.</p></cfif>
        <cfif NOT VARIABLES.eiAgendaReady><p class="ei-warn">Agenda indisponível no momento. Os acessos continuam disponíveis.</p></cfif>
        <cfif arrayLen(eiRows)>
        <div class="ei-scroll" tabindex="0" aria-label="Tabela de provas; role horizontalmente em telas pequenas"><table class="ei-table"><thead><tr><th>Prova</th><th class="ei-num">Aberturas</th><th class="ei-num">Visitantes</th><th>Interesse · #ei.meta.trend_days# dias</th><th>Agenda atual</th><cfif VARIABLES.eiFilters.aba EQ 'cadastro'><th>Revisar</th></cfif></tr></thead><tbody>
        <cfloop array="#eiRows#" index="eiRow"><tr>
          <td class="ei-title"><a href="#encodeForHTMLAttribute(eventInterestUrl({evento_id=eiRow.content_id,p=1,aba='ranking'}))#"><strong>#encodeForHTML(eiRow.event_name)#</strong></a><div class="ei-note ei-muted">#encodeForHTML(eiRow.city)#<cfif len(eiRow.uf)> / #encodeForHTML(eiRow.uf)#</cfif> · #encodeForHTML(eiRow.event_date)#</div><div><span class="ei-pill"><cfif eiRow.catalog_missing>Sem cadastro<cfelseif eiRow.upcoming>Hoje ou futura<cfelse>Já realizada</cfif></span><cfif NOT eiRow.active AND NOT eiRow.catalog_missing><span class="ei-pill">Inativa</span></cfif><cfif arrayLen(eiRow.missing_fields) AND VARIABLES.eiFilters.aba NEQ 'cadastro'><span class="ei-pill">#arrayLen(eiRow.missing_fields)# campos para revisar</span></cfif></div></td>
          <td class="ei-num"><strong>#eventInterestNumber(eiRow.pageviews)#</strong><div class="ei-note ei-muted">#eventInterestNumber(eiRow.sessions)# sessões</div></td><td class="ei-num">#eventInterestNumber(eiRow.visitors)#</td>
          <td><cfif NOT ei.meta.comparison_ready><span class="ei-muted"><cfif VARIABLES.eiFilters.aba EQ 'alta'>Destaque no período<cfelse>Sem base comparável</cfif></span><div class="ei-note ei-muted">#eventInterestNumber(eiRow.recent_visitors)# visitantes · #ei.meta.trend_days# dias</div>
          <cfelse><cfif structKeyExists(eiRow,'growth_pct') AND isNumeric(eiRow.growth_pct)><strong class="<cfif eiRow.growth_pct GT 0>ei-up</cfif>"><cfif eiRow.growth_pct GT 0>+</cfif>#replace(numberFormat(eiRow.growth_pct,'0.0'),'.',',')#%</strong><cfelseif eiRow.recent_visitors GT 0><span class="ei-up">Novo interesse</span><cfelse><span class="ei-muted">Sem interesse recente</span></cfif><div class="ei-note ei-muted">#eventInterestNumber(eiRow.recent_visitors)# vs. #eventInterestNumber(eiRow.previous_visitors)# visitantes</div><cfif eiRow.previous_visitors GT 0 AND eiRow.previous_visitors LT 3><div class="ei-note ei-muted">Base anterior pequena</div></cfif></cfif></td>
          <td style="min-width:180px"><span class="ei-note">#encodeForHTML(eventInterestAgenda(eiRow.content_id))#</span></td>
          <cfif VARIABLES.eiFilters.aba EQ 'cadastro'><td style="min-width:190px"><div class="ei-note ei-warn">#encodeForHTML(arrayToList(eiRow.missing_fields,', '))#</div><cfif NOT eiRow.catalog_missing><a class="ei-note" href="/admin/?periodo=#eiRow.event_year#&amp;id_evento=#encodeForURL(eiRow.content_id)#">Revisar cadastro →</a></cfif></td></cfif>
        </tr></cfloop></tbody></table></div>
        <cfelse><p class="ei-muted mb-0">Nenhuma prova encontrada para esta visão e estes filtros.</p></cfif>
        <cfif VARIABLES.eiFilters.aba EQ 'ranking'><div class="ei-pagination ei-note"><span class="ei-muted">#eventInterestNumber(ei.summary.events)# provas · até 50 por página · página #VARIABLES.eiFilters.p#</span><div><cfif val(VARIABLES.eiFilters.p) GT 1><a class="btn btn-sm btn-outline-light me-2" href="#encodeForHTMLAttribute(eventInterestUrl({p=val(VARIABLES.eiFilters.p)-1}))#">Anterior</a></cfif><cfif val(VARIABLES.eiFilters.p)*50 LT ei.summary.events><a class="btn btn-sm btn-outline-light" href="#encodeForHTMLAttribute(eventInterestUrl({p=val(VARIABLES.eiFilters.p)+1}))#">Próxima</a></cfif></div></div></cfif>
      </div>
      <cfif VARIABLES.eiFilters.aba EQ 'ranking'><details class="ei-panel"><summary>Aberturas por dia</summary><div class="ei-scroll mt-3"><table class="ei-table"><thead><tr><th>Dia</th><th class="ei-num">Aberturas</th><th>Volume</th></tr></thead><tbody><cfset eiMax=1><cfloop array="#ei.daily#" index="eiRow"><cfset eiMax=max(eiMax,eiRow.pageviews)></cfloop><cfloop array="#ei.daily#" index="eiRow"><tr><td>#encodeForHTML(eiRow.day)#</td><td class="ei-num">#eventInterestNumber(eiRow.pageviews)#</td><td style="width:60%"><span class="ei-bar" style="width:#round(100*eiRow.pageviews/eiMax)#%" aria-hidden="true"></span></td></tr></cfloop></tbody></table></div></details></cfif>
    <cfelseif VARIABLES.eiFilters.aba EQ 'origem'>
      <div class="ei-panel"><h2 class="h5">De onde vem o interesse nas provas?</h2><p class="ei-note ei-muted">Origem atribuída às aberturas de páginas de evento deste recorte. Até 30 combinações, ordenadas por aberturas. Visitantes e sessões podem aparecer em mais de uma combinação.</p>
      <cfif arrayLen(ei.sources)><div class="ei-scroll"><table class="ei-table"><thead><tr><th>Origem / meio</th><th>Campanha</th><th class="ei-num">Aberturas</th><th class="ei-num">Visitantes</th><th class="ei-num">Sessões</th></tr></thead><tbody><cfloop array="#ei.sources#" index="eiRow"><tr><td><strong>#encodeForHTML(eiRow.source)#</strong><div class="ei-note ei-muted">#encodeForHTML(eiRow.medium)#</div></td><td class="ei-title">#encodeForHTML(eiRow.campaign)#</td><td class="ei-num">#eventInterestNumber(eiRow.pageviews)#</td><td class="ei-num">#eventInterestNumber(eiRow.visitors)#</td><td class="ei-num">#eventInterestNumber(eiRow.sessions)#</td></tr></cfloop></tbody></table></div><cfelse><p class="ei-muted">Nenhuma origem medida neste recorte.</p></cfif></div>
    <cfelseif VARIABLES.eiFilters.aba EQ 'publico'>
      <div class="ei-columns">
        <div class="ei-panel"><h2 class="h5">UF aproximada do acesso</h2>
          <p class="ei-note ei-muted">Localização de quem acessou, não a UF da prova. Percentuais sobre as #eventInterestNumber(ei.summary.pageviews)# aberturas do recorte, incluindo as sem UF.</p>
          <div class="ei-scroll"><table class="ei-table" id="ei-regions"><thead><tr><th>UF</th><th class="ei-num">Aberturas · % do total</th></tr></thead><tbody>
          <cfloop array="#ei.regions#" index="eiRow"><tr><td>#encodeForHTML(eiRow.uf)#</td><td class="ei-num">#eventInterestNumber(eiRow.pageviews)# <strong>(#eventInterestPercent(eiRow.pageviews,ei.summary.pageviews)#)</strong></td></tr></cfloop>
          <cfif NOT arrayLen(ei.regions)><tr><td colspan="2" class="ei-muted">Nenhuma abertura neste recorte.</td></tr></cfif>
          </tbody></table></div>
          <cfif arrayLen(ei.regions)><p class="ei-note ei-muted mt-3 mb-0">“Não identificada” significa que o registro chegou sem uma UF válida. Os registros antigos sem UF não são preenchidos com o estado da prova.</p></cfif>
        </div>
        <div class="ei-panel"><h2 class="h5">Faixa de tela</h2>
          <p class="ei-note ei-muted">Largura da janela, não identificação do aparelho. Percentuais sobre as #eventInterestNumber(ei.summary.pageviews)# aberturas do recorte.</p>
          <div class="ei-scroll"><table class="ei-table" id="ei-devices"><thead><tr><th>Faixa</th><th class="ei-num">Aberturas · % do total</th></tr></thead><tbody>
          <cfloop array="#ei.devices#" index="eiRow"><tr><td>#encodeForHTML(eiRow.device)#</td><td class="ei-num">#eventInterestNumber(eiRow.pageviews)# <strong>(#eventInterestPercent(eiRow.pageviews,ei.summary.pageviews)#)</strong></td></tr></cfloop>
          <cfif NOT arrayLen(ei.devices)><tr><td colspan="2" class="ei-muted">Nenhuma abertura neste recorte.</td></tr></cfif>
          </tbody></table></div>
        </div>
      </div>
      <div class="ei-panel"><h2 class="h5">Provas exploradas na mesma sessão</h2>
        <p class="ei-note ei-muted">Até 20 sequências de aberturas de eventos, ordenadas no tempo. Não são cliques diretos: abas paralelas e páginas intermediárias podem existir. Os filtros se aplicam à prova de destino.</p>
        <p class="ei-note ei-muted">Base dos percentuais: #eventInterestNumber(ei.summary.flow_transitions)# sequências no total, antes do limite de 20 linhas; e #eventInterestNumber(ei.summary.sessions)# sessões do recorte. Uma sessão pode aparecer em várias sequências; seus percentuais não devem ser somados.</p>
        <cfif arrayLen(ei.flows)><div class="ei-scroll" tabindex="0" aria-label="Sequências entre provas; role horizontalmente em telas pequenas"><table class="ei-table" id="ei-flows"><thead><tr><th>Anterior</th><th>Seguinte</th><th class="ei-num">Sequências · %</th><th class="ei-num">Sessões · %</th></tr></thead><tbody>
        <cfloop array="#ei.flows#" index="eiRow"><tr><td class="ei-title">#encodeForHTML(eiRow.from_event)#</td><td class="ei-title">#encodeForHTML(eiRow.to_event)#</td><td class="ei-num">#eventInterestNumber(eiRow.transitions)# <strong>(#eventInterestPercent(eiRow.transitions,ei.summary.flow_transitions)#)</strong></td><td class="ei-num">#eventInterestNumber(eiRow.sessions)# <strong>(#eventInterestPercent(eiRow.sessions,ei.summary.sessions)#)</strong></td></tr></cfloop>
        </tbody></table></div><cfelse><p class="ei-muted">Sem sequências entre provas neste recorte.</p></cfif>
      </div>
    <cfelse>
      <div class="ei-panel"><h2 class="h5">Sinais para priorizar, não uma previsão de vendas</h2>
<ul class="ei-note"><li><strong>Aberturas:</strong> páginas de evento medidas no navegador, uma por identificador de abertura. Recarregamentos contam; interações não geram uma segunda abertura. Somente Road Runners em produção, com internos excluídos por padrão.</li><li><strong>Visitantes estimados:</strong> identificadores de navegador. Não são pessoas únicas; recusa, bloqueadores e troca de navegador podem reduzir a cobertura ou fragmentar identidades. Não há garantia de eliminação de todos os bots.</li><li><strong>Em alta:</strong> destaques de provas ativas de hoje ou futuras com pelo menos 3 visitantes distintos nos últimos 7 ou 30 dias, ordenados por visitantes e depois aberturas. Crescimento não é requisito. Hoje usa 7 dias; o filtro de 90 dias usa 30 dias para interesse. Na aba Em alta, o período fica em 7 ou 30 dias. A comparação com o período anterior termina no mesmo horário de Brasília; exige registro anterior à base e sinais diários do site nas duas janelas. Presença diária não certifica coleta sem interrupções. Sem histórico, exibimos o volume observado sem variação; base anterior zero vira “Novo interesse”, sem percentual. Bases pequenas são exploratórias, não previsão de inscrições.</li><li><strong>Agenda atual:</strong> atletas distintos por prova, unificando os registros de agenda e interesse sem fornecedores. Cada atleta conta uma vez por prova, mesmo com os dois tipos de registro. O botão Salvar também usa o tipo interno de inscrição; por isso não separamos esses registros como inscrições confirmadas. É um saldo do ecossistema, não necessariamente originado no Road Runners, nem venda ou pagamento. Remoções não têm histórico recuperável nesta fonte; não calculamos conversão nem inclusões por período. A aba Agenda lista provas ativas, não canceladas e ainda não encerradas, mesmo sem acessos medidos; ordena pelo saldo de atletas, depois data e ID. Os filtros de período e tráfego afetam apenas as colunas de acessos.</li><li><strong>Cadastros:</strong> revisão de localização, descrição, imagem, percursos e link de inscrição para provas não encerradas. São campos do cadastro base; complementos herdados podem preencher a apresentação pública. A ausência do cadastro não descarta acessos medidos.</li><li><strong>Histórico:</strong> somente a nova audiência. Não mistura logs antigos de requisições, OR ou MIF. Coleta iniciada em 08/09/2026, com implantação progressiva; períodos anteriores ou parcialmente cobertos não representam zero demanda. Eventos detalhados sujeitos à retenção de 90 dias. Primeiro registro disponível na janela lida: #encodeForHTML(ei.meta.first_observed)#.</li><li><strong>Totais:</strong> calculados antes da paginação. Distintos por prova ou origem não devem ser somados para obter visitantes e sessões do topo.</li></ul>
      </div>
    </cfif>
    </cfif>
  </cfif>
</section>
</cfoutput>
