<cfscript>
VARIABLES.sgStatusLabels={active="Ativo",draft="Rascunho",paused="Pausado",archived="Arquivado"};
function sgAudienceLabel(required struct policy) {
    if (structKeyExists(arguments.policy,"audience") && arguments.policy.audience EQ "open") return "Sem pré-requisitos";
    if (!structKeyExists(arguments.policy,"criteria") || !arrayLen(arguments.policy.criteria)) return "Regras de participação";
    if (arrayLen(arguments.policy.criteria)>1) return "Regras combinadas";
    var c=arguments.policy.criteria[1];
    if (c.type EQ "challenge") return "Inscritos em desafio/circuito";
    if (c.type EQ "event_registration") return structKeyExists(c,"training_only") && specialGroupsBoolean(c.training_only) ? "Inscritos em treino" : "Inscritos em evento";
    if (c.type EQ "circuit_registration") return "Inscritos nas etapas do circuito";
    if (c.type EQ "global_admin") return "Admins globais · regra anterior";
    return "Regra personalizada";
}
</cfscript>
<link rel="stylesheet" href="/administracao/chat/grupos-especiais/assets/manager.css?v=20261002"/>
<section class="communities py-4 py-lg-5">
  <header class="cm-hero mb-4">
    <span class="cm-hero-icon"><i class="fa-solid fa-comments"></i></span>
    <div class="flex-grow-1"><div class="cm-eyebrow">Administração · Comunicação</div><h1>Grupos e canais</h1><p>Comunidades do Road Runners, com público e entrada sob seu controle.</p></div>
    <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-light btn-sm" href="/administracao/chat/">Uso do chat</a><a class="btn btn-warning btn-sm" href="./#configuracao"><i class="fa-solid fa-plus me-2"></i>Nova comunidade</a></div>
  </header>
  <cfif len(VARIABLES.specialGroupsFeedback)><cfoutput><div class="alert alert-#VARIABLES.specialGroupsFeedbackType#" role="status">#encodeForHtml(VARIABLES.specialGroupsFeedback)#</div></cfoutput></cfif>
  <cfif NOT VARIABLES.specialGroupsReady><div class="alert alert-warning">Gerenciador indisponível. <cfoutput>#encodeForHtml(structKeyExists(VARIABLES.specialGroupsData,'message') ? VARIABLES.specialGroupsData.message : 'Confira a integração com o Road Runners.')#</cfoutput></div></cfif>
  <div class="cm-stats mb-4"><cfoutput>
    <div><i class="fa-solid fa-user-group"></i><strong>#VARIABLES.specialGroupsStats.groups#</strong><span>Grupos de conversa</span></div>
    <div><i class="fa-solid fa-bullhorn"></i><strong>#VARIABLES.specialGroupsStats.channels#</strong><span>Canais de publicação</span></div>
    <div><i class="fa-solid fa-circle-check"></i><strong>#VARIABLES.specialGroupsStats.active#</strong><span>Comunidades ativas</span></div>
    <div><i class="fa-solid fa-users"></i><strong>#numberFormat(VARIABLES.specialGroupsStats.members,'_,___')#</strong><span>Vínculos de participantes</span></div>
  </cfoutput></div>
  <section class="cm-card mb-4" aria-labelledby="cm-list-title">
    <div class="cm-section-head"><div><h2 id="cm-list-title">Comunidades configuradas</h2><p>Admins globais têm acesso e gerenciamento em todas as comunidades.</p></div><span class="cm-pill" id="communityCount"><cfoutput>#arrayLen(VARIABLES.specialGroups)#</cfoutput> comunidades</span></div>
    <div class="cm-filters"><label class="cm-search"><span class="visually-hidden">Buscar comunidade</span><i class="fa-solid fa-magnifying-glass"></i><input class="form-control" id="communitySearch" type="search" placeholder="Nome, evento ou público"/></label><select class="form-select" id="communityModeFilter" aria-label="Filtrar por tipo"><option value="">Todos os tipos</option><option value="chat">Grupos</option><option value="channel">Canais</option></select><select class="form-select" id="communityStatusFilter" aria-label="Filtrar por situação"><option value="">Todas as situações</option><option value="active">Ativos</option><option value="draft">Rascunhos</option><option value="paused">Pausados</option><option value="archived">Arquivados</option></select></div>
    <div class="table-responsive"><table class="table align-middle cm-table"><thead><tr><th>Comunidade</th><th>Público e entrada</th><th>Situação</th><th class="text-end">Participantes</th><th class="text-end">Ações</th></tr></thead><tbody>
    <cfloop array="#VARIABLES.specialGroups#" item="VARIABLES.groupItem">
      <cfset VARIABLES.sgMode=structKeyExists(VARIABLES.groupItem,'modo') ? VARIABLES.groupItem.modo : 'chat'/>
      <cfset VARIABLES.sgAudience=sgAudienceLabel(VARIABLES.groupItem.regra)/>
      <cfoutput><tr data-community-row data-name="#encodeForHtmlAttribute(VARIABLES.groupItem.nome & ' ' & VARIABLES.sgAudience & ' ' & (structKeyExists(VARIABLES.groupItem,'official_event_name') ? VARIABLES.groupItem.official_event_name : ''))#" data-mode="#VARIABLES.sgMode#" data-status="#encodeForHtmlAttribute(VARIABLES.groupItem.status)#">
        <td><div class="cm-name"><span class="cm-type-icon"><i class="fa-solid #VARIABLES.sgMode EQ 'channel' ? 'fa-bullhorn' : 'fa-user-group'#"></i></span><div><strong>#encodeForHtml(VARIABLES.groupItem.nome)#</strong><small>#VARIABLES.sgMode EQ 'channel' ? 'Canal' : 'Grupo'#<cfif structKeyExists(VARIABLES.groupItem,'official_event_name') AND len(VARIABLES.groupItem.official_event_name)> · <span class="text-warning">Oficial</span> · #encodeForHtml(VARIABLES.groupItem.official_event_name)#</cfif></small></div></div></td>
        <td>#encodeForHtml(VARIABLES.sgAudience)#<small class="cm-muted d-block">#specialGroupsBoolean(VARIABLES.groupItem.associacao_automatica) ? 'Inclusão automática' : 'Entrada voluntária / inclusão pelo admin'#</small></td>
        <td><span class="cm-pill cm-status-#encodeForHtmlAttribute(VARIABLES.groupItem.status)#">#encodeForHtml(VARIABLES.sgStatusLabels[VARIABLES.groupItem.status])#</span></td><td class="text-end fw-semibold">#numberFormat(val(VARIABLES.groupItem.member_count),'_,___')#</td>
        <td><div class="cm-actions"><a class="btn btn-sm btn-outline-light" href="?editar=#val(VARIABLES.groupItem.id_chat_grupo)###configuracao" title="Configurar" aria-label="Configurar #encodeForHtmlAttribute(VARIABLES.groupItem.nome)#"><i class="fa-solid fa-sliders"></i></a><a class="btn btn-sm btn-outline-light" href="https://roadrunners.run/mensagens/#VARIABLES.sgMode EQ 'channel' ? 'canais' : 'grupos'#/?grupo=#val(VARIABLES.groupItem.id_chat_grupo)#" target="_blank" rel="noopener" title="Abrir no Road Runners" aria-label="Abrir no Road Runners"><i class="fa-solid fa-arrow-up-right-from-square"></i></a>
          <form method="post" data-confirm="Sincronizar os participantes conforme o público e a configuração de inclusão desta comunidade?"><input type="hidden" name="special_groups_csrf" value="#VARIABLES.specialGroupsCsrf#"/><input type="hidden" name="manager_request_id" value="#lCase(hash(createUUID(),'SHA-256'))#"/><input type="hidden" name="manager_action" value="sync"/><input type="hidden" name="group_id" value="#val(VARIABLES.groupItem.id_chat_grupo)#"/><button class="btn btn-sm btn-outline-info" title="Sincronizar participantes" aria-label="Sincronizar participantes" <cfif VARIABLES.groupItem.status NEQ 'active' OR val(VARIABLES.groupItem.id_chat_grupo_especial) LTE 0>disabled</cfif>><i class="fa-solid fa-arrows-rotate"></i></button></form>
          <form method="post"><input type="hidden" name="special_groups_csrf" value="#VARIABLES.specialGroupsCsrf#"/><input type="hidden" name="manager_request_id" value="#lCase(hash(createUUID(),'SHA-256'))#"/><input type="hidden" name="manager_action" value="status"/><input type="hidden" name="group_id" value="#val(VARIABLES.groupItem.id_chat_grupo)#"/><input type="hidden" name="group_status" value="#VARIABLES.groupItem.status EQ 'active' ? 'paused' : 'active'#"/><button class="btn btn-sm btn-outline-warning" title="#VARIABLES.groupItem.status EQ 'active' ? 'Pausar' : 'Ativar'#" aria-label="#VARIABLES.groupItem.status EQ 'active' ? 'Pausar' : 'Ativar'#"><i class="fa-solid #VARIABLES.groupItem.status EQ 'active' ? 'fa-pause' : 'fa-play'#"></i></button></form>
        </div></td>
      </tr></cfoutput>
    </cfloop>
    <tr id="communityEmpty" <cfif arrayLen(VARIABLES.specialGroups)>hidden</cfif>><td colspan="5" class="text-center cm-muted py-4">Nenhuma comunidade nesta seleção.</td></tr>
    </tbody></table></div>
  </section>
  <div class="cm-editor" id="configuracao">
    <section class="cm-card"><div class="cm-section-head"><div><h2><cfif VARIABLES.specialGroupsEditing>Configurar comunidade<cfelse>Nova comunidade</cfif></h2><p>Escolha o formato, o público e como incluir os participantes.</p></div><cfif VARIABLES.specialGroupsEditing><a class="btn btn-sm btn-outline-light" href="./">Cancelar edição</a></cfif></div>
      <form method="post" id="communityForm">
        <cfoutput><input type="hidden" name="special_groups_csrf" value="#VARIABLES.specialGroupsCsrf#"/><input type="hidden" name="manager_request_id" value="#lCase(hash(createUUID(),'SHA-256'))#"/><input type="hidden" name="manager_action" id="managerAction" value="#VARIABLES.specialGroupsEditing ? 'update' : 'create'#"/><input type="hidden" name="group_id" value="#val(VARIABLES.specialGroupsForm.id_chat_grupo)#"/><input type="hidden" name="owner_id" value="#val(VARIABLES.specialGroupsForm.id_dono)#"/><input type="hidden" name="group_code" value="#encodeForHtmlAttribute(VARIABLES.specialGroupsForm.codigo)#"/><input type="hidden" name="policy_json" id="policyJson"/></cfoutput>
        <fieldset class="cm-step"><legend><span>1</span> Identificação e formato</legend>
          <div class="cm-type-options"><label><input type="radio" name="group_mode" value="chat" <cfif VARIABLES.specialGroupsForm.modo NEQ 'channel'>checked</cfif>/><span><i class="fa-solid fa-user-group"></i><strong>Grupo</strong><small>Participantes conversam entre si</small></span></label><label><input type="radio" name="group_mode" value="channel" <cfif VARIABLES.specialGroupsForm.modo EQ 'channel'>checked</cfif>/><span><i class="fa-solid fa-bullhorn"></i><strong>Canal</strong><small>Publicações dos responsáveis, sem respostas</small></span></label></div>
          <label class="cm-field">Nome da comunidade<input class="form-control" name="group_name" id="communityName" minlength="3" maxlength="120" required placeholder="Ex.: Canal oficial da prova" value="<cfoutput>#encodeForHtmlAttribute(VARIABLES.specialGroupsForm.nome)#</cfoutput>"/></label>
          <label class="cm-field">Descrição<textarea class="form-control" name="group_description" maxlength="1000" rows="2" placeholder="Qual é o propósito desta comunidade?"><cfoutput>#encodeForHtml(VARIABLES.specialGroupsForm.descricao)#</cfoutput></textarea></label>
        </fieldset>
        <fieldset class="cm-step"><legend><span>2</span> Público e vínculo</legend>
          <label class="cm-field">Quem pode participar?<select class="form-select" id="communitySource"><option value="open">Qualquer usuário · sem pré-requisitos</option><option value="challenge">Inscritos em um desafio</option><option value="circuit">Inscritos em um circuito</option><option value="training">Inscritos em um treino</option><option value="event">Inscritos em um evento</option><option value="circuit_stages">Inscritos nas etapas de um circuito</option><option value="advanced">Regras combinadas / existentes</option></select></label>
          <div id="audienceReference" class="cm-reference" hidden><label class="cm-field">Buscar <span id="referenceKindLabel">vínculo</span><input class="form-control" type="search" id="referenceSearch" placeholder="Digite parte do nome ou o ID" autocomplete="off"/></label><label class="cm-field">Selecionar<select class="form-select" id="referenceSelect"><option value="">Selecione um vínculo</option></select></label><p class="cm-muted small" id="referenceHelp" aria-live="polite"></p></div>
          <div id="advancedPolicy" hidden><p class="cm-muted small">As regras existentes são preservadas. Ao escolher outro público, você substituirá esses critérios.</p><label class="cm-field">Regra avançada (JSON)<textarea class="form-control font-monospace" id="legacyPolicy" rows="6" spellcheck="false"></textarea></label></div>
          <label class="cm-toggle"><input type="checkbox" id="officialEnabled"/><span><strong>Comunidade oficial de um evento</strong><small>O vínculo oficial é independente dos requisitos de entrada.</small></span></label>
          <div id="officialReference" class="cm-reference mt-3" hidden><label class="cm-field">Buscar evento<input class="form-control" type="search" id="officialSearch" placeholder="Nome ou ID do evento" autocomplete="off"/></label><label class="cm-field">Evento oficial<select class="form-select" id="officialSelect"><option value="">Selecione o evento</option></select></label><p class="cm-muted small" id="officialHelp" aria-live="polite"></p></div>
        </fieldset>
        <fieldset class="cm-step"><legend><span>3</span> Entrada dos participantes</legend>
          <label class="cm-toggle"><input type="checkbox" name="automatic_membership" id="automaticMembership" value="true" <cfif specialGroupsBoolean(VARIABLES.specialGroupsForm.associacao_automatica)>checked</cfif>/><span><strong>Adicionar todos os inscritos automaticamente</strong><small>Inclui os inscritos elegíveis na ativação, sincronização e no acesso ao chat.</small></span></label>
          <p id="automaticHelp" class="cm-note mt-2">Sem inclusão automática, os elegíveis podem entrar por iniciativa própria ou ser incluídos por um admin global.</p>
          <label class="cm-toggle mt-3"><input type="checkbox" name="invitations_enabled" value="true" <cfif specialGroupsBoolean(VARIABLES.specialGroupsForm.convites_habilitados)>checked</cfif>/><span><strong>Permitir inclusão por convite do admin global</strong><small>O convidado também deve cumprir os requisitos da comunidade.</small></span></label>
          <cfif NOT VARIABLES.specialGroupsEditing><label class="cm-toggle mt-3"><input type="checkbox" name="activate_now" value="true"/><span><strong>Ativar ao salvar</strong><small>Desmarcado: cria um rascunho, visível somente para admins globais.</small></span></label></cfif>
          <details class="mt-3"><summary class="cm-muted small">Imagem e identificador</summary><label class="cm-field mt-3">Imagem (caminho ou URL)<input class="form-control" name="image_path" maxlength="255" placeholder="/assets/... ou https://..." value="<cfoutput>#encodeForHtmlAttribute(VARIABLES.specialGroupsForm.path_imagem)#</cfoutput>"/></label><small class="cm-muted">Código interno: <cfoutput>#encodeForHtml(VARIABLES.specialGroupsForm.codigo)#</cfoutput></small></details>
        </fieldset>
        <div id="communityFormError" class="alert alert-danger" role="alert" hidden></div>
        <div class="cm-form-actions"><button class="btn btn-warning" type="submit" <cfif NOT VARIABLES.specialGroupsReady>disabled</cfif>><i class="fa-solid fa-floppy-disk me-2"></i><cfif VARIABLES.specialGroupsEditing>Salvar alterações<cfelse>Criar comunidade</cfif></button><button class="btn btn-outline-info" type="submit" data-action="preview" <cfif NOT VARIABLES.specialGroupsReady>disabled</cfif>><i class="fa-solid fa-users-viewfinder me-2"></i>Simular público</button></div>
      </form>
    </section>
    <aside class="cm-preview"><div class="cm-card"><div class="cm-eyebrow">Prévia da configuração</div><div class="cm-preview-icon"><i id="previewIcon" class="fa-solid fa-user-group"></i></div><h2 id="previewName">Sua comunidade</h2><p id="previewType" class="cm-muted">Grupo de conversa</p><dl><dt>Público</dt><dd id="previewAudience"></dd><dt>Vínculo oficial</dt><dd id="previewOfficial">Sem vínculo</dd><dt>Entrada</dt><dd id="previewEntry"></dd><dt>Administração</dt><dd>Exclusiva dos admins globais</dd></dl><p class="cm-note mb-0"><i class="fa-solid fa-shield-halved me-1"></i>Admins globais participam independentemente de inscrição ou convite.</p></div>
      <cfif structKeyExists(VARIABLES.specialGroupsPreview,'eligible_count')><div class="cm-card mt-3"><h3 class="h6">Simulação do público</h3><strong class="cm-simulation-count"><cfoutput>#numberFormat(VARIABLES.specialGroupsPreview.eligible_count,'_,___')#</cfoutput></strong><p class="cm-muted small">Usuários elegíveis. Nenhum participante foi adicionado pela simulação.</p><cfif structKeyExists(VARIABLES.specialGroupsPreview,'sample')><ul class="cm-sample"><cfloop array="#VARIABLES.specialGroupsPreview.sample#" item="VARIABLES.sampleUser"><li><cfoutput>#encodeForHtml(VARIABLES.sampleUser.nome)#</cfoutput></li></cfloop></ul></cfif></div></cfif>
    </aside>
  </div>
</section>
<script type="application/json" id="communityBootstrap"><cfoutput>#replace(serializeJSON({policy=VARIABLES.specialGroupsForm.regra,editing=VARIABLES.specialGroupsEditing}),'<','\u003c','all')#</cfoutput></script>
<script src="/administracao/chat/grupos-especiais/assets/manager.js?v=20261002" defer></script>
