-- business_ai_mails resolves the existing Business scheduler identity; no credential is created.
-- Initially inactive. Activation follows native compilation and read-only production checks.
INSERT INTO public.tb_cron_jobs(nome,descricao,projeto,ambiente,endpoint_url,http_method,content_type,request_body,headers_json,auth_mode,secret_ref,interval_minutes,timeout_seconds,retry_limit,ativo,executar_em_atraso,max_runtime_seconds,next_run_at)
SELECT 'CRM interno - Notificações','Entrega somente campanhas revisadas e confirmadas; limpa acessos com mais de 90 dias.','roadrunners','prod','https://business.roadrunners.run/api/crm-interno-notifications.cfm','POST','application/json','{"scope":"crm.notifications.worker","environment":"prod"}',CAST('{}' AS jsonb),'hmac_sha256','business_ai_mails',2,110,0,false,true,120,now()
WHERE NOT EXISTS(SELECT 1 FROM public.tb_cron_jobs WHERE endpoint_url='https://business.roadrunners.run/api/crm-interno-notifications.cfm');
INSERT INTO public.tb_cron_jobs(nome,descricao,projeto,ambiente,endpoint_url,http_method,content_type,request_body,headers_json,auth_mode,secret_ref,interval_minutes,timeout_seconds,retry_limit,ativo,executar_em_atraso,max_runtime_seconds,next_run_at)
SELECT 'CRM interno - E-mail','Entrega somente campanhas revisadas e confirmadas. Não repete resultados incertos.','business','prod','https://business.roadrunners.run/api/crm-interno-email.cfm','POST','application/json','{"scope":"crm.email.worker","environment":"prod"}',CAST('{}' AS jsonb),'hmac_sha256','business_ai_mails',2,110,0,false,true,120,now()
WHERE NOT EXISTS(SELECT 1 FROM public.tb_cron_jobs WHERE endpoint_url='https://business.roadrunners.run/api/crm-interno-email.cfm');
-- Histórico diário de públicos: nenhum contato; captura no máximo cinco públicos por execução.
INSERT INTO public.tb_cron_jobs(nome,descricao,projeto,ambiente,endpoint_url,http_method,content_type,request_body,headers_json,auth_mode,secret_ref,interval_minutes,timeout_seconds,retry_limit,ativo,executar_em_atraso,max_runtime_seconds,next_run_at)
SELECT 'CRM interno - Histórico de públicos','Fotografias completas dos públicos ativos, em lotes retomáveis.','business','prod','https://business.roadrunners.run/api/crm-interno-history.cfm','POST','application/json','{"scope":"crm.history.worker","environment":"prod"}',CAST('{}' AS jsonb),'hmac_sha256','business_ai_mails',10,110,0,false,true,120,(date_trunc('day',now() AT TIME ZONE 'America/Sao_Paulo')+interval '1 day 3 hours') AT TIME ZONE 'America/Sao_Paulo'
WHERE NOT EXISTS(SELECT 1 FROM public.tb_cron_jobs WHERE endpoint_url='https://business.roadrunners.run/api/crm-interno-history.cfm');
-- Conciliação de pedidos Todo Santo Dia: consulta Pagar.me via Business e não envia contatos.
INSERT INTO public.tb_cron_jobs(nome,descricao,projeto,ambiente,endpoint_url,http_method,content_type,request_body,headers_json,auth_mode,secret_ref,interval_minutes,timeout_seconds,retry_limit,ativo,executar_em_atraso,max_runtime_seconds,next_run_at)
SELECT 'CRM interno - Compras Todo Santo Dia','Concilia até três pedidos vinculados por execução com GET autenticado ao Pagar.me; nenhum contato.','business','prod','https://business.roadrunners.run/api/crm-interno-commerce.cfm','POST','application/json','{"scope":"crm.commerce.worker","environment":"prod"}',CAST('{}' AS jsonb),'hmac_sha256','business_ai_mails',5,110,0,false,true,120,now()+interval '5 minutes'
WHERE NOT EXISTS(SELECT 1 FROM public.tb_cron_jobs WHERE endpoint_url='https://business.roadrunners.run/api/crm-interno-commerce.cfm');
