<cfif NOT structKeyExists(VARIABLES,"helpdeskCanManage") OR NOT VARIABLES.helpdeskCanManage><cfheader statuscode="403" statustext="Forbidden"/><cfabort/></cfif>
<cfoutput>
<details class="hd-sectors" id="hd-setores" <cfif val(URL.gestao ?: 0) OR val(URL.setor_novo ?: 0) OR qHelpdeskSetorEdit.recordcount>open</cfif>>
  <summary>Setores e responsáveis <small>Organização das filas de atendimento</small></summary>
  <div class="d-flex flex-wrap justify-content-between gap-2 my-3"><p class="text-muted small mb-0">O responsável é definido por setor, não individualmente por chamado.</p><a class="btn btn-outline-secondary btn-sm" href="#encodeForHTMLAttribute(hdUrl({setor_novo=1}))###hd-setores">Novo setor</a></div>
  <cfif val(URL.setor_novo ?: 0) OR qHelpdeskSetorEdit.recordcount>
    <form class="hd-sector-editor" method="post" action="#encodeForHTMLAttribute(hdUrl({gestao=1}))###hd-setores">
      <input type="hidden" name="helpdesk_csrf" value="#encodeForHTMLAttribute(SESSION.helpdeskCsrf)#"/><input type="hidden" name="helpdesk_action" value="salvar_setor"/><input type="hidden" name="setor_id" value="<cfif qHelpdeskSetorEdit.recordcount>#qHelpdeskSetorEdit.id_setor#</cfif>"/>
      <h3 class="h6"><cfif qHelpdeskSetorEdit.recordcount>Editar setor<cfelse>Criar setor</cfif></h3>
      <div class="hd-sector-fields"><div><label for="hd-sector-name">Nome do setor</label><input class="form-control" id="hd-sector-name" name="setor_nome" maxlength="120" required value="<cfif qHelpdeskSetorEdit.recordcount>#encodeForHTMLAttribute(qHelpdeskSetorEdit.nome_setor)#</cfif>"/></div><div><label for="hd-sector-owner">Responsável padrão</label><select class="form-select" id="hd-sector-owner" name="setor_responsavel_id"><option value="">Sem responsável</option><cfloop query="qHelpdeskAdmins"><option value="#qHelpdeskAdmins.id#" <cfif qHelpdeskSetorEdit.recordcount AND val(qHelpdeskSetorEdit.id_usuario_responsavel) EQ qHelpdeskAdmins.id>selected</cfif>>#encodeForHTML(qHelpdeskAdmins.name)#</option></cfloop></select></div><div><label for="hd-sector-active">Disponibilidade</label><select class="form-select" id="hd-sector-active" name="setor_ativo"><option value="true">Ativo</option><option value="false" <cfif qHelpdeskSetorEdit.recordcount AND NOT qHelpdeskSetorEdit.ativo>selected</cfif>>Inativo</option></select></div></div>
      <label for="hd-sector-description" class="mt-3">Descrição</label><textarea class="form-control mb-3" id="hd-sector-description" name="setor_descricao" rows="2" maxlength="2000"><cfif qHelpdeskSetorEdit.recordcount>#encodeForHTML(qHelpdeskSetorEdit.descricao_setor)#</cfif></textarea><button class="btn btn-warning" type="submit">Salvar setor</button> <a href="#encodeForHTMLAttribute(hdUrl({gestao=1}))###hd-setores" class="btn btn-link">Cancelar</a>
    </form>
  </cfif>
  <div class="table-responsive"><table class="table"><caption class="visually-hidden">Setores de atendimento e seus responsáveis</caption><thead><tr><th scope="col">Setor</th><th scope="col">Responsável</th><th scope="col">Disponibilidade</th><th scope="col">Ações</th></tr></thead><tbody><cfloop query="qHelpdeskSetores"><tr><td><strong>#encodeForHTML(qHelpdeskSetores.nome_setor)#</strong><div class="small text-muted">#encodeForHTML(qHelpdeskSetores.descricao_setor)#</div></td><td>#len(trim(qHelpdeskSetores.nome_responsavel)) ? encodeForHTML(qHelpdeskSetores.nome_responsavel) : 'Não definido'#</td><td><cfif qHelpdeskSetores.ativo>Ativo<cfelse>Inativo</cfif></td><td><div class="hd-inline"><a class="btn btn-sm btn-outline-secondary" href="#encodeForHTMLAttribute(hdUrl({setor_id=qHelpdeskSetores.id_setor}))###hd-setores">Editar</a><form method="post" action="#encodeForHTMLAttribute(hdUrl({gestao=1}))#"><input type="hidden" name="helpdesk_csrf" value="#encodeForHTMLAttribute(SESSION.helpdeskCsrf)#"/><input type="hidden" name="helpdesk_action" value="status_setor"/><input type="hidden" name="setor_id" value="#qHelpdeskSetores.id_setor#"/><input type="hidden" name="setor_status" value="#qHelpdeskSetores.ativo ? 'false' : 'true'#"/><button class="btn btn-link btn-sm" type="submit">#qHelpdeskSetores.ativo ? 'Desativar' : 'Ativar'#</button></form></div></td></tr></cfloop><cfif NOT qHelpdeskSetores.recordcount><tr><td colspan="4">Nenhum setor cadastrado.</td></tr></cfif></tbody></table></div>
</details>
</cfoutput>
