-- Saída 2025: preserva a publicação 55 e a referência do PDF; atualiza somente 83 valores de ritmo/CNA pelo congelamento 60.
WITH anterior AS (SELECT result->'rows'->0->'payload' AS payload FROM estudo.notebook_runs WHERE id=55 AND frozen AND status='ok' AND NOT truncated),
fonte AS (SELECT * FROM estudo.notebook_runs WHERE id=60 AND frozen AND status='ok' AND NOT truncated),
m AS (SELECT CASE WHEN r->>'indicador'='cna' THEN 'cna_'|| (r->>'distancia') ELSE 'performance_'||(r->>'distancia')||'_'||(r->>'segmento') END AS serie,r->>'faixa' AS categoria,r
 FROM fonte CROSS JOIN LATERAL jsonb_array_elements(result->'rows') r),
notas AS (SELECT serie,CASE WHEN serie LIKE 'cna_%' THEN 'Recálculo 2025 anual por data final do evento no Brasil. Status 0, homologado, concluinte e tempo positivo. PCD=false e ranking nulo/diferente de false; não restringe tipo de corrida, como a fonte original. Distâncias exatas de 5/10 km, 21–21,1 e 42–42,2 km. Intervalos CNA com limite inferior incluído e superior excluído. Cadastros PCD e modalidades ainda precisam de revisão; nenhum resultado foi excluído só pelo nome. Base própria por distância. Consulta 274 rev2, congelamento 60; auditoria 59, coleta 30/09/2026. Sem corte 14+.'
 ELSE 'Recálculo 2025 anual por data final do evento no Brasil. Rua, status 0, homologado, concluinte e tempo positivo; não exclui PCD nem filtra ranking. Distâncias exatas de 5/10 km, 21≤d<22 e 42≤d<43 km. Cada faixa exclui o limite inferior e inclui o superior; <4:00 na maratona é somente (3h30,4h], não acumulado. Base própria por distância e gênero; Todos inclui registros de gênero não F/M. Rótulos históricos preservados, mas intervalo exato informado por categoria. Consulta 274 rev2, congelamento 60; auditoria 59, coleta 30/09/2026. Sem corte 14+.' END AS nota FROM m GROUP BY serie),
comps AS (SELECT c.value || CASE WHEN m.serie IS NOT NULL THEN jsonb_build_object('atual',jsonb_build_object('valor',m.r->'percentual','contagem',m.r->'total','denominador',m.r->'denominador','fonte','Notebook · execução #60 · 30/09/2026','nota',m.r->>'intervalo'),'status','notebook_em_conciliacao') ELSE '{}'::jsonb END AS item,c.ordinality AS ordem
 FROM anterior CROSS JOIN LATERAL jsonb_array_elements(payload->'comparacoes') WITH ORDINALITY c LEFT JOIN m ON m.serie=c.value->>'serie' AND m.categoria=c.value->>'categoria')
SELECT payload || jsonb_build_object(
 'meta',payload->'meta'||jsonb_build_object('notebook_fontes',(payload->'meta'->'notebook_fontes')||(SELECT jsonb_agg(jsonb_build_object('execucao',id,'celula',cell_id,'revisao',cell_version,'coletado_em',started_at)) FROM fonte)),
 'comparacoes',(SELECT jsonb_agg(item ORDER BY ordem) FROM comps),
 'conciliacao',jsonb_build_object('compativel_no_valor',0,'divergente',0,'nao_recalculado',0,'compativel_no_arredondamento',0,'notebook_em_conciliacao',0)||(SELECT jsonb_object_agg(status,total) FROM (SELECT item->>'status' AS status,count(*) AS total FROM comps GROUP BY 1) q),
 'series',(SELECT jsonb_agg(s.value || CASE WHEN n.nota IS NOT NULL THEN jsonb_build_object('ressalva',n.nota) ELSE '{}'::jsonb END ORDER BY s.ordinality) FROM jsonb_array_elements(payload->'series') WITH ORDINALITY s LEFT JOIN notas n ON n.serie=s.value->>'id')
) AS payload FROM anterior WHERE (SELECT count(*) FROM m)=83 AND (SELECT count(*) FROM comps WHERE item->'atual'->>'fonte'='Notebook · execução #60 · 30/09/2026')=83
