CREATE ROLE runnerhub LOGIN;
CREATE ROLE runner_dba LOGIN;
CREATE TYPE status_conta_evento AS ENUM ('ATIVO','PENDENTE','INATIVO');
CREATE TABLE tb_evento_corridas(id_evento integer PRIMARY KEY,ativo boolean DEFAULT true,nome_evento text,tag text,cidade text,cod_cidade integer,estado text,data_inicial date,data_final date,tipo_corrida text,endereco text,coordenadas text,url_inscricao text,url_hotsite text,inscricao_disponibilidade jsonb,descricao text,url_imagem text,url_imagem_listagem text,descricao_original text,resumo text,categorias text,organizador text,url_resultado text);
CREATE TABLE tb_conta_eventos(id_conta bigint,id_evento integer,status status_conta_evento,usuario_cadastro bigint,data_atualizacao timestamp,PRIMARY KEY(id_conta,id_evento));
CREATE TABLE tb_conta_evento_solicitacoes(id_solicitacao bigserial PRIMARY KEY,id_conta bigint,id_evento integer,id_usuario_solicitante bigint,url_informada text,tag_informada text,mensagem text,status text,data_criacao timestamp DEFAULT now(),data_revisao timestamp,observacao_revisor text,id_usuario_revisor bigint);
CREATE TABLE tb_evento_corridas_percursos(id_evento_percurso integer PRIMARY KEY,id_evento integer,percurso_evento numeric,unidade_de_medida text,data_percurso date,hora_largada time,tipo_corrida text,percurso_bloqueado boolean);
CREATE TABLE tb_fornecedores(id_fornecedor integer PRIMARY KEY,nome_fornecedor text);
CREATE TABLE tb_fornecedores_tipos(id_fornecedor_tipo integer PRIMARY KEY,descricao_tipo text);
CREATE TABLE tb_evento_corridas_fornecedores(id_evento integer,id_fornecedor integer REFERENCES tb_fornecedores,id_fornecedor_tipo integer REFERENCES tb_fornecedores_tipos);
CREATE TABLE tb_evento_corridas_relaciona(id_evento integer,id_evento_parceiro integer,id_parceiro integer,nome_variavel text);
CREATE TABLE tb_cidades(cod_cidade integer,nome_cidade text,uf text);
CREATE TABLE tb_log(log_item text,log_item_id text,log_user text,site text);
CREATE TABLE tb_badges_tipos(image_path text,badge text,tipo_badge text,min_km integer,ordem integer);
CREATE TABLE tb_badges(id_evento integer,percurso integer,badge text,valor_badge text,complemento_badge text,flag_badge boolean,UNIQUE(id_evento,percurso,badge));
CREATE EXTENSION IF NOT EXISTS unaccent;
INSERT INTO tb_evento_corridas(id_evento,nome_evento,tag,cidade,estado,data_final,url_inscricao) VALUES(701,'Own','own-event','Teste','SP','2026-12-01','https://example.test/old'),(702,'Foreign','foreign-event','Teste','SP','2026-12-01',''),(703,'Public','public-event','Teste','SP','2026-12-01','');
INSERT INTO tb_conta_eventos VALUES(102,701,'ATIVO',904,now()),(103,702,'ATIVO',902,now());
INSERT INTO tb_evento_corridas_percursos VALUES(711,701,5,'km','2026-12-01',null,'rua',false),(712,702,10,'km','2026-12-01',null,'rua',false);
INSERT INTO tb_fornecedores VALUES(1,'One'),(2,'Two'); INSERT INTO tb_fornecedores_tipos VALUES(1,'Organizador'),(2,'Timer');
INSERT INTO tb_evento_corridas_fornecedores VALUES(701,1,1),(702,2,2);
INSERT INTO tb_evento_corridas_relaciona VALUES(702,888,1,'competition_id');
INSERT INTO tb_cidades VALUES(123,'Teste','SP'),(124,'Outra cidade','RJ');
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO runnerhub,runner_dba;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO runnerhub,runner_dba;
