// Supplemental integrated HTTP flow; other suites own boundary/remoting, payments and Events matrices.
// Every target is a copied real handler in a private loopback servlet and disposable PostgreSQL cluster.
import {mkdirSync,cpSync,writeFileSync,readFileSync,existsSync,readdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {createServer} from 'node:net';
export async function runIntegrationHttp({root,scratch,port,boxHome,execute,sql}) {
 // Real legacy voucher functions are required by the Ads page readiness check even for delegated campaign-only users.
 const voucherSource=readFileSync(resolve(root,'../RoadRunners/_codex/sql/2026-08-23_ads_legacy_voucher_balance_bridge.sql'),'utf8');
 for(const name of ['create_voucher','change_voucher_status','redeem_voucher']){const start=voucherSource.indexOf('CREATE OR REPLACE FUNCTION ads.'+name+'(');const end=voucherSource.indexOf('$function$;',start);if(start<0||end<0)throw Error('Missing canonical voucher fixture');await sql(voucherSource.slice(start,end+11));}
 await sql('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ads TO runnerhub; GRANT SELECT ON ALL TABLES IN SCHEMA ads TO runnerhub');
 await sql("INSERT INTO ads.placements(placement_key,channel,surface,format_key,device_class,status) VALUES('rr-home-upcoming-native-secondary','ROADRUNNERS','HOME_UPCOMING_SECONDARY','NATIVE_EVENT','ALL','ACTIVE')");
 const app=resolve(scratch,'integration-http');mkdirSync(app,{recursive:true});
 const copy=name=>{const dst=resolve(app,name);mkdirSync(dirname(dst),{recursive:true});cpSync(resolve(root,name),dst,{recursive:true});};
 for(const name of ['services','includes','eventos','gestao-clientes','convites','selecionar-conta','administracao/contas','ads','index.cfm','home_logado.cfm','delegation_home.cfm','cadastro/status.cfm','assets/user.png','assets/css','assets/js','assets/plugins','lib/images'])if(existsSync(resolve(root,name)))copy(name);
 const ds=user=>`{class="org.postgresql.Driver",bundleName="org.postgresql.jdbc",bundleVersion="42.2.20",connectionString="jdbc:postgresql://127.0.0.1:${port}/business_delegation_test",username="${user}",password=""}`;
 const settings=`<cfset THIS.charset={resource="UTF-8",web="UTF-8"}/><cfset THIS.datasource="business_delegation_test"/><cfset THIS.datasources={business_delegation_test=${ds('business_delegation_test')},runnerhub=${ds('runnerhub')},runner_dba=${ds('business_delegation_test')}}/><cfset THIS.mappings["/services"]="${app}/services"/><cfset THIS.mappings["/ads"]="${app}/ads"/>`;
 let source=readFileSync(resolve(root,'Application.cfc'),'utf8').replace('secure=true','secure=false').replace('<cfset THIS.datasource = "runner_dba"/>',settings);
 source=source.replace(/<cffunction\s+name="OnApplicationStart"[\s\S]*?<\/cffunction>/,'<cffunction name="OnApplicationStart" returntype="boolean"><cfset APPLICATION.businessAccountDelegationEnabled=true/><cfset APPLICATION.codSite="fixture"/><cfreturn true/></cffunction>');writeFileSync(resolve(app,'Application.cfc'),source);
 // Surrounding visual assets stay local; the real backend, root routing and feature templates are unchanged.
 const head=resolve(app,'includes/estrutura/head.cfm');writeFileSync(head,readFileSync(head,'utf8').replace(/<link[^>]+https:\/\/[^>]+>/g,'').replace(/<script[^>]+https:\/\/[\s\S]*?<\/script>/g,''));
 const footer=resolve(app,'includes/estrutura/footer.cfm');writeFileSync(footer,readFileSync(footer,'utf8').replace(/<script[^>]+src="https:\/\/[^>]+><\/script>/g,''));
 writeFileSync(resolve(app,'home.cfm'),'<h1>Login sintético local</h1>');
 writeFileSync(resolve(app,'template.cfm'),'<cfinclude template="includes/estrutura/head.cfm"><body data-mdb-theme="dark"><main class="container"><cfinclude template="home_logado.cfm"></main></body>');
 // Admin host adapter supplies the same identity/context/CSRF inputs as the legacy page; mutation includes are real.
 writeFileSync(resolve(app,'administracao/contas/index.cfm'),`<cfinclude template="../../includes/backend/backend_login.cfm"><cfparam name="URL.busca" default=""><cfset VARIABLES.accountsPage=1/><cfset VARIABLES.accountManagementTab="gestoras"/><cfset VARIABLES.businessAccountsSimulationActive=structKeyExists(REQUEST,'businessAccessContext') AND REQUEST.businessAccessContext.accessMode EQ 'INTERNAL_SIMULATION'/><cfset VARIABLES.businessAccountsCanAdminAll=REQUEST.businessIdentity.id EQ 901/><cfset qBusinessAccountEdit=queryNew('id_conta')/><cfif structKeyExists(URL,'conta_id')><cfset queryAddRow(qBusinessAccountEdit)/><cfset querySetCell(qBusinessAccountEdit,'id_conta',val(URL.conta_id))/></cfif>
 <cfif CGI.request_method EQ 'POST' AND structKeyExists(FORM,'account_registration_action')><cfset VARIABLES.accountRegistrationAction=FORM.account_registration_action/><cfset VARIABLES.accountRegistrationRequestId=FORM.id_solicitacao/><cfinclude template="includes/delegation_backend.cfm"/><cfif NOT structKeyExists(VARIABLES,'accountRegistrationErrors')><cflocation url="#VARIABLES.accountRegistrationRedirectUrl#" addtoken="false"/></cfif></cfif>
 <cfinclude template="includes/delegation_workspace_backend.cfm"><cfinclude template="../../includes/estrutura/head.cfm"><body data-mdb-theme="dark"><main class="container py-4"><h1>Revisão interna</h1><cfinclude template="delegation_queue.cfm"><cfif qBusinessAccountEdit.recordCount><cfinclude template="delegation_home.cfm"></cfif></main></body>`);
 mkdirSync(resolve(app,'fixtures'),{recursive:true});
 writeFileSync(resolve(app,'fixtures/SyntheticGoogleVerifier.cfc'),`component output=false {public struct function verify(required string token,required string expectedNonce){if(token!='synthetic-pending'||!len(expectedNonce))throw(type='Synthetic.Invalid');return {sub='synthetic-pending',email='pending@example.test',name='Pending Owner',picture=''};}}`);
 writeFileSync(resolve(app,'prepare-login.cfm'),`<cfscript>APPLICATION.businessGoogleVerifierV1=createObject('component','fixtures.SyntheticGoogleVerifier');writeOutput('CSRF=' & SESSION.businessLoginCsrf);</cfscript>`);
 for(const [name,id,email,selection] of [['manager',902,'owner@example.test',"{accountId=101,accessMode='DIRECT',managerAccountId=0,relationshipId=0}"],['operator',903,'operator@example.test',"{accountId=101,accessMode='DIRECT',managerAccountId=0,relationshipId=0}"],['viewer',905,'viewer@example.test',"{accountId=101,accessMode='DIRECT',managerAccountId=0,relationshipId=0}"],['internal',901,'reviewer@example.test','{}'],['owner',907,'new@example.test','{}'],['pending',908,'pending@example.test','{}']])writeFileSync(resolve(app,`bootstrap-${name}.cfm`),`<cfscript>structDelete(SESSION,'businessAccessSelection');structDelete(SESSION,'businessAccessInvalidated');createObject('component','services.BusinessAuthSession').establish(SESSION,${id},{sub='synthetic-${name}',email='${email}',name='Synthetic ${name}',picture=''});SESSION.businessRememberCheckedAt=now();if(!structIsEmpty(${selection})){SESSION.businessAccessSelection=${selection};SESSION.businessActiveAccountId=SESSION.businessAccessSelection.accountId;}else structDelete(SESSION,'businessActiveAccountId');writeOutput('READY');</cfscript>`);
 mkdirSync(resolve(app,'WEB-INF/lib'),{recursive:true});cpSync(resolve(boxHome,'lib/lucee-5.3.10.120.jar'),resolve(app,'WEB-INF/lib/lucee.jar'));writeFileSync(resolve(app,'WEB-INF/web.xml'),readFileSync(resolve(boxHome,'cfml/system/config/web.xml'),'utf8'));
 cpSync(resolve(boxHome,'engine/cfml/cli/lucee-server/bundles'),resolve(scratch,'integration-lucee/lucee-server/bundles'),{recursive:true});
 const listener=createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const httpPort=listener.address().port;await new Promise(r=>listener.close(r));
 mkdirSync(resolve(scratch,'integration-tmp'),{recursive:true});
 const task=execute('/usr/bin/java',['-Dfile.encoding=UTF-8',`-Djava.io.tmpdir=${resolve(scratch,'integration-tmp')}`,`-Dlucee.server.dir=${resolve(scratch,'integration-lucee')}`,'-jar',resolve(boxHome,'lib/runwar-4.8.3.jar'),'-war',app,'-host','127.0.0.1','-p',String(httpPort),'-b','false','-open','false','-urlrewriteenable','false','-logDir',resolve(scratch,'integration-logs')],undefined,{timeout:1800000});
 let servletExit;task.then(result=>{servletExit=result;});
 const base=`http://127.0.0.1:${httpPort}`;let cookies='';
 const request=async(path,options={})=>{const response=await fetch(base+path,{redirect:'manual',...options,headers:{Cookie:cookies,...options.headers}});const jar=new Map(cookies.split('; ').filter(Boolean).map(c=>[c.split('=')[0],c]));for(const item of response.headers.getSetCookie()){const pair=item.split(';')[0];jar.set(pair.split('=')[0],pair);}cookies=[...jar.values()].join('; ');return {status:response.status,body:await response.text(),location:response.headers.get('location')||''};};
 const assert=(ok,label,result={})=>{if(!ok){for(const name of readdirSync(app,{recursive:true}))if(String(name).endsWith('business_ads_v1.log'))writeFileSync(resolve(root,'../task-11-ads-diagnostic.log'),readFileSync(resolve(app,name)));writeFileSync(resolve(root,'../task-11-http-failure.html'),(result.body||'').replace(/(name="(?:token|[^\"]*csrf|business_access_token)"[^>]*value=")[^"]*/gi,'$1[redacted]'));throw Error(label+': '+JSON.stringify({status:result.status,location:result.location,body:result.body?.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').slice(0,1700)}));}};
 const decode=value=>value.replaceAll('&amp;','&').replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))).replace(/&#([0-9]+);/g,(_,n)=>String.fromCharCode(Number(n)));
 const forms=body=>[...body.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/gi)].map(m=>({action:decode((m[1].match(/action="([^"]+)"/)||[])[1]||''),fields:Object.fromEntries([...m[2].matchAll(/<input\b(?=[^>]*type="hidden")[^>]*name="([^"]+)"[^>]*value="([^"]*)"/gi)].map(i=>[i[1].toLowerCase(),decode(i[2])]))}));
 const post=(path,fields)=>request(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});
 const boot=async name=>{cookies='';const r=await request('/bootstrap-'+name+'.cfm');assert(r.status===200&&r.body.includes('READY'),'bootstrap '+name,r);};
 const workspace='/gestao-clientes/?gestora=101&tab=clientes';
 const wsAction=async(action,extra,predicate=()=>true)=>{const page=await request(workspace);assert(page.status===200,'workspace render',page);const f=forms(page.body).find(f=>f.fields.business_delegation_action===action&&predicate(f));assert(!!f,'workspace form '+action,page);const response=await post(f.action,{...f.fields,...extra});assert(response.status===302,'workspace '+action,response);return response;};
 try{
  let ready=false;for(let n=0;n<120;n++){if(servletExit)throw Error('Servlet exited before ready: '+JSON.stringify(servletExit));try{const r=await request('/bootstrap-manager.cfm');if(r.status===200){ready=true;break;}if(r.status>=500)assert(false,'servlet startup',r);}catch(e){if(!String(e).includes('fetch failed'))throw e;}await new Promise(r=>setTimeout(r,250));}assert(ready,'servlet ready');
  const create=async(name,document,email)=>{await wsAction('create_client',{nome_empresa:name,tipo_titular:'PJ',documento:document,nome_responsavel:'Synthetic Owner',email_responsavel:email,tipo_prestador:'Organizador',cap_ads_campaigns_manage:'1',cap_events_view:'1'});return JSON.parse(await sql(`SELECT json_build_object('id',v.id_vinculo,'account',v.id_conta_cliente,'request',sol.id_solicitacao) FROM tb_conta_gestao_vinculos v JOIN tb_conta_cadastro_solicitacoes sol ON sol.gestao_vinculo_id=v.id_vinculo WHERE sol.documento='${document}'`));};
  const teamPage=await request('/gestao-clientes/?gestora=101&tab=equipe&estado=ATIVO');assert(teamPage.status===200&&teamPage.body.includes('Manager Operator'),'actual enum membership filter renders',teamPage);
  const created=await create('Cliente Integração','91919191919191','new@example.test');
  const pending=await create('Cliente Pendente','92929292929292','pending@example.test');
  assert((await sql(`SELECT status FROM tb_contas WHERE id_conta=${created.account}`)).trim()==='PENDENTE','create stays pending');
  const issue=async(row,email)=>{await wsAction('invite_owner',{owner_email:email},f=>f.fields.relationship_id===String(row.id));const page=await request(workspace);const link=decode((page.body.match(/id="business-issued-link"[^>]*value="([^"]+)"/)||[])[1]||'');assert(link.startsWith('/convites/?token='),'one-time owner link');return link;};
  const ownerLink=await issue(created,'new@example.test');const pendingLink=await issue(pending,'pending@example.test');
  await boot('pending');await request(pendingLink);let proposal=await request('/convites/');let acceptance=await post('/convites/',{...forms(proposal.body)[0].fields,action:'accept'});assert(acceptance.status===302,'pending owner accepts',acceptance);
  cookies='';const prepared=await request('/prepare-login.cfm');const callback=await post('/',{action:'googlesignin',credential:'synthetic-pending',business_login_csrf:prepared.body.split('CSRF=')[1]?.trim()});assert(callback.status===302,'fresh pending login',callback);
  const pendingHome=await request('/');assert(pendingHome.status===200&&pendingHome.body.includes('Sua titularidade foi confirmada'),'fresh pending owner real root routing',pendingHome);
  for(const path of ['/ads/','/eventos/'])for(const method of ['GET','POST']){const before=await sql('SELECT count(*) FROM ads.campaigns');const denied=method==='GET'?await request(path):await post(path,{ads_v1_action:'save_campaign',name:'Unauthorized pending'});assert(denied.status===302&&denied.location==='/','pending cannot operate '+method+' '+path,denied);assert(await sql('SELECT count(*) FROM ads.campaigns')===before,'pending POST zero campaign writes');}
  console.log('PASS http fresh verified owner login, actual root pending status and preapproval operational denial');
  await boot('internal');let queue=await request('/administracao/contas/?tab=gestoras');assert(queue.status===200,'internal queue',queue);const review=forms(queue.body).find(f=>f.fields.id_solicitacao===String(created.request));assert(!!review,'created request in internal queue',queue);const reviewed=await post('/administracao/contas/?tab=gestoras',{...review.fields,capabilities:'ads.campaigns.view,ads.campaigns.manage,events.view',account_registration_action:'aprovar'});assert(reviewed.status===302,'real internal review adapter',reviewed);assert((await sql(`SELECT status FROM tb_contas WHERE id_conta=${created.account}`)).trim()==='ATIVA','internal review active');
  await boot('manager');await wsAction('assign_member',{membership_id:'1002',cap_ads_campaigns_manage:'1'},f=>f.fields.assignment_target?.startsWith(created.id+':'));
  console.log('PASS http actual create → internal review → assign operator persisted');
  const choose=async(account,mode,manager='0')=>{const page=await request('/selecionar-conta/');assert(page.status===200,'selector renders',page);const f=forms(page.body).find(f=>f.fields.accountid===String(account)&&f.fields.accessmode===mode&&f.fields.manageraccountid===String(manager));assert(!!f,'selector explicit option '+account+'/'+mode+'/'+manager,page);const result=await post('/selecionar-conta/',f.fields);assert(result.status===302,'selector switches',result);};
  await boot('manager');await choose(102,'DIRECT');await choose(102,'DELEGATED',103);let onlyEvents=await request('/');assert(onlyEvents.status===200&&onlyEvents.body.includes('Via')&&!onlyEvents.body.includes('href="/ads/?view=campaigns"'),'second agency has no Ads union',onlyEvents);await choose(102,'DELEGATED',101);let allGranted=await request('/');assert(allGranted.status===200&&allGranted.body.includes('href="/ads/?view=campaigns"'),'first agency own grants',allGranted);
  await boot('operator');await choose(created.account,'DELEGATED',101);
  // Actual Ads backend and canonical SQL; fixture supplies a legitimate client event without approving campaigns.
  await sql(`ALTER TABLE tb_evento_corridas ADD COLUMN tag text,ADD COLUMN nome_evento text,ADD COLUMN data_evento date,ADD COLUMN data_inicial date DEFAULT CURRENT_DATE+10,ADD COLUMN data_final date DEFAULT CURRENT_DATE+10,ADD COLUMN cidade text,ADD COLUMN url_imagem text,ADD COLUMN url_imagem_listagem text,ADD COLUMN imagem text; INSERT INTO tb_evento_corridas(id_evento,ativo,estado,tag,nome_evento,data_evento) VALUES(701,true,'SP','synthetic-event','Evento Sintético',CURRENT_DATE+10); INSERT INTO tb_conta_eventos VALUES(${created.account},701,'ATIVO')`);
  const ads=await request('/ads/?view=campaigns&mode=new');assert(ads.status===200,'actual Ads page',ads);
  const campaignForm=forms(ads.body).find(f=>f.fields.ads_v1_action==='save_campaign');assert(!!campaignForm,'actual campaign form',ads);
  const campaignFields={...campaignForm.fields,core_event_id:'701',name:'Campanha Integração',cpc_bid:'1',budget_total:'10',budget_daily:'5',starts_at:'2026-10-03T12:00',ends_at:'2026-10-20T12:00',target_device_class:'ALL',target_country_code:'BR',target_region_code:'',placement_keys:'rr-home-upcoming-native',campaign_intent:'draft'};
  const saved=await post('/ads/',campaignFields);assert(saved.status===302,'actual campaign save',saved);
  const campaign=JSON.parse(await sql(`SELECT json_build_object('account',account_id,'actor',updated_by,'status',status) FROM ads.campaigns WHERE name='Campanha Integração'`));assert(campaign.account===created.account&&campaign.actor===903&&campaign.status==='DRAFT','campaign client/actor/review invariants');
  const oldCookies=cookies;
  await boot('owner');await request(ownerLink);proposal=await request('/convites/');acceptance=await post('/convites/',{...forms(proposal.body)[0].fields,action:'accept'});assert(acceptance.status===302,'active owner accepts',acceptance);
  const ownerAdmin=await request(`/administracao/contas/?conta_id=${created.account}&tab=gestoras`);assert(ownerAdmin.status===200,'direct owner governance',ownerAdmin);const revoke=forms(ownerAdmin.body).find(f=>f.fields.account_delegation_action==='revoke_relationship');assert(!!revoke,'owner revoke form',ownerAdmin);const revoked=await post(`/administracao/contas/?conta_id=${created.account}&tab=gestoras`,revoke.fields);assert(revoked.status===302,'real owner revocation',revoked);
  cookies=oldCookies;const before=await sql('SELECT count(*) FROM ads.campaigns');const oldPost=await post('/ads/',campaignFields);assert(oldPost.status===403||oldPost.status===409,'old tab denied after agency revoke',oldPost);assert(await sql('SELECT count(*) FROM ads.campaigns')===before,'zero unauthorized writes after revoke');
  console.log('PASS http direct + two agency context isolation; actual campaign save; owner acceptance/revocation; old tab POST denied with zero writes');
  if(process.env.BUSINESS_DELEGATION_BROWSER==='1'){
   writeFileSync(resolve(root,'output/playwright/local-fixture.json'),JSON.stringify({base,done:resolve(scratch,'browser-done')}));console.log('READY browser local fixture '+base);
   for(let i=0;i<1200&&!existsSync(resolve(scratch,'browser-done'));i++)await new Promise(r=>setTimeout(r,1000));
   if(!existsSync(resolve(scratch,'browser-done')))throw Error('Browser evidence not completed before fixture timeout');
  }
 }finally{task.child.kill('SIGTERM');await task;}
}
