#!/usr/bin/env node
// Exercita os assets reais do CRM com respostas sintéticas; nenhuma API de produção.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {mkdirSync} from 'node:fs';

const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const origin='http://127.0.0.1:8768';
const server=spawn('python3',['_codex/scripts/crm_ui_fixture.py'],{cwd:root,stdio:'ignore'});
let browser;
async function ready(){for(let n=0;n<50;n++){try{const response=await fetch(origin);if(response.ok)return;}catch{}await new Promise(done=>setTimeout(done,100));}throw new Error('synthetic CRM fixture did not start');}
const report={code:'todosantodia',status:'active_tracking',coverage:{registrants_as_of:'2026-09-25T09:00:00-03:00',signups_from:'2026-09-25T08:00:00-03:00',launch_date_status:'unverified',finance:{status:'unavailable'}},totals:{registrants:1,signup_starts:0},series:[],profile:{registrants:{states:[{label:'SC',people:1}],cities:[{label:'Não informado',people:1}],ages:[{label:'Não informado',people:1}]},buyers:{status:'unavailable'}}};
const calls=[];
try{
 await ready();
 browser=await chromium.launch({channel:'chrome',headless:true});
 mkdirSync(resolve(root,'output/playwright'),{recursive:true});
 for(const width of [1440,390]){
  const page=await browser.newPage({viewport:{width,height:900}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/crm-interno/api.cfm',async route=>{
   const payload=JSON.parse(new URLSearchParams(route.request().postData()).get('payload'));
   if(!payload.action.startsWith('programs.'))return route.continue();
   calls.push(payload.action);
   const financial={...report,coverage:{...report.coverage,finance:{status:'partial',linked_from:'2026-09-25T12:00:00Z',historical_status:'running',historical:{windows:81,complete_windows:1,pending:11,from_day:'2020-01-01',through_day:'2026-09-24'}}},totals:{...report.totals,paid_orders:1,identified_buyers:0,active_terms:1,renewals:0,upgrades:0,refunded_orders:0},finance:{amount_by_currency:[{currency:'BRL',net_amount_minor:4990}],series:[{period_start:'2026-09-25T00:00:00',product_code:'todosantodia',paid_orders:1,refunded_orders:0}]},linked_campaigns:[{name:'Campanha sintética'}],profile:{...report.profile,buyers:{status:'available',demographics:{states:[{label:'SC',people:1}],cities:[],ages:[]},tiers:[{label:'Básica',people:1}]}}};
   const data=payload.action==='programs.report'?(payload.input.bucket==='month'?financial:report):payload.action==='programs.users'?{items:[{id:102,name:'Corredor sintético',email:'runner@example.test',cidade:'',estado:'SC'}],total:1,page:1}:payload.action==='programs.purchases'?{items:[{order_key:'or_future1234',user_id:102,user_name:'Corredor sintético',product_code:'todosantodia',paid_at:'2026-09-25T12:00:00Z',classification:'confirmed',term_end:'2027-09-25T12:00:00Z',attribution_method:'none'},{order_key:'or_history1234',user_id:null,user_name:'',product_code:'todosantodiavip',paid_at:'2026-07-18T12:00:00Z',classification:'confirmed',term_end:'2027-07-18T12:00:00Z',attribution_method:''}],total:2,page:1}:{};
   await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({SUCCESS:true,DATA:data})});
  });
  let timelineUnavailable=false;
  await page.route('**/crm-interno/timeline.cfm',async route=>route.fulfill({status:timelineUnavailable?503:200,contentType:'application/json',body:JSON.stringify(timelineUnavailable?{success:false,error:'service_unavailable'}:{success:true,data:{items:[{id:'ad-1',name:'Corrida patrocinada',kind:'ads',status:'ACTIVE',starts_day:'2026-09-25',ends_day:'2026-10-05'},{id:'banner-1',name:'Banner de meia maratona',kind:'banner',status:'ACTIVE',starts_day:'2026-09-26',ends_day:'2026-09-28'}],truncated:false}})}));
  await page.goto(origin,{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Planejamento',exact:true}).click();
  await page.locator('#planningGantt .crm-gantt-row').first().waitFor({state:'visible'});
  assert.equal(await page.locator('.crm-gantt-program').evaluate(node=>node.getBoundingClientRect().height<=14),true,'campaign bars match the thinner rows');
  assert.equal(await page.locator('#planningGantt .crm-gantt-row').first().locator('.crm-gantt-label').innerText(),'Todo Santo Dia','Gantt shows only the campaign name in each row');
  assert.equal(await page.locator('#planningGantt .crm-gantt-row').first().evaluate(node=>node.getBoundingClientRect().height<=30),true,'single-line Gantt rows are visibly thinner');
  assert.match(await page.locator('.crm-gantt-program').getAttribute('aria-label'),/Contínua · Ativa/,'status remains available to assistive technology');
  assert.equal(await page.locator('#calendarAdvancedFilters').evaluate(node=>node.open),false,'secondary CRM filters start collapsed');
  assert.equal(await page.locator('#calendarAgenda').evaluate(node=>node.open),false,'detailed CRM agenda starts collapsed');
  assert.equal(await page.locator('#calendarAgendaCount').innerText(),'1 campanha CRM','agenda summary reports the CRM count');
  assert.equal(await page.locator('.crm-gantt-scroll').evaluate(node=>{const row=node.querySelector('.crm-gantt-row');const copies=Array.from({length:30},()=>row.cloneNode(true));copies.forEach(copy=>node.querySelector('.crm-gantt-board').append(copy));const bounded=node.scrollHeight>node.clientHeight&&node.clientHeight<=480;copies.forEach(copy=>copy.remove());return bounded;}),true,'long timelines scroll inside a bounded panel');
  await page.screenshot({path:resolve(root,`output/playwright/crm-gantt-${width}.png`)});
  if(width===390)assert.equal(await page.locator('#calendarAgenda').evaluate(node=>node.getBoundingClientRect().bottom<=innerHeight),true,'agenda summary remains visible in the first mobile viewport');
  await page.locator('#calendarAgenda summary').click();
  assert.equal(await page.locator('#calendarList').isVisible(),true,'agenda remains available on request');
  await page.locator('#calendarList [data-pressure]').first().click();
  await page.locator('#planningPressure').getByText('Outra campanha sintética').waitFor();
  await page.locator('#calendarAgenda summary').click();
  await page.locator('#calendarAdvancedFilters summary').click();
  await page.locator('#calendarFilters select[name="channel"]').selectOption('email');
  assert.equal(await page.locator('#calendarFilters select[name="channel"]').inputValue(),'email','secondary CRM filters remain usable');
  await page.locator('#calendarAdvancedFilters summary').click();
  assert.match(await page.locator('#planningGantt').innerText(),/Todo Santo Dia[\s\S]*Campanha sintética de outubro[\s\S]*Corrida patrocinada[\s\S]*Banner de meia maratona/,'Gantt includes continuous program, CRM, ads and banners');
  assert.equal(await page.locator('#planningGantt .crm-gantt-row').count(),4,'each scheduled source has one timeline row');
  assert.equal(await page.locator('.crm-gantt-program').evaluate(node=>Number.parseFloat(node.style.width)),100,'continuous program spans the selected window without a claimed launch date');
  assert.equal(await page.locator('.crm-gantt-banner').evaluate(node=>Number.parseFloat(node.style.width)),20,'banner width follows its three-day window');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`Gantt has no page overflow at ${width}px`);
  if(width===390)assert.equal(await page.locator('.crm-gantt-scroll').evaluate(node=>node.scrollWidth>node.clientWidth),true,'mobile Gantt scrolls horizontally inside its panel');
  timelineUnavailable=true;
  await page.locator('#calendarFilters button[type="submit"]').click();
  await page.locator('.crm-gantt-warning').getByText('Ads e banners indisponíveis nesta consulta.').waitFor();
  assert.match(await page.locator('#planningGantt').innerText(),/Todo Santo Dia[\s\S]*Campanha sintética de outubro/,'CRM and continuous program remain visible if the ads source fails');
  timelineUnavailable=false;
  await page.locator('#calendarFilters button[type="submit"]').click();
  await page.locator('#planningGantt .crm-gantt-row').nth(3).waitFor({state:'visible'});
  await page.getByRole('button',{name:'Campanhas',exact:true}).click();
  assert.equal(await page.locator('#crmProgramEntry').isVisible(),true,'continuous campaign has a closed summary');
  assert.equal(await page.locator('#crmProgram').isVisible(),false,'program details do not occupy the campaign page initially');
  await page.locator('[data-program-open]').click();
  await page.locator('#crmProgram').waitFor({state:'visible'});
  assert.equal(await page.locator('#crmProgram').evaluate(node=>node instanceof HTMLDialogElement && node.open && node.matches(':modal')),true,'program details open in a native modal');
  await page.screenshot({path:resolve(root,`output/playwright/crm-program-modal-open-${width}.png`)});
  assert.match(await page.locator('#crmProgram').innerText(),/Base cadastrada atual[\s\S]*1/);
  assert.match(await page.locator('#crmProgram').innerText(),/Inícios desde[\s\S]*0/);
  assert.match(await page.locator('#crmProgram').innerText(),/Compras ainda não conciliadas/);
  assert.match(await page.locator('#crmProgram').innerText(),/Não informado/);
  await page.locator('[data-program-users]').click();
  const firstUser=page.locator('[data-program-user-rows] td:first-child').first();
  await firstUser.waitFor({state:'visible'});
  assert.match(await firstUser.innerText(),/Corredor sintético/,'selected program lists its users');
  assert.equal(await page.locator('[data-program-next]').isDisabled(),true,'one user needs no second page');
  assert.equal(await page.locator('[data-program-finance-details]').isHidden(),true,'unavailable finance does not render a false zero');
  await page.locator('[data-program-filters] select[name=bucket]').selectOption('month');
  await page.locator('[data-program-filters] button[type=submit]').click();
  await page.locator('[data-program-finance-details] small').filter({hasText:'Compradores identificados'}).waitFor({state:'visible'});
  assert.match(await page.locator('[data-program-finance-details]').innerText(),/R\$\s*49,90/,'verified BRL amount is distinct from registrations');
  assert.match(await page.locator('[data-program-coverage]').innerText(),/1 de 81 janelas históricas concluídas[\s\S]*11 pedidos sem pagamento confirmado ou ambíguos/,'historical coverage and unresolved payments remain explicit');
  assert.match(await page.locator('[data-program-financial-series]').innerText(),/Compras por período e produto[\s\S]*Básica[\s\S]*1/,'paid orders are shown over time by product');
  assert.match(await page.locator('[data-program-buyer-profile]').innerText(),/Compradores identificados[\s\S]*Básica/,'verified buyer profile and current tier are distinct from registrants');
  assert.match(await page.locator('[data-program-link-status]').innerText(),/Campanha sintética/,'program-linked campaign appears as metadata');
  await page.locator('[data-program-user-source]').selectOption('buyers');
  await page.locator('[data-program-users]').click();
  assert.match(await page.locator('[data-program-user-rows]').innerText(),/Corredor sintético/,'identified buyers can be inspected');
  await page.locator('[data-program-purchases] summary').click();
  await page.getByText('or_future1234',{exact:true}).waitFor({state:'visible'});
  assert.match(await page.locator('[data-program-purchase-rows]').innerText(),/Básica[\s\S]*Pago[\s\S]*Corredor sintético[\s\S]*Orgânico/,'future purchase shows product, verified user and attribution');
  assert.match(await page.locator('[data-program-purchase-rows]').innerText(),/VIP[\s\S]*Sem vínculo/,'historical purchase cannot invent a buyer');
  assert.equal(await page.locator('[data-program-link-open]').isVisible(),true,'optional campaign linkage remains separate from sending');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`no horizontal overflow at ${width}px`);
  assert.deepEqual(errors,[],'no browser errors');
  await page.screenshot({path:resolve(root,`output/playwright/crm-program-${width}.png`)});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#crmProgram').evaluate(node=>node.open),false,'Escape closes the program modal');
  assert.equal(await page.locator('#crmProgramEntry').isVisible(),true,'closed summary remains on the campaign page');
  assert.match(await page.locator('[data-program-entry-summary]').innerText(),/base atual 1 · inícios no período 0 · compras comprovadas no período 1/,'closed summary preserves the last verified report');
  assert.equal((await page.locator('#campaignList').boundingBox()).y<900,true,'campaign list remains close to the top when the modal closes');
  await page.locator('[data-program-open]').click();
  await page.locator('#crmProgram').waitFor({state:'visible'});
  await page.locator('[data-program-close]').click();
  assert.equal(await page.locator('#crmProgram').evaluate(node=>node.open),false,'close button dismisses the program modal');
  await page.close();
 }
 const fixture=await (await fetch(origin+'/state')).json();
 assert.equal(fixture.confirmations,0,'opening the continuous program does not confirm a campaign');
 assert.ok(calls.includes('programs.report') && calls.includes('programs.users'),'read-only program actions are used');
 assert.equal(calls.includes('programs.link'),false,'opening a program does not link a campaign');
 console.log('PASS CRM continuous program browser 1440/390px, source labels, users and no delivery action');
}finally{if(browser)await browser.close();server.kill('SIGTERM');}
