(() => {
  'use strict';
  const app = document.querySelector('#crmApp'); if (!app) return;
  const $ = (selector, root = app) => root.querySelector(selector);
  const $$ = (selector, root = app) => [...root.querySelectorAll(selector)];
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lower = data => Array.isArray(data) ? data.map(lower) : data && typeof data === 'object' ? Object.fromEntries(Object.entries(data).map(([k,v]) => [k.toLowerCase(),lower(v)])) : data;
  const messages = {forbidden:'Acesso recusado. Recarregue a página em sua conta administrativa.',service_unavailable:'O CRM está temporariamente indisponível. Tente novamente.',module_disabled:'O CRM está desativado para publicação de campanhas.',source_unavailable:'Um dos critérios está sem fonte disponível. Revise os dados disponíveis.',invalid_rule:'Revise os valores dos critérios.',invalid_payload:'Revise os campos e as datas informadas.',revision_conflict:'Esta versão mudou. Reabra o registro antes de salvar.',request_conflict:'Esta operação já foi usada com outros dados. Reabra o registro.',already_exists:'Já existe uma oportunidade aberta para esta pessoa e interesse.',preview_expired:'A revisão expirou. Gere uma nova lista antes de confirmar.',invalid_destination:'Use um caminho do Road Runners ou uma URL HTTPS de um domínio autorizado.',empty_audience:'Nenhuma pessoa está elegível para este canal.',channel_unavailable:'O canal está indisponível.'};
  const labels = {draft:'Rascunho',reviewed:'Em revisão',scheduled:'Agendada',running:'Em envio',active:'Ativa',paused:'Pausada',completed:'Concluída',cancelled:'Cancelada',failed:'Falha',pending:'Pendente',leased:'Reservada',authorized:'Autorizada',accepted:'Aceita pelo canal',unknown:'Resultado incerto',excluded:'Excluída',notification:'Notificação',email:'E-mail',card:'Card no perfil',marketing_opt_out:'Sem opt-in comercial',channel_opt_out:'Canal cancelado',email_unverified:'E-mail não confirmado',email_suppressed:'E-mail com bloqueio registrado',frequency_limit:'Limite de contato',no_longer_eligible:'Critério deixou de ser atendido',campaign_inactive:'Campanha inativa',impression:'Impressões visíveis',click:'Cliques registrados',dismiss:'Campanhas dispensadas'};
  const state = {catalog:null,audience:null,ap:1,up:1,cp:1,campaign:null,preview:null,audiences:[],userTotal:0,evaluationPolicy:null,requestId:null,listRequest:0,evaluationRequest:0,selectionRequest:0,eligibilityRequest:0,coverageRequest:0,recommendationRequest:0,editingAudience:null,editorRequest:0,editorSaving:false};
  function message(text) { const box=$('#crmDialog').open?$('#dialogMessage'):$('#audienceEditor').open?$('#audienceMessage'):$('#campaignEditor').open?$('#campaignMessage'):$('#campaignDetailsDialog').open?$('#campaignDetailsMessage'):$('#crmProgram').open?$('[data-program-message]'):$('#crmMessage'); box.textContent=text; box.hidden=!text; }
  function date(value) { if (!value) return 'Não informado'; const parsed=new Date(value); return Number.isNaN(parsed.valueOf())?String(value):new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(parsed); }
  async function api(action,input={}) {const res=await fetch('/crm-interno/api.cfm',{method:'POST',credentials:'same-origin',body:new URLSearchParams({csrf:app.dataset.csrf,payload:JSON.stringify({action,input})})});let response;try{response=lower(await res.json());}catch{throw new Error('Sessão expirada ou serviço indisponível. Recarregue a página.');}if(!response.success)throw new Error(messages[response.error]||'Não foi possível concluir a operação.');return response.data;}
  async function task(button, action) {const previous=button?.disabled;if(button)button.disabled=true;message('');try{return await action();}catch(error){message(error.message);return null;}finally{if(button)button.disabled=state.editorSaving&&!!button.closest('#audienceEditor')?true:previous;}}
  function tab(name) {$$('[data-tab]').forEach(b=>b.dataset.tab===name?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);}
  function dialog(title,html) {$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#dialogMessage').hidden=true;if(!$('#crmDialog').open)$('#crmDialog').showModal();}
  $('#closeDialog').onclick=()=>$('#crmDialog').close();
  $$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
  const input = (key,label,value,type='number',extra='') => `<label>${label}<input data-key="${key}" type="${type}" value="${escape(value)}" ${extra}></label>`;
  const distance = value => `<label>Distância<select data-key="distance">${[['any','Qualquer'],['5','5 km'],['10','10 km'],['half','Meia maratona (21 km)'],['marathon','Maratona (42 km)']].map(([id,label])=>`<option value="${id}" ${id===String(value)?'selected':''}>${label}</option>`).join('')}</select></label>`;
  const selectField=(key,label,value,options)=>`<label>${label}<select data-key="${key}">${options.map(([id,text])=>`<option value="${escape(id)}" ${String(id)===String(value)?'selected':''}>${escape(text)}</option>`).join('')}</select></label>`;
  const states='AC:Acre|AL:Alagoas|AP:Amapá|AM:Amazonas|BA:Bahia|CE:Ceará|DF:Distrito Federal|ES:Espírito Santo|GO:Goiás|MA:Maranhão|MT:Mato Grosso|MS:Mato Grosso do Sul|MG:Minas Gerais|PA:Pará|PB:Paraíba|PR:Paraná|PE:Pernambuco|PI:Piauí|RJ:Rio de Janeiro|RN:Rio Grande do Norte|RS:Rio Grande do Sul|RO:Rondônia|RR:Roraima|SC:Santa Catarina|SP:São Paulo|SE:Sergipe|TO:Tocantins'.split('|').map(s=>{const [uf,name]=s.split(':');return [uf,`${uf} — ${name}`];});
  const stateField=(value='',optional=false)=>selectField('state',optional?'Estado (opcional)':'Estado',value,[['',optional?'Qualquer estado':'Selecione o estado'],...states]).replace('<select ',optional?'<select ':'<select required ');
  const enrollmentDays=rule=>input('days','Inscrição nos últimos dias (0 = qualquer data)',rule.days??0,'number','min="0" max="3650" required');
  const groups=[['Dados do perfil',['profile_state','profile_city','profile_age','profile_gender','birthday_month','profile_location']],['Cadastro e contato',['account_created','email_verified','marketing_optin','contact_history']],['Inscrições e provas',['brasil_gigante','challenge_enrollment','recent_result','event_agenda','event_registration','event_offers_distance']],['Uso do site',['site_access']],['Fontes ainda indisponíveis',['confirmed_distance','challenge_activity','recent_training','shoe_km']]];
  function criterionOptions(selected){return groups.map(([label,types])=>`<optgroup label="${label}">${types.filter(type=>state.catalog.capabilities[type]).map(type=>{const c=state.catalog.capabilities[type];return `<option value="${type}" ${type===selected?'selected':''} ${!c.available?'disabled':''}>${escape(c.label)}${!c.available?' · indisponível':''}</option>`;}).join('')}</optgroup>`).join('');}
  function ruleFields(type,rule={}) {
    switch(type){
      case 'profile_state':return stateField(rule.state);
      case 'profile_city':return input('city','Cidade',rule.city||'','text','required maxlength="100" placeholder="Ex.: Florianópolis"')+stateField(rule.state,true)+'<p class="crm-muted crm-wide">Nome completo da cidade do cadastro, com acentos. Estado ajuda a distinguir cidades de mesmo nome.</p>';
      case 'profile_location':return stateField(rule.state||'SC')+input('city','Cidade (opcional)',rule.city||'','text','maxlength="100"');
      case 'profile_age':return input('minimum','Idade mínima',rule.minimum??18,'number','min="0" max="120" required')+input('maximum','Idade máxima',rule.maximum??65,'number','min="0" max="120" required')+'<p class="crm-muted crm-wide">Idade completa na data da consulta. Cadastros sem data de nascimento não entram neste filtro.</p>';
      case 'profile_gender':return selectField('gender','Gênero informado no cadastro',rule.gender||'feminino',[['feminino','Feminino'],['masculino','Masculino'],['other','Outra identificação'],['unknown','Não informado']]);
      case 'birthday_month':return selectField('month','Mês de aniversário',rule.month||new Date().getMonth()+1,['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((m,i)=>[i+1,m]));
      case 'account_created':return input('days','Cadastro nos últimos dias',rule.days||30,'number','min="1" max="3650" required');
      case 'email_verified':return selectField('value','Confirmação do e-mail',rule.value||'yes',[['yes','E-mail confirmado'],['no','E-mail não confirmado']]);
      case 'marketing_optin':return selectField('value','Permissão comercial no cadastro',rule.value||'yes',[['yes','Com opt-in'],['no','Sem opt-in']])+'<p class="crm-muted crm-wide">Consultar um público não concede permissão de envio. As preferências são revalidadas na campanha.</p>';
      case 'brasil_gigante':return enrollmentDays(rule)+'<p class="crm-muted crm-wide">Cadastro próprio no Circuito Brasil Gigante. Não exige atividade ou treino no Strava.</p>';
      case 'recent_result':return input('days','Nos últimos dias',rule.days||30,'number','min="1" max="90" required')+distance(rule.distance||'any');
      case 'event_agenda':case 'event_registration':case 'event_offers_distance':return input('days','Nos próximos dias',rule.days||90,'number','min="1" max="365" required')+input('event_id','Código do evento (0 = qualquer)',rule.event_id||0,'number','min="0" required')+(type==='event_offers_distance'?distance(rule.distance||'half')+'<p class="crm-muted crm-wide">A distância é oferecida pelo evento. A modalidade escolhida pela pessoa não está informada.</p>':'');
      case 'challenge_enrollment':return input('code','Código do desafio',rule.code||'todosantodia','text','required maxlength="80" list="crmChallengeCodes"')+enrollmentDays(rule)+'<p class="crm-muted crm-wide">Filtra a inscrição feita no nosso ambiente e sua data. Não usa dias corridos calculados pelo Strava.</p>';
      case 'site_access':return input('days','Nos últimos dias',rule.days||30,'number','min="1" max="90" required')+input('minimum','Mínimo de dias com acesso',rule.minimum||3,'number','min="1" max="90" required');
      case 'contact_history':return input('days','Nos últimos dias',rule.days||7,'number','min="1" max="90" required')+selectField('contacted','Contato comercial',rule.contacted||'no',[['no','Sem contato registrado no CRM'],['yes','Com contato registrado no CRM']]);
      default:return '<p>Fonte indisponível.</p>';
    }
  }
  function addCriterion(rule={type:'profile_state',state:''}) {if($$('.crm-criterion').length>=12)return;const el=document.createElement('div');el.className='crm-criterion';el.innerHTML=`<div class="crm-line"><label style="flex:1">Filtro<select data-type>${criterionOptions(rule.type)}</select></label><button type="button" class="crm-link" data-remove aria-label="Remover critério">Remover</button></div><div class="crm-rule-fields">${ruleFields(rule.type,rule)}</div>`;$('[data-type]',el).onchange=e=>{$('.crm-rule-fields',el).innerHTML=ruleFields(e.target.value);invalidateAudience();};$('[data-remove]',el).onclick=()=>{el.remove();invalidateAudience();};$('#criteria').append(el);}
  function policy(){return {operator:$('#ruleOperator').value,criteria:$$('.crm-criterion').map(el=>Object.fromEntries([['type',$('[data-type]',el).value],...$$('[data-key]',el).map(i=>[i.dataset.key,i.type==='number'?Number(i.value):i.value])]))};}
  function invalidateAudience(){state.editorRequest++;$('#audienceSize').textContent='—';$('#audienceMessage').hidden=true;}
  function setAudience(a=null,preset=null){state.editingAudience=a;const form=$('#audienceForm');form.elements.name.value=a?.name||'';form.elements.description.value=a?.description||'';$('#audienceHeading').textContent=a?'Editar público':'Montar público';$('#audienceVersion').textContent=a?`Versão ${a.current_version}`:'';$('#ruleOperator').value=a?.policy.operator||'all';$('#criteria').innerHTML='';(a?.policy.criteria||[preset||{type:'profile_state',state:''}]).forEach(addCriterion);$('#archiveAudience').hidden=!a;invalidateAudience();}
  function openAudienceEditor(a=null){if(!state.catalog)return;setAudience(a);$('#audienceEditor').showModal();}
  function closeAudienceEditor(){if(!state.editorSaving){state.editorRequest++;$('#audienceEditor').close();}}
  $('#closeAudienceEditor').onclick=closeAudienceEditor;$('#cancelAudienceEditor').onclick=closeAudienceEditor;
  $('#audienceEditor').addEventListener('cancel',e=>{if(state.editorSaving)e.preventDefault();else state.editorRequest++;});
  function clearSelection(){state.selectionRequest++;state.evaluationRequest++;state.eligibilityRequest++;state.coverageRequest++;state.recommendationRequest++;state.audience=null;state.evaluationPolicy=null;$('#selectedAudienceName').textContent='Usuários do público';$('#userSummary').textContent='Selecione um público na lista para ver seus usuários.';$('#userRows').innerHTML='<tr><td colspan="4">Selecione um público para começar.</td></tr>';$('#userPage').textContent='';$('#userPrev').disabled=true;$('#userNext').disabled=true;$('#editAudience').hidden=true;$('#campaignFromAudience').hidden=true;$('#audienceEligibility').hidden=true;$('#audienceCoverage').hidden=true;$('#audienceRecommendations').hidden=true;$('#audienceHistory').hidden=true;$('#audienceOverlap').hidden=true;$$('[data-audience]').forEach(b=>b.classList.remove('is-selected'));}
  async function loadEligibility(selected){const request=++state.eligibilityRequest;$('#audienceEligibility').hidden=false;$('#eligibilityStamp').textContent=`Público v${selected.current_version}`;$('#eligibilityCards').textContent='Consultando elegibilidade…';try{const data=await api('audiences.eligibility',{id:selected.id,version:selected.current_version});if(request!==state.eligibilityRequest||state.audience?.id!==selected.id||state.audience?.current_version!==selected.current_version)return;const count=n=>Number(n||0).toLocaleString('pt-BR');$('#eligibilityStamp').textContent=`Público v${selected.current_version} · ${date(data.as_of)}`;$('#eligibilityCards').innerHTML=`<div class="crm-eligibility-grid">${[['email','E-mail'],['notification','Notificação'],['card','Card no perfil']].map(([key,label])=>{const channel=data.channels[key];return `<div class="crm-eligibility-card"><strong>${count(channel.eligible)}</strong><span>${label} · aptos</span><small>${count(channel.excluded)} excluídos de ${count(data.total)}</small>${channel.reasons?.length?`<details><summary>Ver motivos</summary><ul>${channel.reasons.map(r=>`<li>${escape(labels[r.code]||r.code)}: ${count(r.total)}</li>`).join('')}</ul></details>`:''}</div>`;}).join('')}</div>`;}catch(error){if(request===state.eligibilityRequest&&state.audience?.id===selected.id){$('#eligibilityCards').textContent='Contagem indisponível. Use Recalcular para tentar novamente.';$('#eligibilityStamp').textContent=`Público v${selected.current_version}`;}}}
  $('#eligibilityRefresh').onclick=()=>{if(state.audience)loadEligibility(state.audience);};
  const sourceDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))?`${String(value).slice(8,10)}/${String(value).slice(5,7)}/${String(value).slice(0,4)}`:date(value);
  async function loadCoverage(selected){const request=++state.coverageRequest;$('#coverageContent').textContent='Consultando cobertura…';try{const data=await api('audiences.coverage',{id:selected.id,version:selected.current_version});if(request!==state.coverageRequest||state.audience?.id!==selected.id||state.audience?.current_version!==selected.current_version)return;const count=n=>Number(n||0).toLocaleString('pt-BR');const fieldLabels={state:'Estado',city:'Cidade',birth:'Nascimento',gender:'Gênero informado'};const sourceLabels={results:'Resultados',agenda:'Agenda e inscrições',challenges:'Desafios',accesses:'Acessos identificados'};const sourceStatus={partial:'Parcial',not_observed:'Sem registros observados',unavailable:'Indisponível'};$('#coverageContent').innerHTML=`<p class="crm-muted">${count(data.total)} pessoas · consulta em ${escape(date(data.as_of))}. Campo vazio não significa falta de interesse.</p><div class="crm-table-wrap"><table><thead><tr><th>Campo</th><th>Preenchido</th><th>Ausente</th><th>Inválido</th></tr></thead><tbody>${data.fields.map(f=>`<tr><td>${escape(fieldLabels[f.key]||f.key)}</td><td>${count(f.filled)}</td><td>${count(f.missing)}</td><td>${count(f.invalid)}</td></tr>`).join('')}</tbody></table></div><p class="crm-muted">Períodos observados nas fontes; registros anteriores ou não identificados podem não aparecer.</p><div class="crm-coverage-sources">${data.sources.map(s=>`<span>${escape(sourceLabels[s.key]||s.key)} · ${escape(sourceStatus[s.status]||s.status)}${s.from?` · ${escape(sourceDate(s.from))} a ${escape(sourceDate(s.to))}`:''}</span>`).join('')}</div>`;}catch(error){if(request===state.coverageRequest&&state.audience?.id===selected.id)$('#coverageContent').textContent='Cobertura indisponível. Use Recalcular para tentar novamente.';}}
  $('#audienceCoverage').addEventListener('toggle',()=>{if($('#audienceCoverage').open&&state.audience)loadCoverage(state.audience);});
  $('#coverageRefresh').onclick=()=>{if(state.audience)loadCoverage(state.audience);};
  async function loadRecommendations(selected){const ticket=++state.recommendationRequest;$('#recommendationContext').textContent=`Público v${selected.current_version} · sugestões baseadas apenas nos critérios deste público.`;$('#recommendationList').textContent='Consultando sugestões…';try{const result=await api('audiences.recommendations',{id:selected.id,version:selected.current_version});if(ticket!==state.recommendationRequest||state.audience?.id!==selected.id||state.audience?.current_version!==selected.current_version)return;if(!result.items.length){const reasons={audience_needs_refinement:'Este público usa “qualquer critério”. Refine-o antes de preparar uma mensagem comum.',consent_not_available:'Este público seleciona pessoas sem opt-in comercial.',source_unavailable:'Uma fonte deixou de estar disponível.',no_matching_signal:'Nenhuma sugestão para os critérios atuais.'};$('#recommendationList').textContent=reasons[result.reason]||'Nenhuma sugestão disponível.';return;}const module=await import('/crm-interno/crm-recommendations.js?v=1');if(ticket!==state.recommendationRequest)return;module.renderRecommendations({container:$('#recommendationList'),items:result.items,onPrepareDraft:item=>task(null,()=>prepareRecommendation(item,selected))});}catch(error){if(ticket===state.recommendationRequest)$('#recommendationList').textContent='Sugestões indisponíveis. Feche e abra esta seção para tentar novamente.';}}
  $('#audienceRecommendations').addEventListener('toggle',()=>{if($('#audienceRecommendations').open&&state.audience)loadRecommendations(state.audience);});
  let historyPanel,planningModule,planningPromise;
  async function initPlanning(){if(planningModule)return planningModule;if(!planningPromise)planningPromise=import('/crm-interno/crm-calendar.js?v=5').then(module=>planningModule=module.initPlanning({api,escape,date,notify:message})).catch(error=>{planningPromise=null;throw error;});return planningPromise;}
  async function loadHistory(selected){if(!historyPanel){const module=await import('/crm-interno/crm-audience-history.js?v=3');historyPanel=module.createAudienceHistory({api,escape,date,container:$('#audienceHistoryContent')});}await historyPanel.load(selected);}
  $('#audienceHistory').addEventListener('toggle',()=>{if($('#audienceHistory').open&&state.audience)loadHistory(state.audience);});
  $('#audienceOverlap').addEventListener('toggle',()=>{if($('#audienceOverlap').open&&state.audience)initPlanning().then(planning=>planning.loadChoices(state.audience));});
  async function selectAudience(id){const request=++state.selectionRequest;state.evaluationRequest++;state.eligibilityRequest++;state.coverageRequest++;state.recommendationRequest++;state.evaluationPolicy=null;state.audience=null;$('#audienceEligibility').hidden=true;$('#audienceCoverage').hidden=true;$('#audienceRecommendations').hidden=true;$('#audienceHistory').hidden=true;$('#audienceOverlap').hidden=true;$('#editAudience').hidden=true;$('#campaignFromAudience').hidden=true;$('#selectedAudienceName').textContent='Carregando público…';$('#userSummary').textContent='Consultando os critérios salvos.';$('#userRows').innerHTML='<tr><td colspan="4">Carregando usuários…</td></tr>';$('#userPrev').disabled=true;$('#userNext').disabled=true;$('#userPage').textContent='';const selected=await api('audiences.get',{id});if(request!==state.selectionRequest)return;state.audience=selected;$('#selectedAudienceName').textContent=selected.name;$('#editAudience').hidden=false;$$('[data-audience]').forEach(b=>b.classList.toggle('is-selected',Number(b.dataset.audience)===id));await evaluate(1);if(request===state.selectionRequest){$('#audienceCoverage').hidden=false;$('#audienceRecommendations').hidden=false;$('#audienceHistory').hidden=false;$('#audienceOverlap').hidden=false;$('#coverageContent').textContent='Abra para consultar a cobertura.';$('#recommendationList').textContent='Abra para consultar sugestões.';loadEligibility(selected);if($('#audienceCoverage').open)loadCoverage(selected);if($('#audienceRecommendations').open)loadRecommendations(selected);if($('#audienceHistory').open)loadHistory(selected);if($('#audienceOverlap').open)initPlanning().then(planning=>planning.loadChoices(selected));}}
  async function loadAudiences(){
    const request=++state.listRequest;const data=await api('audiences.list',{page:state.ap,term:$('#audienceSearch').value,include_counts:true});if(request!==state.listRequest)return;
    state.audiences=data.items;$('#audienceTotal').textContent=data.total.toLocaleString('pt-BR');
    $('#audienceList').innerHTML=data.items.length?data.items.map(a=>`<button data-audience="${a.id}" class="${state.audience?.id===a.id?'is-selected':''}" title="${escape(a.description||a.name)}"><span class="crm-audience-name">${escape(a.name)}<small>v${a.current_version}</small></span><span class="crm-member-count">${a.count_status==='ready'?Number(a.member_count).toLocaleString('pt-BR'):'—'}<small>${a.count_status==='ready'?'pessoas':'indisponível'}</small></span></button>`).join(''):'<p class="crm-empty">Nenhum público encontrado.</p>';
    $('#audiencePage').textContent=`${state.ap} / ${Math.max(1,Math.ceil(data.total/25))}`;$('#audiencePrev').disabled=state.ap<=1;$('#audienceNext').disabled=state.ap*25>=data.total;
    $('#audienceCountTime').textContent=data.counted_at?`Contagem em ${date(data.counted_at)}`:'';
    $$('[data-audience]').forEach(b=>b.onclick=()=>task(b,async()=>{await selectAudience(Number(b.dataset.audience));}));
  }
  let searchTimer;$('#audienceSearch').addEventListener('input',()=>{state.ap=1;state.listRequest++;clearTimeout(searchTimer);searchTimer=setTimeout(()=>task(null,loadAudiences),300);});
  async function evaluate(page){if(!state.audience)return;const chosen=state.audience.policy;const request=++state.evaluationRequest;const data=await api('audiences.evaluate',{policy:chosen,page});if(request!==state.evaluationRequest)return;state.up=page;state.evaluationPolicy=chosen;state.userTotal=data.total;$('#userSummary').textContent=`${data.total.toLocaleString('pt-BR')} usuários · consulta em ${date(data.as_of)} · elegibilidade de cada canal será revisada na campanha.`;$('#userRows').innerHTML=data.users.length?data.users.map(u=>`<tr><td>${escape(u.name)}<small>${escape(u.email)}</small></td><td>${escape([u.cidade,u.estado].filter(Boolean).join(' / ')||'Não informada')}</td><td><ul class="crm-reasons">${u.reasons.map(r=>`<li>${escape(r)}</li>`).join('')}</ul></td><td><button class="crm-link" data-profile="${u.id}">Ver perfil</button></td></tr>`).join(''):'<tr><td colspan="4">Nenhum usuário corresponde aos critérios com os dados disponíveis.</td></tr>';$('#userPage').textContent=`Página ${page} de ${Math.max(1,Math.ceil(data.total/25))}`;$('#userPrev').disabled=page<=1;$('#userNext').disabled=page*25>=data.total;$('#campaignFromAudience').hidden=!state.audience;$$('[data-profile]').forEach(b=>b.onclick=()=>task(b,()=>profile(Number(b.dataset.profile),b)));}
  let profilePanel;
  let opportunitiesModule,opportunitiesPromise;
  async function initOpportunities(){if(opportunitiesModule)return opportunitiesModule;if(!opportunitiesPromise)opportunitiesPromise=import('/crm-interno/crm-opportunities.js?v=4').then(module=>opportunitiesModule=module.initOpportunities({api,escape,date,openProfile:profile,notify:message})).catch(error=>{opportunitiesPromise=null;throw error;});return opportunitiesPromise;}
  let programModule,programPromise;
  async function initProgram(){if(programModule)return programModule;if(!programPromise)programPromise=import('/crm-interno/crm-program.js?v=8').then(module=>programModule=module.initProgram({api,escape,date,openProfile:profile,notify:message})).catch(error=>{programPromise=null;throw error;});return programPromise;}
  $('[data-program-open]').onclick=e=>task(e.currentTarget,async()=>{const program=await initProgram();await program.open();});
  async function profile(id,origin){if(!profilePanel){const module=await import('/crm-interno/crm-profile.js?v=2');profilePanel=module.createProfilePanel({api,escape,date,onOpportunity:async detail=>{const opportunities=await initOpportunities();if(detail.opportunityId)await opportunities.open(detail.opportunityId);else await opportunities.openForUser(detail.userId,detail.userName);}});}await profilePanel.open(id,origin);}
  $('#newAudience').onclick=()=>openAudienceEditor();$('#editAudience').onclick=()=>openAudienceEditor(state.audience);
  $('#addCriterion').onclick=()=>{addCriterion();invalidateAudience();};$('#audienceForm').addEventListener('input',invalidateAudience);
  $('#audienceForm').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{const request=++state.editorRequest;const data=await api('audiences.evaluate',{policy:policy(),page:1});if(request===state.editorRequest&&$('#audienceEditor').open)$('#audienceSize').textContent=Number(data.total).toLocaleString('pt-BR');});};
  function editorBusy(value){state.editorSaving=value;$$('input,select,textarea,button',$('#audienceEditor')).forEach(control=>control.disabled=value);}
  $('#saveAudience').onclick=e=>task(e.currentTarget,async()=>{const f=$('#audienceForm');if(!f.reportValidity())return;if(!f.elements.name.value.trim()){message('Informe um nome para salvar este público.');f.elements.name.focus();return;}const editing=state.editingAudience;const input={name:f.elements.name.value,description:f.elements.description.value,policy:policy(),...(editing?{id:editing.id,expected_version:editing.current_version}:{})};let result;editorBusy(true);try{result=await api('audiences.save',input);}finally{editorBusy(false);}closeAudienceEditor();await selectAudience(result.id);await loadAudiences();if(!$('#audienceEditor').open)message('Público salvo. Os usuários exibidos usam os critérios salvos.');});
  $('#archiveAudience').onclick=e=>task(e.currentTarget,async()=>{const editing=state.editingAudience;if(!editing)return;editorBusy(true);try{await api('audiences.archive',{id:editing.id,expected_version:editing.current_version});}finally{editorBusy(false);}closeAudienceEditor();if(state.audience?.id===editing.id)clearSelection();await loadAudiences();message('Público arquivado.');});
  $$('[data-quick-filter]').forEach(b=>b.onclick=()=>{if(!state.catalog)return;const initial=$$('.crm-criterion');if(initial.length===1&&$('[data-type]',initial[0]).value==='profile_state'&&!$('[data-key=state]',initial[0]).value)initial[0].remove();addCriterion({type:b.dataset.quickFilter});invalidateAudience();const last=$$('.crm-criterion').at(-1);last.scrollIntoView({block:'nearest',behavior:'smooth'});$('[data-key]',last)?.focus();});
  $$('[data-preset]').forEach(b=>b.onclick=()=>{const presets={half:{type:'recent_result',days:30,distance:'half'},agenda:{type:'event_offers_distance',days:90,event_id:0,distance:'half'},visits:{type:'site_access',days:30,minimum:3}};setAudience(null,presets[b.dataset.preset]);});
  function dateInput(value){if(!value)return '';const d=new Date(value);if(Number.isNaN(d.valueOf()))return String(value).slice(0,16);const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);return parts.replace(' ','T');}
  async function editCampaign(id=null){const form=$('#campaignForm');state.campaign=id?await api('campaigns.get',{id}):null;state.preview=null;state.requestId=null;let options=[];for(let page=1;page<=20;page++){const list=await api('audiences.list',{page});options.push(...list.items);if(list.items.length<25)break;}if(state.campaign&&!options.some(a=>a.id===state.campaign.audience_id))options.push({id:state.campaign.audience_id,name:state.campaign.audience_name});form.reset();form.elements.audience_id.innerHTML=options.map(a=>`<option value="${a.id}">${escape(a.name)}</option>`).join('');if(state.audience)form.elements.audience_id.value=state.audience.id;const c=state.campaign;if(c){for(const key of ['name','audience_id','channel','priority','destination'])form.elements[key].value=c[key];for(const key of ['title','body','button'])form.elements[key].value=c.content[key];form.elements.conversion_goal.value=c.content.conversion_goal||c.content.CONVERSION_GOAL||'none';for(const key of ['starts_at','ends_at'])form.elements[key].value=dateInput(c[key]);}else{form.elements.starts_at.value=dateInput(new Date());form.elements.ends_at.value=dateInput(new Date(Date.now()+7*86400000));}$('#campaignHeading').textContent=c?`Campanha · versão ${c.revision}`:'Nova campanha';$('#campaignAudienceVersion').textContent=c?`Público ${c.audience_name} · versão ${c.audience_version} no rascunho.`:state.audience?`Público ${state.audience.name} · versão ${state.audience.current_version} nesta consulta. A versão vigente será conferida ao salvar.`:'';$('#reviewCampaign').disabled=!c;const notice=$('#campaignMessage');notice.textContent='';notice.hidden=true;const editor=$('#campaignEditor');if(!editor.open)editor.showModal();form.elements.name.focus();}
  async function prepareRecommendation(item,selected){const latest=await api('audiences.get',{id:selected.id});if(latest.current_version!==selected.current_version)throw new Error('Este público mudou. Reabra-o antes de preparar a campanha.');tab('campaigns');await editCampaign();const form=$('#campaignForm');form.elements.audience_id.value=selected.id;form.elements.name.value=`${item.title} · ${selected.name}`.slice(0,160);for(const key of ['title','body','button','channel'])form.elements[key].value=item.template[key];form.elements.destination.value='';$('#campaignAudienceVersion').textContent=`Sugestão para ${selected.name} · versão ${selected.current_version} na consulta. Escolha o destino e revise os destinatários antes de confirmar.`;form.elements.destination.focus();}
  async function loadCampaigns(){
    const d=await api('campaigns.list',{page:state.cp});
    $('#campaignPage').textContent=`Página ${state.cp}`;
    $('#campaignPrev').disabled=state.cp<=1;
    $('#campaignNext').disabled=d.items.length<25;
    $('#campaignList').innerHTML=d.items.length?d.items.map(c=>`<div class="crm-campaign-row"><button type="button" class="crm-campaign-summary" data-campaign-details="${Number(c.id)}" aria-haspopup="dialog" aria-controls="campaignDetailsDialog"><span class="crm-campaign-summary-main"><strong>${escape(c.name)}</strong><span class="crm-tag">${escape(labels[c.status]||c.status)}</span></span><span class="crm-campaign-summary-meta">${escape(labels[c.channel]||c.channel)} · ${escape(c.audience_name)}</span><span class="crm-campaign-summary-time">${escape(date(c.starts_at))} → ${escape(date(c.ends_at))}</span><span class="crm-campaign-summary-open">Ver detalhes</span></button></div>`).join(''):'<p class="crm-empty">Nenhuma campanha criada. Comece por um público salvo.</p>';
    $$('#campaignList [data-campaign-details]').forEach(button=>button.onclick=()=>task(button,()=>showCampaignDetails(Number(button.dataset.campaignDetails))));
  }
  async function showCampaignDetails(id){
    const c=await api('campaigns.get',{id});
    const content=c.content||{};
    const goal=content.conversion_goal==='todosantodia_signup'?'Início de inscrição no Todo Santo Dia':'Sem objetivo mensurável';
    const details=$('#campaignDetailsDialog');
    $('#campaignDetailsHeading').textContent=c.name;
    $('#campaignDetailsBody').innerHTML=`<div class="crm-campaign-facts"><div><small>Situação</small><strong>${escape(labels[c.status]||c.status)}</strong></div><div><small>Canal</small><strong>${escape(labels[c.channel]||c.channel)}</strong></div><div><small>Público</small><strong>${escape(c.audience_name)} · versão ${Number(c.audience_version)}</strong></div><div><small>Versão da campanha</small><strong>${Number(c.revision)}</strong></div><div><small>Início (Brasília)</small><strong>${escape(date(c.starts_at))}</strong></div><div><small>Fim (Brasília)</small><strong>${escape(date(c.ends_at))}</strong></div><div><small>Objetivo</small><strong>${escape(goal)}</strong></div>${c.channel==='card'?`<div><small>Prioridade do card</small><strong>${Number(c.priority)}</strong></div>`:''}</div><h3>Mensagem e destino</h3><div class="crm-preview-card"><h3>${escape(content.title||'Sem título')}</h3><p>${escape(content.body||'')}</p><strong>${escape(content.button||'')}</strong><p class="crm-break">${escape(c.destination||'')}</p></div>`;
    const actions=$('#campaignDetailsActions');
    actions.innerHTML=`${['draft','reviewed'].includes(c.status)?`<button type="button" data-edit="${id}">Editar / revisar</button>`:''}<button type="button" data-report="${id}">Resultados</button><button type="button" data-duplicate="${id}">Duplicar</button>${['active','scheduled','running','paused'].includes(c.status)?`<button type="button" data-transition="${c.status==='paused'?'resume':'pause'}">${c.status==='paused'?'Retomar':'Pausar'}</button>`:''}${!['completed','cancelled','failed'].includes(c.status)?'<button type="button" data-transition="cancel">Cancelar</button>':''}`;
    const notice=$('#campaignDetailsMessage');notice.textContent='';notice.hidden=true;
    if(!details.open)details.showModal();
    details.scrollTop=0;
    const edit=$('[data-edit]',actions);if(edit)edit.onclick=()=>task(edit,async()=>{details.close();await editCampaign(id);});
    const results=$('[data-report]',actions);results.onclick=()=>task(results,async()=>{details.close();await report(id);});
    const duplicate=$('[data-duplicate]',actions);duplicate.onclick=()=>task(duplicate,async()=>{details.close();await editCampaign(id);state.campaign=null;$('#campaignForm').elements.name.value+=' (cópia)';$('#campaignHeading').textContent='Nova campanha';$('#reviewCampaign').disabled=true;});
    $$('[data-transition]',actions).forEach(button=>button.onclick=()=>task(button,async()=>{const action=button.dataset.transition;await api('campaigns.transition',{id,revision:Number(c.revision),transition:action});await loadCampaigns();await showCampaignDetails(id);message(`Campanha ${action==='pause'?'pausada':action==='resume'?'retomada':'cancelada'}.`);}));
  }
  $('#closeCampaignDetails').onclick=()=>$('#campaignDetailsDialog').close();
  $('#newCampaign').onclick=e=>task(e.currentTarget,()=>editCampaign());$('#campaignFromAudience').onclick=e=>task(e.currentTarget,async()=>{tab('campaigns');await editCampaign();});$('#closeCampaign').onclick=()=>$('#campaignEditor').close();
  $('#campaignForm').addEventListener('input',()=>{$('#reviewCampaign').disabled=true;state.preview=null;});
  $('#campaignForm').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{const raw=Object.fromEntries(new FormData(e.target));raw.audience_id=Number(raw.audience_id);raw.priority=Number(raw.priority);raw.starts_at+=':00-03:00';raw.ends_at+=':00-03:00';if(state.campaign){raw.id=state.campaign.campaign_id;raw.expected_revision=state.campaign.revision;}const saved=await api('campaigns.save',raw);state.campaign=await api('campaigns.get',{id:saved.id});$('#reviewCampaign').disabled=false;$('#campaignHeading').textContent=`Campanha · versão ${saved.revision}`;await loadCampaigns();message('Rascunho salvo. Revise os destinatários antes de confirmar.');});};
  async function reviewPage(page=1){const pv=page===1&&!state.preview?await api('campaigns.preview',{id:state.campaign.campaign_id,revision:state.campaign.revision}):await api('campaigns.review',{preview_id:state.preview.id,page});state.preview=pv;state.requestId ||= crypto.randomUUID();const c=state.campaign;dialog('Revisar e confirmar',`<p><strong>${escape(c.name)}</strong> · versão ${c.revision} · ${escape(labels[c.channel])}</p><p>Público: ${escape(c.audience_name)} · versão ${c.audience_version}<br>Período: ${escape(date(c.starts_at))} → ${escape(date(c.ends_at))}</p><div class="crm-preview-card"><h3>${escape(c.content.title)}</h3><p>${escape(c.content.body)}</p><strong>${escape(c.content.button)}</strong><p class="crm-break">${escape(c.destination)}</p></div><div class="crm-kpis"><div><strong>${pv.total}</strong><span>No público</span></div><div><strong>${pv.eligible}</strong><span>Elegíveis</span></div><div><strong>${pv.total-pv.eligible}</strong><span>Excluídos</span></div></div><p class="crm-muted">Lista fixada em ${escape(date(pv.as_of))}. Revisão válida até ${escape(date(pv.expires_at))}. O envio revalida preferências e critérios, sem incluir novas pessoas.</p><div class="crm-table-wrap"><table><thead><tr><th>Usuário</th><th>Motivo</th><th>Elegibilidade</th></tr></thead><tbody>${pv.members.map(m=>`<tr><td>${escape(m.name)}</td><td>${(typeof m.reasons==='string'?JSON.parse(m.reasons):m.reasons||[]).map(escape).join('<br>')}</td><td>${m.eligible?'Elegível':escape(labels[m.exclusion_code]||m.exclusion_code)}</td></tr>`).join('')||'<tr><td colspan="3">Lista vazia.</td></tr>'}</tbody></table></div><div class="crm-line"><button id="reviewPrev" ${page<=1?'disabled':''}>Anterior</button><span>Página ${page}</span><button id="reviewNext" ${page*25>=pv.total?'disabled':''}>Próxima</button></div><div class="crm-actions"><button id="confirmCampaign" class="crm-primary" ${!pv.eligible||!state.catalog.enabled?'disabled':''}>Confirmar campanha para ${pv.eligible} pessoas</button></div>`);$('#reviewPrev').onclick=e=>task(e.currentTarget,()=>reviewPage(page-1));$('#reviewNext').onclick=e=>task(e.currentTarget,()=>reviewPage(page+1));$('#confirmCampaign').onclick=e=>task(e.currentTarget,async()=>{await api('campaigns.confirm',{preview_id:pv.id,request_id:state.requestId});$('#crmDialog').close();$('#campaignEditor').close();await loadCampaigns();message('Campanha confirmada. A execução seguirá o período definido e as preferências de cada pessoa.');});}
  $('#reviewCampaign').onclick=e=>task(e.currentTarget,async()=>{state.preview=null;state.requestId=null;await reviewPage();});
  async function report(id){
    const r=await api('campaigns.report',{id});
    const conversion=r.conversion_tracking_available?`<h3 style="margin-top:24px">Objetivo: Todo Santo Dia</h3><p><strong>${Number(r.challenge_signup_starts||0).toLocaleString('pt-BR')}</strong> inícios de inscrição atribuídos</p><p class="crm-muted">Eventos novos desde ${escape(date(r.source_started_at))}. Cada pessoa conta uma vez; a atribuição usa o último clique registrado até 7 dias antes do início. Não confirma conclusão, pagamento ou causa da inscrição.</p>`:'<p class="crm-muted">Esta campanha não tem objetivo de conversão mensurável configurado.</p>';
    dialog('Resultados da campanha',`<h3>Processamento por pessoa</h3>${r.deliveries.length?'<table><thead><tr><th>Estado</th><th>Motivo</th><th>Pessoas</th></tr></thead><tbody>'+r.deliveries.map(d=>`<tr><td>${escape(labels[d.status]||d.status)}</td><td>${escape(labels[d.error_code]||d.error_code||'—')}</td><td>${d.total}</td></tr>`).join('')+'</tbody></table>':'<p>Nenhum processamento registrado.</p>'}<h3 style="margin-top:24px">Interações registradas</h3>${r.events.length?r.events.map(e=>`<p>${escape(labels[e.kind]||e.kind)}: <strong>${e.total}</strong> · ${e.users} pessoas</p>`).join(''):'<p>Nenhuma interação registrada.</p>'}${conversion}<p class="crm-muted">“Aceita pelo canal” confirma o processamento do envio ou a impressão do card. Entrega na caixa de entrada, abertura de e-mail e valores de vendas ainda não têm integração de medição. Cliques não distinguem verificadores de links.</p>`);
  }
  function sources(){const entries=Object.entries(state.catalog.capabilities);$('#sourceList').innerHTML=entries.map(([type,c])=>`<div class="crm-source-row"><div><strong>${escape(c.label)}</strong><p>${escape(c.source||c.reason)}${type==='site_access'?`<br>Cobertura observada: ${c.coverage_from?escape(date(c.coverage_from)):'ainda não iniciada'} · ${c.measured_days||0} dias medidos. A coleta é parcial e respeita opt-out.`:''}</p></div><span class="crm-tag">${c.available?'Disponível':'Indisponível'}</span></div>`).join('');}
  for(const [prefix,key,load] of [['audience','ap',loadAudiences],['campaign','cp',loadCampaigns]])for(const [suffix,delta] of [['Prev',-1],['Next',1]])$('#'+prefix+suffix).onclick=e=>task(e.currentTarget,async()=>{state[key]+=delta;await load();});
  function userPages(){const ready=!!state.audience&&!!state.evaluationPolicy;$('#userPrev').disabled=!ready||state.up<=1;$('#userNext').disabled=!ready||state.up*25>=state.userTotal;}$('#userPrev').onclick=e=>task(e.currentTarget,()=>evaluate(state.up-1)).then(userPages);$('#userNext').onclick=e=>task(e.currentTarget,()=>evaluate(state.up+1)).then(userPages);
  task(null,async()=>{state.catalog=await api('catalog');$('#crmAvailability').textContent=state.catalog.enabled?'Revisão manual ativa':'Publicação de campanhas desativada';sources();clearSelection();await Promise.all([loadAudiences(),loadCampaigns()]);await Promise.all([initOpportunities(),initPlanning()]);});
})();
