<cfprocessingdirective pageencoding="utf-8">
<cfset VARIABLES.theme="dark"><cfset VARIABLES.template="/crm-interno/">
<cfinclude template="../includes/backend/backend_login.cfm">
<cfinclude template="../includes/backend/require_admin_dev.cfm">
<cfinclude template="../includes/backend/require_real_platform_context.cfm">
<cflock scope="session" type="exclusive" timeout="3"><cfif NOT structKeyExists(SESSION,'crmInternalCsrf')><cfset SESSION.crmInternalCsrf=lCase(hash(createUUID() & createUUID(),'SHA-256'))></cfif></cflock>
<!doctype html><html lang="pt-BR"><cfinclude template="../includes/estrutura/head.cfm">
<link rel="stylesheet" href="/crm-interno/crm.css?v=20">
<body data-mdb-theme="dark" class="bg-dark-subtle crm-workspace"><cfinclude template="../includes/estrutura/header.cfm">
<main id="crmApp" class="crm-app container-fluid px-3 px-lg-4" data-csrf="<cfoutput>#encodeForHTMLAttribute(SESSION.crmInternalCsrf)#</cfoutput>">
 <div class="crm-heading"><div><div class="crm-eyebrow">RELACIONAMENTO · ADMINISTRAÇÃO</div><h1>CRM interno</h1><p>Encontre públicos, prepare a mensagem e revise antes de ativar.</p></div><span id="crmAvailability" class="crm-tag">Conectando…</span></div>
 <div id="crmMessage" role="status" aria-live="polite" hidden></div>
 <nav class="crm-tabs" aria-label="Áreas do CRM"><button data-tab="audiences" aria-current="page">Públicos</button><button data-tab="opportunities">Oportunidades</button><button data-tab="planning">Planejamento</button><button data-tab="campaigns">Campanhas</button><button data-tab="sources">Dados disponíveis</button></nav>
 <section data-panel="audiences">
  <div class="crm-grid">
   <aside class="crm-box crm-audiences"><div class="crm-line"><h2>Públicos <small id="audienceTotal"></small></h2><button id="newAudience" class="crm-link">Novo público</button></div><label class="crm-search"><span class="crm-sr-only">Buscar público</span><input id="audienceSearch" type="search" placeholder="Buscar público…" maxlength="160"></label><div id="audienceList" class="crm-list">Carregando…</div><div class="crm-line"><button id="audiencePrev" class="crm-link">Anterior</button><span id="audiencePage"></span><button id="audienceNext" class="crm-link">Próxima</button></div><p id="audienceCountTime" class="crm-muted"></p><small class="crm-muted">Pessoas no público; elegibilidade de envio revisada na campanha. Os públicos podem se sobrepor.</small></aside>
   <div class="crm-box crm-results"><div class="crm-line"><div><h2 id="selectedAudienceName">Usuários do público</h2><p id="userSummary" class="crm-muted">Selecione um público na lista para ver seus usuários.</p></div><div class="crm-result-actions"><button id="editAudience" hidden>Editar público</button><button id="campaignFromAudience" hidden>Criar campanha</button></div></div><section id="audienceEligibility" class="crm-eligibility" aria-label="Pessoas aptas por canal" hidden><div class="crm-line"><div><strong>Aptos por canal</strong><small id="eligibilityStamp" class="crm-muted"></small></div><button id="eligibilityRefresh" class="crm-link" type="button">Recalcular</button></div><div id="eligibilityCards" role="status" aria-live="polite">Consultando elegibilidade…</div><p class="crm-muted">Estimativa para este público. Preferências e limites são verificados novamente antes de cada envio.</p></section><details id="audienceCoverage" class="crm-coverage" hidden><summary>Cobertura dos dados deste público</summary><div class="crm-line"><small class="crm-muted">Campos do público selecionado; períodos das fontes no cadastro geral.</small><button id="coverageRefresh" type="button" class="crm-link">Recalcular</button></div><div id="coverageContent" role="status" aria-live="polite">Abra para consultar a cobertura.</div></details><details id="audienceRecommendations" class="crm-coverage" hidden><summary>Ideias de campanha para este público</summary><p id="recommendationContext" class="crm-muted"></p><div id="recommendationList" role="status" aria-live="polite"></div></details><details id="audienceHistory" class="crm-coverage" hidden><summary>Evolução diária deste público</summary><div id="audienceHistoryContent" role="status" aria-live="polite">Abra para consultar o histórico real.</div></details><details id="audienceOverlap" class="crm-coverage" hidden><summary>Sobreposição com outros públicos</summary><p class="crm-muted">Selecione até quatro outros públicos. O total único não soma pessoas repetidas.</p><div id="overlapChoices" class="crm-overlap-choices"></div><button id="overlapCompare" type="button">Comparar públicos</button><div id="overlapResult" role="status" aria-live="polite"></div></details><div class="crm-table-wrap"><table><thead><tr><th>Usuário</th><th>Localidade</th><th>Motivo da seleção</th><th></th></tr></thead><tbody id="userRows"><tr><td colspan="4">Selecione um público para começar.</td></tr></tbody></table></div><div class="crm-line"><button id="userPrev" class="crm-link" disabled>Anterior</button><span id="userPage"></span><button id="userNext" class="crm-link" disabled>Próxima</button></div></div>
  </div>
 </section>
 <section data-panel="opportunities" hidden><div class="crm-line crm-section-heading"><div><h2>Oportunidades e próximos retornos</h2><p class="crm-muted">Registros internos por pessoa; não enviam mensagens nem comprovam receita.</p></div></div><div class="crm-box crm-opportunity-filters"><label>Responsável<select id="opportunityOwner"><option value="">Todos</option></select></label><label>Etapa<select id="opportunityStage"><option value="">Todas</option><option value="new">Nova</option><option value="contacting">Em contato</option><option value="interested">Interessado</option><option value="converted">Convertida manualmente</option><option value="closed">Encerrada</option></select></label><label>Prazo<select id="opportunityDue"><option value="">Todos</option><option value="overdue">Vencidas</option><option value="today">Hoje</option><option value="upcoming">Próximas</option><option value="none">Sem prazo</option></select></label><button id="opportunityRefresh" type="button">Atualizar</button></div><div id="opportunitySummary" class="crm-opportunity-summary" role="status" aria-live="polite">Consultando indicadores…</div><div id="opportunityList" class="crm-box" role="status" aria-live="polite">Abra uma ficha de usuário para registrar a primeira oportunidade.</div><div class="crm-line"><button id="opportunityPrev" class="crm-link">Anterior</button><span id="opportunityPage"></span><button id="opportunityNext" class="crm-link">Próxima</button></div></section>
 <section data-panel="planning" hidden><div class="crm-line crm-section-heading"><div><h2>Planejamento de campanhas</h2><p class="crm-muted">CRM, ads, banners e Todo Santo Dia na mesma linha do tempo.</p></div></div><form id="calendarFilters" class="crm-box crm-calendar-filters"><label>De<input name="from" type="date" required></label><label>Até<input name="to" type="date" required></label><button type="submit">Consultar</button><details id="calendarAdvancedFilters" class="crm-planning-advanced"><summary>Filtros CRM <span id="calendarFilterCount" hidden></span></summary><div class="crm-planning-filter-menu"><label>Canal CRM<select name="channel"><option value="">Todos</option><option value="email">E-mail</option><option value="notification">Notificação</option><option value="card">Card no perfil</option></select></label><label>Estado CRM<select name="status"><option value="">Todos</option><option value="draft">Rascunho</option><option value="reviewed">Em revisão</option><option value="scheduled">Agendada</option><option value="running">Em envio</option><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option><option value="cancelled">Cancelada</option><option value="failed">Falha</option></select></label><small>Canal e estado filtram apenas as campanhas CRM.</small></div></details></form><div id="planningGantt" class="crm-box" role="region" aria-label="Gantt das campanhas">Consultando linha do tempo…</div><details id="calendarAgenda" class="crm-box crm-planning-agenda"><summary>Agenda CRM <span id="calendarAgendaCount" class="crm-muted">Consultando…</span></summary><div id="planningPressure" class="crm-box" role="status" aria-live="polite" hidden></div><div id="calendarList" role="status" aria-live="polite">Consultando calendário CRM…</div><div class="crm-line crm-planning-pages"><button id="calendarPrev" class="crm-link" disabled>Anterior</button><span id="calendarPage"></span><button id="calendarNext" class="crm-link" disabled>Próxima</button></div></details></section>
 <section data-panel="campaigns" hidden><div class="crm-line crm-section-heading"><div><h2>Campanhas revisadas</h2><p class="crm-muted">Notificações, e-mail e cards no mini perfil. Salvar não envia.</p></div><button id="newCampaign" class="crm-primary">Nova campanha</button></div>
  <div id="crmProgramEntry" class="crm-box crm-program-entry"><div><small class="crm-muted">CAMPANHA CONTÍNUA</small><h3>Todo Santo Dia</h3><p data-program-entry-summary>Ativa · acompanhamento da base, inscrições e compras; sem envio automático.</p></div><button type="button" data-program-open aria-haspopup="dialog" aria-controls="crmProgram">Ver andamento</button></div>
  <dialog id="crmProgram" class="crm-dialog crm-program crm-program-dialog" aria-labelledby="crmProgramHeading"><div class="crm-line"><div><small class="crm-muted">TODO SANTO DIA · CAMPANHA CONTÍNUA</small><h2 id="crmProgramHeading">Acompanhamento</h2><p class="crm-muted" data-program-status>Consultando…</p></div><button type="button" data-program-close class="crm-link">Fechar</button></div><div data-program-message class="crm-modal-message" role="status" aria-live="polite" hidden></div>
   <form data-program-filters class="crm-program-filters"><label>De<input name="from" type="date" required></label><label>Até<input name="to" type="date" required></label><label>Agrupar<select name="bucket"><option value="week">Semana</option><option value="month">Mês</option></select></label><button type="submit">Atualizar</button></form>
   <div class="crm-program-kpis"><div><small>Base cadastrada atual</small><strong data-program-registrants>—</strong><span data-program-registrants-asof></span></div><div><small>Inícios desde <span data-program-signups-from>—</span></small><strong data-program-signups>—</strong><span>Primeira inscrição observada no período</span></div><div><small>Compras comprovadas</small><strong data-program-orders>—</strong><span data-program-finance>Compras ainda não conciliadas</span></div></div>
   <p class="crm-muted" data-program-coverage>O histórico de inscrições começa na ativação da fonte; a base cadastrada é um retrato atual.</p><div class="crm-program-finance" data-program-finance-details hidden></div><div class="crm-program-columns"><section><h3>Evolução dos inícios</h3><div data-program-series role="status">Consultando…</div><div data-program-financial-series></div></section><section><h3>Perfil atual da base</h3><div data-program-profile role="status">Consultando…</div><div data-program-buyer-profile></div></section></div>
   <div class="crm-program-link"><button type="button" class="crm-link" data-program-link-open>Vincular campanha existente</button><form data-program-link-form hidden><label>Campanha revisada<select data-program-link-select required></select></label><button type="submit">Vincular para análise</button><p class="crm-muted">O vínculo é apenas metadado de acompanhamento; não ativa envios.</p></form><p class="crm-muted" data-program-link-status></p></div>
   <div class="crm-line crm-program-user-head"><div><h3>Usuários do programa</h3><p class="crm-muted">Pessoas identificadas na inscrição ou por pedido vinculado ao checkout autenticado.</p></div><label>Fonte<select data-program-user-source><option value="registrants">Base cadastrada atual</option><option value="signup_starts">Novos inícios observados</option><option value="buyers">Compradores comprovados</option></select></label></div><button type="button" data-program-users class="crm-link">Ver usuários</button><div class="crm-table-wrap"><table><thead><tr><th>Usuário</th><th>Localidade</th><th></th></tr></thead><tbody data-program-user-rows><tr><td colspan="3">Abra o acompanhamento para consultar usuários.</td></tr></tbody></table></div><div class="crm-line crm-program-pages"><button type="button" data-program-prev class="crm-link" disabled>Anterior</button><span data-program-page></span><button type="button" data-program-next class="crm-link" disabled>Próxima</button></div>
   <details class="crm-program-purchases" data-program-purchases><summary>Pedidos e conciliação</summary><p class="crm-muted">Pedidos comprovados por consulta ao Pagar.me e pedidos futuros pendentes. Compradores antigos sem vínculo seguro aparecem sem usuário.</p><div class="crm-table-wrap"><table><thead><tr><th>Pedido</th><th>Produto</th><th>Estado</th><th>Pagamento</th><th>Usuário</th><th>Vigência</th><th>Origem</th></tr></thead><tbody data-program-purchase-rows><tr><td colspan="7">Abra para consultar os pedidos do período.</td></tr></tbody></table></div><div class="crm-line crm-program-pages"><button type="button" data-program-purchase-prev class="crm-link" disabled>Anterior</button><span data-program-purchase-page></span><button type="button" data-program-purchase-next class="crm-link" disabled>Próxima</button></div></details>
  </dialog><div id="campaignList" class="crm-box">Carregando…</div><div class="crm-line"><button id="campaignPrev" class="crm-link">Anterior</button><span id="campaignPage"></span><button id="campaignNext" class="crm-link">Próxima</button></div>
  <dialog id="campaignEditor" class="crm-dialog crm-campaign-dialog" aria-labelledby="campaignHeading"><form id="campaignForm"><div class="crm-line"><h2 id="campaignHeading">Nova campanha</h2><button type="button" id="closeCampaign" class="crm-link">Fechar</button></div><div id="campaignMessage" class="crm-modal-message" role="status" aria-live="polite" hidden></div><div class="crm-form-grid">
   <label>Nome interno<input name="name" maxlength="160" required></label><label>Público salvo<select name="audience_id" required></select></label>
   <label>Canal<select name="channel"><option value="notification">Notificação no site</option><option value="email">E-mail marketing</option><option value="card">Card no mini perfil</option></select></label><label>Prioridade do card<input name="priority" type="number" min="0" max="100" value="0"></label>
   <label class="crm-wide">Objetivo mensurável<select name="conversion_goal"><option value="none">Sem objetivo de conversão</option><option value="todosantodia_signup">Início de inscrição no Todo Santo Dia</option></select></label>
   <label>Título / assunto<input name="title" maxlength="160" required></label><label>Texto do botão<input name="button" maxlength="60" value="Saiba mais" required></label>
   <label class="crm-wide">Mensagem<textarea name="body" maxlength="4000" rows="4" required></textarea></label><label class="crm-wide">Link de destino<input name="destination" maxlength="2048" placeholder="/busca/ ou URL HTTPS dos sites autorizados" required></label>
   <label>Início (Brasília)<input name="starts_at" type="datetime-local" required></label><label>Fim (Brasília)<input name="ends_at" type="datetime-local" required></label>
  </div><p id="campaignAudienceVersion" class="crm-muted"></p><p class="crm-muted">E-mail e notificação: no máximo um contato comercial em 7 dias por pessoa. Cards: até 3 sessões por dia, com opção de dispensar.</p><div class="crm-actions"><button type="submit" class="crm-primary">Salvar rascunho</button><button type="button" id="reviewCampaign" disabled>Revisar destinatários</button></div></form></dialog>
 </section>
 <section data-panel="sources" hidden><div class="crm-box"><h2>Origem e cobertura dos dados</h2><p>Ausência de informação não significa inatividade. Dados do Strava e seus derivados ficam fora da segmentação comercial.</p><div id="sourceList"></div></div></section>
 <dialog id="audienceEditor" class="crm-dialog crm-editor-dialog" aria-labelledby="audienceHeading">
   <div class="crm-editor"><div class="crm-line"><div><h2 id="audienceHeading">Montar público</h2><span id="audienceVersion" class="crm-muted"></span></div><button id="closeAudienceEditor" type="button" class="crm-link" aria-label="Fechar editor">Fechar</button></div><div id="audienceMessage" role="status" aria-live="polite" hidden></div><div class="crm-audience-size"><strong id="audienceSize">—</strong><small>pessoas na consulta dos critérios</small></div>
    <div class="crm-presets crm-quick-filters" aria-label="Adicionar filtros básicos"><button type="button" data-quick-filter="profile_state">+ Estado</button><button type="button" data-quick-filter="profile_city">+ Cidade</button><button type="button" data-quick-filter="profile_age">+ Idade</button><button type="button" data-quick-filter="profile_gender">+ Gênero</button><button type="button" data-quick-filter="brasil_gigante">+ Brasil Gigante</button><button type="button" data-quick-filter="challenge_enrollment">+ Desafio</button></div>
    <datalist id="crmChallengeCodes"><option value="todosantodia">Todo Santo Dia</option><option value="circuitobrasilgigante">Circuito Brasil Gigante</option></datalist>
    <details class="crm-interest-presets"><summary>Atalhos por interesse</summary><div class="crm-presets"><button data-preset="half">Correu uma meia</button><button data-preset="agenda">Meia na agenda</button><button data-preset="visits">Visita regularmente</button></div></details>
    <form id="audienceForm"><div class="crm-audience-meta"><label>Nome do público<input name="name" maxlength="160" placeholder="Ex.: interesse em meia maratona"></label>
     <label>Combinar critérios<select id="ruleOperator"><option value="all">Todos os critérios</option><option value="any">Qualquer um dos critérios</option></select></label></div><details class="crm-observation"><summary>Observação interna</summary><label><span class="crm-sr-only">Observação interna</span><input name="description" maxlength="2000" placeholder="Opcional"></label></details>
     <div id="criteria"></div><button id="addCriterion" type="button" class="crm-link">+ Adicionar critério</button>
     <div class="crm-actions"><button type="submit">Consultar quantidade</button><button id="saveAudience" type="button" class="crm-primary">Salvar público</button><button id="cancelAudienceEditor" type="button">Cancelar</button><button id="archiveAudience" type="button" hidden>Arquivar</button></div>
    </form>
   </div>
 </dialog>
 <dialog id="campaignDetailsDialog" class="crm-dialog crm-campaign-details-dialog" aria-labelledby="campaignDetailsHeading"><div class="crm-line"><h2 id="campaignDetailsHeading">Campanha</h2><button id="closeCampaignDetails" type="button" class="crm-link">Fechar</button></div><div id="campaignDetailsMessage" class="crm-modal-message" role="status" aria-live="polite" hidden></div><div id="campaignDetailsBody"></div><div id="campaignDetailsActions" class="crm-actions"></div></dialog>
 <dialog id="crmDialog" class="crm-dialog"><div class="crm-line"><h2 id="dialogTitle"></h2><button id="closeDialog" class="crm-link" aria-label="Fechar janela">Fechar</button></div><div id="dialogMessage" class="crm-modal-message" role="status" aria-live="polite" hidden></div><div id="dialogBody"></div></dialog>
 <dialog id="opportunityDialog" class="crm-dialog" aria-labelledby="opportunityDialogTitle"><div class="crm-line"><h2 id="opportunityDialogTitle">Oportunidade</h2><button id="closeOpportunityDialog" class="crm-link" type="button" aria-label="Fechar oportunidade">Fechar</button></div><div id="opportunityDialogBody"></div></dialog>
</main><cfinclude template="../includes/estrutura/footer.cfm"><script src="/crm-interno/crm.js?v=29" defer></script></body></html>
