-- Saída web 2025. Preserva saída congelada 72; altera somente geografia P09/P10.
-- Referência histórica 2025 preservada. Cidades têm nova coleta própria; outros comparativos intactos.
WITH anterior AS(SELECT result->'rows'->0->'payload' AS payload FROM estudo.notebook_runs WHERE id=72 AND frozen AND status='ok' AND NOT truncated),
cityraw AS(SELECT x->'dados' AS r FROM estudo.notebook_runs a CROSS JOIN LATERAL jsonb_array_elements(a.result->'rows') x WHERE a.id=77 AND a.frozen AND a.status='ok' AND NOT a.truncated AND x->>'bloco'='cidades'),
m AS(SELECT r->>'serie' AS serie,r->>'categoria' AS categoria,jsonb_build_object('valor',r->>'percentual','contagem',(r->>'n')::bigint,'denominador',(r->>'denominador')::bigint)||jsonb_build_object('fonte','Notebook · derivação #75 · fonte #'||(r->>'fonte'),'nota','Contagem já congelada; base própria do gráfico, sem normalização do subconjunto') AS atual,0 AS ordem FROM estudo.notebook_runs a CROSS JOIN LATERAL jsonb_array_elements(a.result->'rows') r WHERE a.id=75 AND a.frozen AND a.status='ok' AND NOT a.truncated AND (r->>'ano')::integer=2025
 UNION ALL SELECT 'cidades',r->>'rotulo',jsonb_build_object('valor',((r->>'total')::numeric*100/nullif((r->>'denominador')::numeric,0))::text,'contagem',(r->>'total')::bigint,'denominador',(r->>'denominador')::bigint)||jsonb_build_object('fonte','Notebook · #77 · célula 288 rev2 · 30/09/2026','nota','Cidade/UF: '||(r->>'rotulo')||'/'||(r->>'uf')||'; código '||(r->>'codigo')||'; '||(r->>'eventos')||' eventos validados'),(r->>'ordem')::integer FROM cityraw WHERE (r->>'ano')::integer=2025 AND (r->>'nome')||'/'||(r->>'uf') IN('SAO PAULO/SP','RIO DE JANEIRO/RJ','BELO HORIZONTE/MG','BRASILIA/DF','CURITIBA/PR','SALVADOR/BA','FORTALEZA/CE','PORTO ALEGRE/RS','BELEM/PA','RECIFE/PE','FLORIANOPOLIS/SC','GOIANIA/GO','JOAO PESSOA/PB','SANTOS/SP')),
notas AS(SELECT 'cidades' AS serie,'Coleta própria de 30/09/2026. célula 288 rev2. congelamento 77. BR. ano inteiro 2025; status 0 e homologado. sem filtro extra de conclusão. todas as modalidades e idades. Base nacional: 5.279.220 participações; 5.247.745 em cidades validadas. 31.081 em 26 eventos: Código diverge da cidade/UF; 394 em 3 eventos: Cidade/UF sem correspondência. Cidade/UF normalizada e única; código positivo precisa concordar. Pendências permanecem no denominador; agregação por evento evita multiplicação. As 14 cidades são as destacadas no PDF. não as 14 maiores atuais. Base diferente do congelamento 23 (5.279.415); não atribuir toda diferença à normalização.' AS nota UNION ALL SELECT serie,CASE WHEN serie LIKE 'ufs%' THEN 'Contagens congeladas 22 / DataGrip (vw_resultados), célula 199 rev1, coleta 28/09/2026: BR, 2025 pela data final, status 0 e homologado, sem filtro extra de conclusão, idade ou modalidade. Base 5.279.415. A seleção resumida conserva as nove UFs do PDF; Outros soma todas as restantes. Derivação 287 rev1/75; percentuais não arredondados na fonte.' ELSE 'Contagens congeladas 21, célula 195 rev1, coleta 28/09/2026: BR, status 0, homologado, ano pela data final, todas as modalidades e idades; sem filtro extra de conclusão. A view atual não é uma cópia imutável de 2025. Percentuais recalculados com as contagens, sem reutilizar arredondamentos. Dentro da região usa total regional incluindo outros/não informados; distribuição de cada gênero usa seu total nacional. Derivação 287 rev1/75. Categorias novas de recálculo não alteram a referência do PDF.' END FROM m WHERE serie<>'cidades' GROUP BY serie),
orig AS(SELECT c.value AS item,c.ordinality AS ordem FROM anterior CROSS JOIN LATERAL jsonb_array_elements(payload->'comparacoes') WITH ORDINALITY c ),
comps AS(SELECT o.item||CASE WHEN m.serie IS NOT NULL THEN jsonb_build_object('atual',m.atual,'status','notebook_em_conciliacao') ELSE '{}'::jsonb END AS item,o.ordem FROM orig o LEFT JOIN m ON m.serie=o.item->>'serie' AND m.categoria=o.item->>'categoria'
 UNION ALL SELECT jsonb_build_object('serie',m.serie,'categoria',m.categoria,'atual',m.atual,'status','notebook_em_conciliacao'),10000+row_number() OVER(ORDER BY m.serie,m.ordem,m.categoria) FROM m WHERE NOT EXISTS(SELECT 1 FROM orig o WHERE o.item->>'serie'=m.serie AND o.item->>'categoria'=m.categoria))
SELECT payload||jsonb_build_object('meta',(payload->'meta'||jsonb_build_object('contrato_versao',3))||jsonb_build_object('notebook_fontes',(payload->'meta'->'notebook_fontes')||(SELECT jsonb_agg(jsonb_build_object('execucao',id,'celula',cell_id,'revisao',cell_version,'coletado_em',started_at) ORDER BY id) FROM estudo.notebook_runs WHERE id IN(75,77) AND frozen)),'comparacoes',(SELECT jsonb_agg(item ORDER BY ordem) FROM comps),'conciliacao',jsonb_build_object('compativel_no_valor',0,'divergente',0,'nao_recalculado',0,'compativel_no_arredondamento',0,'notebook_em_conciliacao',0)||(SELECT jsonb_object_agg(status,total) FROM(SELECT item->>'status' AS status,count(*) AS total FROM comps GROUP BY 1) q),
'series',(SELECT jsonb_agg(s.value||CASE WHEN n.nota IS NOT NULL THEN jsonb_build_object('ressalva',n.nota) ELSE '{}'::jsonb END  ORDER BY s.ordinality) FROM jsonb_array_elements(payload->'series') WITH ORDINALITY s LEFT JOIN notas n ON n.serie=s.value->>'id')) AS payload
FROM anterior WHERE(SELECT count(*) FROM m WHERE serie='cidades')=14 AND NOT EXISTS(SELECT 1 FROM m WHERE atual->>'valor' IS NULL OR (atual->>'contagem')::bigint<0)
