-- Saída web 2026. Preserva saída congelada 74; altera somente geografia P09/P10.
-- Referência histórica 2025 preservada. Cidades têm nova coleta própria; outros comparativos intactos.
WITH anterior AS(SELECT result->'rows'->0->'payload' AS payload FROM estudo.notebook_runs WHERE id=74 AND frozen AND status='ok' AND NOT truncated),
cityraw AS(SELECT x->'dados' AS r FROM estudo.notebook_runs a CROSS JOIN LATERAL jsonb_array_elements(a.result->'rows') x WHERE a.id=77 AND a.frozen AND a.status='ok' AND NOT a.truncated AND x->>'bloco'='cidades'),
m AS(SELECT r->>'serie' AS serie,r->>'categoria' AS categoria,jsonb_build_object('valor',r->>'percentual','contagem',(r->>'n')::bigint,'denominador',(r->>'denominador')::bigint) AS atual,0 AS ordem FROM estudo.notebook_runs a CROSS JOIN LATERAL jsonb_array_elements(a.result->'rows') r WHERE a.id=75 AND a.frozen AND a.status='ok' AND NOT a.truncated AND (r->>'ano')::integer=2026
 UNION ALL SELECT 'cidades',r->>'rotulo'||' · '||(r->>'uf'),jsonb_build_object('valor',((r->>'total')::numeric*100/nullif((r->>'denominador')::numeric,0))::text,'contagem',(r->>'total')::bigint,'denominador',(r->>'denominador')::bigint),(r->>'ordem')::integer FROM cityraw WHERE (r->>'ano')::integer=2026 AND (r->>'ordem')::integer<=14),
notas AS(SELECT 'cidades' AS serie,'Coleta própria de 30/09/2026. célula 288 rev2. congelamento 77. BR. 01/01–26/09/2026; status 0. homologado e concluinte. todas as modalidades e idades. Base nacional: 4.274.231 participações; 4.266.163 em cidades validadas. 8.068 em 19 eventos: Cidade/UF sem correspondência. Cidade/UF normalizada e única; código positivo precisa concordar. Pendências permanecem no denominador; agregação por evento evita multiplicação. Ranking das 14 cidades validadas de maior volume. Coleta independente dos 4.214.040 resultados do panorama; não altera totais. comparativos mensais ou coortes.' AS nota UNION ALL SELECT serie,CASE WHEN serie LIKE 'ufs%' THEN 'Contagens congeladas 22 / DataGrip (vw_resultados), célula 199 rev1, coleta 28/09/2026: BR, 2025 pela data final, status 0 e homologado, sem filtro extra de conclusão, idade ou modalidade. Base 5.279.415. A seleção resumida conserva as nove UFs do PDF; Outros soma todas as restantes. Derivação 287 rev1/75; percentuais não arredondados na fonte.' ELSE 'Distribuição regional de cada gênero derivada das contagens congeladas da saída 74 (origem 33, snapshot 2026 v3), sem nova coleta. Cada gênero tem denominador nacional próprio: F=2.268.950; M=1.943.942. Norte entra pela contagem existente. Região não informada é o saldo nacional após as cinco regiões (F=8.061; M=6.598). Categorias somam 100% dentro de cada gênero. Derivação 287 rev1/75. Corte 26/09/2026 e coleta originais preservados; não compara volumes com 2025 inteiro.' END FROM m WHERE serie<>'cidades' GROUP BY serie),
orig AS(SELECT c.value AS item,c.ordinality AS ordem FROM anterior CROSS JOIN LATERAL jsonb_array_elements(payload->'comparacoes') WITH ORDINALITY c WHERE c.value->>'serie'<>'cidades'),
comps AS(SELECT o.item||CASE WHEN m.serie IS NOT NULL THEN jsonb_build_object('atual',m.atual,'status','coletado_notebook') ELSE '{}'::jsonb END AS item,o.ordem FROM orig o LEFT JOIN m ON m.serie=o.item->>'serie' AND m.categoria=o.item->>'categoria'
 UNION ALL SELECT jsonb_build_object('serie',m.serie,'categoria',m.categoria,'atual',m.atual,'status','coletado_notebook'),10000+row_number() OVER(ORDER BY m.serie,m.ordem,m.categoria) FROM m WHERE NOT EXISTS(SELECT 1 FROM orig o WHERE o.item->>'serie'=m.serie AND o.item->>'categoria'=m.categoria))
SELECT payload||jsonb_build_object('meta',(payload->'meta'||jsonb_build_object('contrato_versao',2))||jsonb_build_object('origem',(payload->'meta'->>'origem')||'; regiões por gênero derivadas do congelamento 74 via 75; cidades validadas em 77, coleta própria 30/09/2026. Outros recortes preservados'),'comparacoes',(SELECT jsonb_agg(item ORDER BY ordem) FROM comps),'conciliacao',jsonb_build_object('calculado',(SELECT count(*) FROM comps WHERE item->'atual' IS NOT NULL AND item->'atual'<>'null'::jsonb AND item->'atual'->>'valor' IS NOT NULL),'pendente',(SELECT count(*) FROM comps WHERE item->'atual' IS NULL OR item->'atual'='null'::jsonb OR item->'atual'->>'valor' IS NULL)),
'series',(SELECT jsonb_agg(s.value||CASE WHEN n.nota IS NOT NULL THEN jsonb_build_object('ressalva',n.nota) ELSE '{}'::jsonb END ||CASE WHEN s.value->>'id'='cidades' THEN jsonb_build_object('valores',(SELECT jsonb_agg(jsonb_build_object('rotulo',categoria,'valor',NULL) ORDER BY ordem) FROM m WHERE serie='cidades')) ELSE '{}'::jsonb END ORDER BY s.ordinality) FROM jsonb_array_elements(payload->'series') WITH ORDINALITY s LEFT JOIN notas n ON n.serie=s.value->>'id')) AS payload
FROM anterior WHERE(SELECT count(*) FROM m WHERE serie='cidades')=14 AND NOT EXISTS(SELECT 1 FROM m WHERE atual->>'valor' IS NULL OR (atual->>'contagem')::bigint<0)
